-- Portable promotion-style migration linking the EN Merge Conflicts
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, and
-- rebase-and-squash/V479-V480 (see those files for the full rationale).
--
-- Development Question IDs: 235, 236, 237, 238, 239, 240, 241, 242, 243, 244
-- Topic: merge-conflicts (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 235, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$According to the lesson, what is a merge conflict, fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is a merge conflict, fundamentally?$$, NULL, NULL,
           $$A merge conflict happens when Git tries to combine two sets of changes and can't automatically decide which version is correct, because both sides changed the same lines of the same file — so it stops and asks a human to decide.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.322416',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$When Git tries to combine two sets of changes and can't automatically decide which version is correct, because both sides changed the same lines of the same file — so it stops and asks a human to decide.$$, TRUE, 0),
    ($$Whenever two developers work on the same file at the same time, regardless of which lines.$$, FALSE, 1),
    ($$A permanent, unrecoverable error that requires deleting one of the branches.$$, FALSE, 2),
    ($$Something that only happens during a merge, never during a rebase.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 236, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$According to the lesson, what specifically causes a merge conflict?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what specifically causes a merge conflict?$$, NULL, NULL,
           $$A conflict specifically requires both branches to have modified the same lines — changes to different files, or different non-overlapping lines of the same file, usually merge automatically without any conflict.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.35029',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Both branches touched the same file, even if the changes are on different lines.$$, FALSE, 0),
    ($$Both branches modified the same lines of the same file — different files or different, non-overlapping lines usually merge cleanly on their own.$$, TRUE, 1),
    ($$One branch has more commits than the branch it's merging into.$$, FALSE, 2),
    ($$A commit message is missing.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 237, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$In a conflicted file, what does the `<<<<<<< HEAD` marker indicate?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In a conflicted file, what does the `<<<<<<< HEAD` marker indicate?$$, NULL, NULL,
           $$`<<<<<<< HEAD` marks the start of your current branch's version of the conflicting code; `=======` separates it from the incoming branch's version, which ends at the `>>>>>>> branch-name` marker.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.359189',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$The start of the incoming branch's version.$$, FALSE, 0),
    ($$A syntax error Git inserted by mistake.$$, FALSE, 1),
    ($$The start of your current branch's version of the conflicting code.$$, TRUE, 2),
    ($$The point where the file will be permanently split into two files.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 238, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$During conflict resolution, what does running `git add` on the resolved file actually mean?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$During conflict resolution, what does running `git add` on the resolved file actually mean?$$, NULL, NULL,
           $$During conflict resolution, `git add` means something slightly different than usual — it's not staging a new change, it's telling Git that this file's conflict has been resolved.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.366799',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$It creates a backup copy of the conflicted version before you edit it.$$, FALSE, 0),
    ($$It automatically removes the conflict markers for you.$$, FALSE, 1),
    ($$It reverts the file to the incoming branch's version.$$, FALSE, 2),
    ($$It tells Git this file's conflict is resolved — not that you're staging a brand-new change.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 239, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$Why can a single rebase pause for a conflict more than once?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why can a single rebase pause for a conflict more than once?$$, NULL, NULL,
           $$Because rebase replays commits one at a time, a conflict can occur on any individual commit in the sequence — Git pauses exactly at each commit where one occurs, which can mean stopping more than once in the same rebase.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.374362',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Because rebase replays commits one at a time, and a conflict can occur on any individual commit in the sequence, so Git pauses at each one that conflicts.$$, TRUE, 0),
    ($$Because Git deliberately re-triggers the same conflict a second time as a safety check.$$, FALSE, 1),
    ($$Because every rebase always produces exactly two conflicts.$$, FALSE, 2),
    ($$Because conflicts during a rebase are unrelated to the commits being replayed.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 240, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$According to the lesson, what does actually resolving a merge conflict involve?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what does actually resolving a merge conflict involve?$$, NULL, NULL,
           $$There's no special 'conflict resolution mode' — resolving a conflict just means editing a normal text file, removing the markers and leaving the correct code behind.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.381504',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Running a dedicated `git resolve` command that automatically picks the correct version.$$, FALSE, 0),
    ($$There's no special 'conflict resolution mode' — you're just editing a normal text file, removing the markers and choosing the correct code.$$, TRUE, 1),
    ($$Switching to a special conflict-only branch to make the edit.$$, FALSE, 2),
    ($$Opening a GitHub-only web interface, since conflicts can't be resolved locally.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 241, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$Per the lesson's practical workflow and Best Practices, what should you do after editing the conflicted files but before completing the merge or rebase?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Per the lesson's practical workflow and Best Practices, what should you do after editing the conflicted files but before completing the merge or rebase?$$, NULL, NULL,
           $$The lesson's workflow and Best Practices both recommend running the project's tests after resolving, before completing the merge or rebase — a conflict resolution that compiles isn't necessarily one that's logically correct.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.39081',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Immediately force-push the branch to save your resolution.$$, FALSE, 0),
    ($$Delete the other branch so the conflict can't happen again.$$, FALSE, 1),
    ($$Run the project's tests if you can — a resolved conflict that compiles isn't necessarily a resolved conflict that's correct.$$, TRUE, 2),
    ($$Skip re-reading the file, since the markers being gone means it's already correct.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 242, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$Which of the following are true about `git merge --abort` and `git rebase --abort`, according to the lesson? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about `git merge --abort` and `git rebase --abort`, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$Both `git merge --abort` and `git rebase --abort` are completely safe — there's no partial or broken state to worry about, so aborting and re-approaching a confusing conflict is always a reasonable choice.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.398768',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Both commands are completely safe — there's no partial or broken state to worry about.$$, TRUE, 0),
    ($$`git merge --abort` also cancels any commits that were already pushed to the remote.$$, FALSE, 1),
    ($$Aborting and re-approaching a confusing conflict, perhaps after talking to whoever wrote the conflicting change, is always a reasonable choice.$$, TRUE, 2),
    ($$Once you start resolving a conflict, aborting is no longer possible.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 243, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$Which of the following are true about completing a conflict resolution, according to the lesson? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about completing a conflict resolution, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$Completing a merge conflict resolution uses `git commit`, which creates the merge commit itself. Completing one step of a rebase conflict uses `git rebase --continue` instead, which may pause again at the next conflicting commit if there is one.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.406151',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Completing a rebase conflict resolution always uses `git commit`, exactly like a merge.$$, FALSE, 0),
    ($$Completing a merge conflict resolution uses `git commit`, which creates the merge commit itself.$$, TRUE, 1),
    ($$Once one conflicted file in a rebase is resolved, the entire rebase is automatically finished.$$, FALSE, 2),
    ($$`git rebase --continue` may pause again at the next conflicting commit if there is one.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 244, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes warns that leaving conflict markers in committed code is a real risk, and that the correct resolution is sometimes a combination of both sides rather than picking just one.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.414102',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Sometimes the correct resolution is neither version alone, but a combination of both.$$, TRUE, 0),
    ($$The safest approach is to always pick whichever side looks more familiar, without checking why the other side made its change.$$, FALSE, 1),
    ($$Panicking mid-conflict is unavoidable, since there's no way to safely back out once a conflict starts.$$, FALSE, 2),
    ($$Accidentally leaving conflict markers in committed code is a real mistake that can ship a syntax error, or worse, silently wrong logic, to `main`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

