-- Portable promotion-style migration linking the TR Merge Conflicts
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, and
-- rebase-and-squash/V479-V480 (see those files for the full rationale).
--
-- Development Question IDs: 245, 246, 247, 248, 249, 250, 251, 252, 253, 254
-- Topic: merge-conflicts (language: tr)
-- Turkish counterparts of the English questions in V481 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 245, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Derse göre bir merge conflict, temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir merge conflict, temelde nedir?$$, NULL, NULL,
           $$Bir merge conflict, Git iki değişiklik kümesini birleştirmeye çalışırken hangi sürümün doğru olduğuna otomatik olarak karar veremediğinde olur, çünkü her iki taraf da aynı dosyanın aynı satırlarını farklı şekillerde değiştirmiştir — bu yüzden durur ve bir insandan karar vermesini ister.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.421596',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Git, iki değişiklik kümesini birleştirmeye çalışırken hangi sürümün doğru olduğuna otomatik olarak karar veremediğinde ortaya çıkar, çünkü her iki taraf da aynı dosyanın aynı satırlarını farklı şekillerde değiştirmiştir — bu yüzden durur ve senden, bir insandan, karar vermeni ister.$$, TRUE, 0),
    ($$İki geliştirici aynı anda aynı dosya üzerinde çalıştığında, hangi satırlar olursa olsun ortaya çıkar.$$, FALSE, 1),
    ($$Bir branch'i silmeni gerektiren, kalıcı ve geri döndürülemez bir hatadır.$$, FALSE, 2),
    ($$Yalnızca bir merge sırasında olur, asla bir rebase sırasında olmaz.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 246, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Derse göre, bir merge conflict'e özellikle neden olan nedir?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre, bir merge conflict'e özellikle neden olan nedir?$$, NULL, NULL,
           $$Bir conflict, özellikle her iki branch'in de aynı satırları değiştirmiş olmasını gerektirir — farklı dosyalara yapılan değişiklikler, ya da aynı dosyanın farklı, örtüşmeyen satırları, genellikle hiçbir conflict olmadan otomatik olarak merge edilir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.428949',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Her iki branch de, dosyanın farklı satırları olsa bile, aynı dosyaya dokunmuştur.$$, FALSE, 0),
    ($$Her iki branch de aynı dosyanın aynı satırlarını değiştirmiştir — farklı dosyalar ya da aynı dosyanın farklı, örtüşmeyen satırları genellikle kendi başına sorunsuz merge edilir.$$, TRUE, 1),
    ($$Bir branch'in, merge edildiği branch'ten daha fazla commit'i vardır.$$, FALSE, 2),
    ($$Bir commit mesajı eksiktir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 247, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Çakışan bir dosyada, `<<<<<<< HEAD` işaretçisi neyi belirtir?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Çakışan bir dosyada, `<<<<<<< HEAD` işaretçisi neyi belirtir?$$, NULL, NULL,
           $$`<<<<<<< HEAD`, çakışan kodun mevcut branch'inin sürümünün başlangıcını işaretler; `=======` bunu gelen branch'in sürümünden ayırır, ki bu da `>>>>>>> branch-adı` işaretçisinde sona erer.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.43679',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Gelen branch'in sürümünün başlangıcını.$$, FALSE, 0),
    ($$Git'in yanlışlıkla eklediği bir sözdizimi hatasını.$$, FALSE, 1),
    ($$Çakışan kodun mevcut branch'inin sürümünün başlangıcını.$$, TRUE, 2),
    ($$Dosyanın kalıcı olarak ikiye bölüneceği noktayı.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 248, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Conflict çözümü sırasında, çözülen dosya üzerinde `git add` çalıştırmak aslında ne anlama gelir?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Conflict çözümü sırasında, çözülen dosya üzerinde `git add` çalıştırmak aslında ne anlama gelir?$$, NULL, NULL,
           $$Conflict çözümü sırasında `git add`, her zamankinden biraz farklı bir anlama gelir — yepyeni bir değişikliği stage'lemek değil, Git'e bu dosyanın conflict'inin çözüldüğünü söylemektir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.443365',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Düzenlemeden önce çakışan sürümün bir yedek kopyasını oluşturur.$$, FALSE, 0),
    ($$Conflict işaretlerini senin için otomatik olarak kaldırır.$$, FALSE, 1),
    ($$Dosyayı gelen branch'in sürümüne geri döndürür.$$, FALSE, 2),
    ($$Git'e bu dosyanın conflict'inin çözüldüğünü söyler — yepyeni bir değişikliği stage'lemek değildir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 249, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Tek bir rebase, bir conflict için neden birden fazla kez duraklayabilir?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Tek bir rebase, bir conflict için neden birden fazla kez duraklayabilir?$$, NULL, NULL,
           $$Rebase, commit'leri tek tek yeniden oynattığı için, bir conflict sıradaki herhangi bir bireysel commit'te olabilir — Git, bir conflict oluşan her commit'te tam olarak duraklar, ki bu aynı rebase'te birden fazla kez durmak anlamına gelebilir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.450373',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Rebase, commit'leri tek tek yeniden oynattığı için, bir conflict sıradaki herhangi bir bireysel commit'te olabilir, bu yüzden Git bir conflict oluşan her commit'te duraklar.$$, TRUE, 0),
    ($$Çünkü Git, bir güvenlik kontrolü olarak aynı conflict'i kasıtlı olarak ikinci kez tetikler.$$, FALSE, 1),
    ($$Çünkü her rebase her zaman tam olarak iki conflict üretir.$$, FALSE, 2),
    ($$Çünkü bir rebase sırasındaki conflict'ler, yeniden oynatılan commit'lerle ilgisizdir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 250, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Derse göre, bir merge conflict'i gerçekten çözmek neyi içerir?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre, bir merge conflict'i gerçekten çözmek neyi içerir?$$, NULL, NULL,
           $$Özel bir 'conflict çözme modu' yoktur — bir conflict'i çözmek yalnızca normal bir metin dosyasını düzenlemek, işaretçileri kaldırıp arkada doğru kodu bırakmak anlamına gelir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.457046',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Doğru sürümü otomatik olarak seçen özel bir `git resolve` komutu çalıştırmayı.$$, FALSE, 0),
    ($$Özel bir 'conflict çözme modu' yoktur — yalnızca normal bir metin dosyasını düzenliyorsun, işaretçileri kaldırıp doğru kodu bırakıyorsun.$$, TRUE, 1),
    ($$Düzenlemeyi yapmak için özel, yalnızca-conflict bir branch'e geçmeyi.$$, FALSE, 2),
    ($$Yalnızca GitHub'a özgü bir web arayüzü açmayı, çünkü conflict'ler yerel olarak çözülemez.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 251, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Dersin pratik iş akışına ve En İyi Pratikler'ine göre, çakışan dosyaları düzenledikten sonra ama merge'i ya da rebase'i tamamlamadan önce ne yapmalısın?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin pratik iş akışına ve En İyi Pratikler'ine göre, çakışan dosyaları düzenledikten sonra ama merge'i ya da rebase'i tamamlamadan önce ne yapmalısın?$$, NULL, NULL,
           $$Dersin iş akışı ve En İyi Pratikler'i, çözdükten sonra, merge'i ya da rebase'i tamamlamadan önce projenin testlerini çalıştırmayı öneriyor — derlenen bir conflict çözümü, mutlaka mantıksal olarak doğru olan bir çözüm değildir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.463397',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Branch'ini çözümünü kaydetmek için hemen force-push yapmalısın.$$, FALSE, 0),
    ($$Conflict'in bir daha olmaması için diğer branch'i silmelisin.$$, FALSE, 1),
    ($$Mümkünse projenin testlerini çalıştırmalısın — derlenen bir conflict çözümü, mutlaka doğru olan bir çözüm değildir.$$, TRUE, 2),
    ($$İşaretçilerin gitmiş olması zaten doğru olduğu anlamına geldiği için dosyayı yeniden okumayı atlamalısın.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 252, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Derse göre `git merge --abort` ve `git rebase --abort` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre `git merge --abort` ve `git rebase --abort` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Hem `git merge --abort` hem `git rebase --abort` tamamen güvenlidir — endişelenecek kısmi ya da bozuk bir durum yoktur, bu yüzden kafa karıştırıcı bir conflict'i iptal edip yeniden yaklaşmak her zaman makul bir seçimdir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.469652',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Her iki komut da tamamen güvenlidir — endişelenecek kısmi ya da bozuk bir durum yoktur.$$, TRUE, 0),
    ($$`git merge --abort`, remote'a zaten push edilmiş commit'leri de iptal eder.$$, FALSE, 1),
    ($$Kafa karıştırıcı bir conflict'i iptal edip yeniden yaklaşmak, belki de çakışan değişikliği yazan kişiyle konuştuktan sonra, her zaman makul bir seçimdir.$$, TRUE, 2),
    ($$Bir conflict'i çözmeye başladıktan sonra, artık iptal etmek mümkün değildir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 253, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Derse göre bir conflict çözümünü tamamlamak hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir conflict çözümünü tamamlamak hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Bir merge conflict çözümünü tamamlamak, merge commit'inin kendisini oluşturan `git commit`'i kullanır. Bir rebase conflict'inin bir adımını tamamlamak ise bunun yerine `git rebase --continue` kullanır, ki bu da varsa sıradaki çakışan commit'te tekrar duraklayabilir.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.476187',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Bir rebase conflict çözümünü tamamlamak, tıpkı bir merge gibi her zaman `git commit` kullanır.$$, FALSE, 0),
    ($$Bir merge conflict çözümünü tamamlamak, merge commit'inin kendisini oluşturan `git commit`'i kullanır.$$, TRUE, 1),
    ($$Bir rebase'te çakışan bir dosya çözüldüğünde, tüm rebase otomatik olarak biter.$$, FALSE, 2),
    ($$`git rebase --continue`, eğer varsa sıradaki çakışan commit'te tekrar duraklayabilir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 254, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'merge-conflicts')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar bölümüne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar bölümüne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, commit edilmiş kodda conflict işaretçileri bırakmanın gerçek bir risk olduğunu ve doğru çözümün bazen yalnızca bir tarafı seçmek değil, ikisinin bir kombinasyonu olduğunu uyarıyor.$$, 'n8n-ai-judge', '2026-08-29 21:25:57.483783',
           now(), now()
    FROM topic
    WHERE slug = 'merge-conflicts'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Bazen doğru çözüm, tek başına ne bir sürüm ne de diğeridir, ikisinin bir kombinasyonudur.$$, TRUE, 0),
    ($$En güvenli yaklaşım, diğer tarafın değişikliğini neden yaptığını kontrol etmeden, her zaman daha tanıdık görünen tarafı seçmektir.$$, FALSE, 1),
    ($$Conflict ortasında paniklemek kaçınılmazdır, çünkü bir conflict başladıktan sonra güvenle geri çekilmenin bir yolu yoktur.$$, FALSE, 2),
    ($$Commit edilmiş kodda yanlışlıkla conflict işaretçileri bırakmak gerçek bir hatadır, bu `main`'e bir sözdizimi hatası, ya da daha kötüsü, sessizce yanlış bir mantık gönderebilir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'merge-conflicts'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

