-- Portable promotion-style migration linking the EN Working With
-- Commits quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467 and V468 (see those files for the full rationale).
--
-- Development Question IDs: 115, 116, 117, 118, 119, 120, 121, 122, 123, 124
-- Topic: working-with-commits (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 115, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$What question should a good commit message primarily answer?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What question should a good commit message primarily answer?$$, NULL, NULL,
           $$A good commit message answers why the change was made -- the what is already visible in git diff, so the message shouldn't repeat it.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.606537',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Why the change was made.$$, TRUE, 0),
    ($$How long the change took to write.$$, FALSE, 1),
    ($$What lines of code changed.$$, FALSE, 2),
    ($$Who approved the change.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 116, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$Which of these commit summary lines best follows the convention the lesson describes?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of these commit summary lines best follows the convention the lesson describes?$$, NULL, NULL,
           $$The convention is a short summary in the imperative mood that explains why. "Fix NullPointerException when user has no roles assigned" matches this -- the other options are either vague, past tense, or don't explain why.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.646299',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$"Update UserService.java"$$, FALSE, 0),
    ($$"Fixed bug in UserService"$$, FALSE, 1),
    ($$"This commit contains various changes to the codebase"$$, FALSE, 2),
    ($$"Fix NullPointerException when user has no roles assigned"$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 117, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$Which of the following statements about Conventional Commits are true? (Select all that apply)$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following statements about Conventional Commits are true? (Select all that apply)$$, NULL, NULL,
           $$Conventional Commits prefixes the summary with a type such as feat: or fix:, and it is not required by Git itself -- it's a team/tooling convention some projects use to auto-generate changelogs.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.662047',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$It changes how git commit stages files.$$, FALSE, 0),
    ($$It prefixes the commit summary with a type such as feat: or fix:.$$, TRUE, 1),
    ($$It is required by Git itself for every commit.$$, FALSE, 2),
    ($$It is not required by Git itself -- it's a team/tooling convention.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 118, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$What does git log --oneline do?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does git log --oneline do?$$, NULL, NULL,
           $$git log --oneline shows a compact, one-line-per-commit summary instead of the default multi-line output -- it gives a fast overview, not a count limit or a destructive operation.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.677120',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Deletes all commits except the most recent one.$$, FALSE, 0),
    ($$Shows a compact, one-line-per-commit summary instead of the default multi-line output.$$, TRUE, 1),
    ($$Shows only the single most recent commit.$$, FALSE, 2),
    ($$Combines all commits into a single commit.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 119, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$Which of the following are valid ways to filter git log output, according to the lesson? (Select all that apply)$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are valid ways to filter git log output, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$git log --author="Ada" filters by author, and git log -- UserService.java filters to commits touching that file -- these are read-only filters, not destructive operations, unlike what the other two options claim.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.692015',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$git log --author="Ada" -- shows only commits by a specific author.$$, TRUE, 0),
    ($$git log --oneline -5 -- permanently deletes all but the 5 most recent commits.$$, FALSE, 1),
    ($$git log -- UserService.java -- shows only commits that touched that file.$$, TRUE, 2),
    ($$git log --since="2 days ago" -- permanently removes commits older than 2 days.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 120, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$What does git show display that git log does not?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does git show display that git log does not?$$, NULL, NULL,
           $$While git log lists commits, git show shows the full content of one specific commit -- its message and its complete diff.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.705933',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$A list of all commits in the repository.$$, FALSE, 0),
    ($$The current contents of the working tree.$$, FALSE, 1),
    ($$Only the author and date of a commit, without the message or diff.$$, FALSE, 2),
    ($$The full content of one specific commit, including its complete diff.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 121, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$Which of the following statements about git commit -am are true? (Select all that apply)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following statements about git commit -am are true? (Select all that apply)$$, NULL, NULL,
           $$-am stages already-tracked, modified files and commits them in one step, but it will not stage brand-new, untracked files -- those still need an explicit git add.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.720318',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$It stages every file in the repository, including new untracked files.$$, FALSE, 0),
    ($$It stages already-tracked, modified files and commits them in one step.$$, TRUE, 1),
    ($$It only works if you have not modified any files.$$, FALSE, 2),
    ($$It will not stage brand-new, untracked files -- those still need an explicit git add.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 122, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$What actually happens when you run git commit --amend?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What actually happens when you run git commit --amend?$$, NULL, NULL,
           $$Git commits are immutable -- --amend does not modify the existing commit in place. Instead Git creates a brand-new commit that replaces the old one, and moves the branch to point at the new one.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.733588',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Git creates a brand-new commit that replaces the old one; the old commit is no longer part of the branch's history.$$, TRUE, 0),
    ($$Git deletes the previous commit permanently, with no way to recover it.$$, FALSE, 1),
    ($$Git merges the previous two commits into one new commit.$$, FALSE, 2),
    ($$Git edits the existing commit object in place, changing its content directly.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 123, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$Why does the lesson say you should only amend commits that are still local and haven't been pulled by anyone else?$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson say you should only amend commits that are still local and haven't been pulled by anyone else?$$, NULL, NULL,
           $$Amending replaces the commit with a new one. If someone else already pulled the old version, your branch now has a different commit at that position than their copy -- a divergence in shared history.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.746837',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Because amended commits are automatically rejected by GitHub.$$, FALSE, 0),
    ($$Because amending replaces the commit, so if someone else already has the old version, your histories diverge.$$, TRUE, 1),
    ($$Because Git physically cannot amend a commit once it has been pushed.$$, FALSE, 2),
    ($$Because amending is a slow operation that can only run once per day.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 124, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'en'
      AND question = $$What does HEAD~2 refer to?$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does HEAD~2 refer to?$$, NULL, NULL,
           $$HEAD~1, HEAD~2, etc. refer to earlier commits relative to HEAD -- HEAD~2 means two commits before the current one.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.759993',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$The commit two positions after HEAD in the future.$$, FALSE, 0),
    ($$The second branch in the repository.$$, FALSE, 1),
    ($$Two commits before the current one.$$, TRUE, 2),
    ($$A commit exactly 2 minutes old.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;
