-- Portable promotion-style migration linking the TR Working With
-- Commits quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467 and V468 (see those files for the full rationale).
--
-- Development Question IDs: 125, 126, 127, 128, 129, 130, 131, 132, 133, 134
-- Topic: working-with-commits (language: tr)
-- Turkish counterparts of the English questions in V469 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 125, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$İyi bir commit mesajı temel olarak hangi soruyu yanıtlamalıdır?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$İyi bir commit mesajı temel olarak hangi soruyu yanıtlamalıdır?$$, NULL, NULL,
           $$İyi bir commit mesajı, değişikliğin neden yapıldığını yanıtlar -- ne değiştiği zaten git diff'te görünür, bu yüzden mesajın bunu tekrarlamasına gerek yoktur.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.772679',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Değişikliğin neden yapıldığını.$$, TRUE, 0),
    ($$Değişikliğin ne kadar sürede yazıldığını.$$, FALSE, 1),
    ($$Değişikliği kimin onayladığını.$$, FALSE, 2),
    ($$Kod satırlarında tam olarak ne değiştiğini.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 126, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$Derste anlatılan konvansiyona göre hangi commit özet satırı en uygunudur?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derste anlatılan konvansiyona göre hangi commit özet satırı en uygunudur?$$, NULL, NULL,
           $$Konvansiyon, neden'i açıklayan, emir kipiyle yazılmış kısa bir özet satırıdır. "Fix NullPointerException when user has no roles assigned" buna uyar -- diğer seçenekler ya belirsiz, ya geçmiş zamanlı, ya da nedeni açıklamıyor.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.785387',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$"Update UserService.java"$$, FALSE, 0),
    ($$"Fix NullPointerException when user has no roles assigned"$$, TRUE, 1),
    ($$"Fixed bug in UserService"$$, FALSE, 2),
    ($$"This commit contains various changes to the codebase"$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 127, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$Conventional Commits hakkında aşağıdaki ifadelerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Conventional Commits hakkında aşağıdaki ifadelerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Conventional Commits özeti feat: ya da fix: gibi bir tip önekiyle başlatır, ve Git'in kendisi tarafından zorunlu tutulmaz -- bazı projelerin changelog otomatik üretmek için kullandığı bir takım/araç konvansiyonudur.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.798374',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$git commit'in dosyaları nasıl stage'lediğini değiştirir.$$, FALSE, 0),
    ($$Özeti feat: ya da fix: gibi bir tip önekiyle başlatır.$$, TRUE, 1),
    ($$Git'in kendisi tarafından her commit için zorunlu tutulur.$$, FALSE, 2),
    ($$Git'in kendisi tarafından zorunlu tutulmaz -- bir takım/araç konvansiyonudur.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 128, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$git log --oneline ne yapar?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$git log --oneline ne yapar?$$, NULL, NULL,
           $$git log --oneline, varsayılan çok satırlı çıktı yerine commit başına tek satırlık kompakt bir özet gösterir -- hızlı bir genel bakış sağlar, bir sayı sınırı ya da yıkıcı bir işlem değildir.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.811934',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Son commit hariç tüm commit'leri siler.$$, FALSE, 0),
    ($$Yalnızca en son tek commit'i gösterir.$$, FALSE, 1),
    ($$Varsayılan çok satırlı çıktı yerine, commit başına tek satırlık kompakt bir özet gösterir.$$, TRUE, 2),
    ($$Tüm commit'leri tek bir commit'te birleştirir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 129, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$Aşağıdakilerden hangileri derste anlatılan geçerli git log filtreleme yöntemleridir? (Uygun olanların hepsini seçin)$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdakilerden hangileri derste anlatılan geçerli git log filtreleme yöntemleridir? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$git log --author="Ada" yazara göre filtreler, git log -- UserService.java ise yalnızca o dosyayı değiştiren commit'leri filtreler -- bunlar salt-okunur filtrelerdir, diğer iki seçeneğin iddia ettiği gibi yıkıcı işlemler değildir.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.824434',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$git log --author="Ada" -- yalnızca belirli bir yazarın commit'lerini gösterir.$$, TRUE, 0),
    ($$git log --oneline -5 -- en son 5 commit hariç tümünü kalıcı olarak siler.$$, FALSE, 1),
    ($$git log -- UserService.java -- yalnızca bu dosyayı değiştiren commit'leri gösterir.$$, TRUE, 2),
    ($$git log --since="2 days ago" -- 2 günden eski commit'leri kalıcı olarak kaldırır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 130, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$git show, git log'un göstermediği neyi gösterir?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$git show, git log'un göstermediği neyi gösterir?$$, NULL, NULL,
           $$git log commit'leri listelerken, git show belirli BİR commit'in tam içeriğini gösterir -- mesajını ve tam diff'ini.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.837558',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Repository'deki tüm commit'lerin listesini.$$, FALSE, 0),
    ($$Belirli BİR commit'in tam içeriğini, tam diff'i dahil.$$, TRUE, 1),
    ($$Working tree'nin şu anki içeriğini.$$, FALSE, 2),
    ($$Bir commit'in yalnızca yazarını ve tarihini, mesajını ya da diff'ini değil.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 131, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$git commit -am hakkında aşağıdaki ifadelerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$git commit -am hakkında aşağıdaki ifadelerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$-am, zaten takip edilen, değiştirilmiş dosyaları tek adımda stage'ler ve commit'ler, ama yepyeni, takip edilmeyen dosyaları stage'lemez -- onlar için hâlâ açık bir git add gerekir.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.849904',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Yepyeni, takip edilmeyen dosyalar dahil repository'deki her dosyayı stage'ler.$$, FALSE, 0),
    ($$Zaten takip edilen, değiştirilmiş dosyaları tek adımda stage'ler ve commit'ler.$$, TRUE, 1),
    ($$Yalnızca hiçbir dosyayı değiştirmediysen çalışır.$$, FALSE, 2),
    ($$Yepyeni, takip edilmeyen dosyaları stage'lemez -- onlar için hâlâ açık bir git add gerekir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 132, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$git commit --amend çalıştırdığında aslında ne olur?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$git commit --amend çalıştırdığında aslında ne olur?$$, NULL, NULL,
           $$Git commit'leri değişmezdir (immutable) -- --amend var olan commit'i yerinde değiştirmez. Bunun yerine Git, eskisinin yerine geçecek yepyeni bir commit oluşturur ve branch'i yeni olana işaret edecek şekilde taşır.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.862502',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Git, eskisinin yerine geçecek yepyeni bir commit oluşturur; eski commit artık branch'in geçmişinin bir parçası değildir.$$, TRUE, 0),
    ($$Git, önceki commit'i kalıcı olarak siler, geri getirme imkanı yoktur.$$, FALSE, 1),
    ($$Git, önceki iki commit'i tek bir yeni commit'te birleştirir.$$, FALSE, 2),
    ($$Git, var olan commit nesnesini yerinde değiştirir, içeriğini doğrudan değiştirir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 133, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$Ders neden yalnızca hâlâ yerel olan, henüz kimsenin pull etmediği commit'leri amend etmen gerektiğini söylüyor?$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders neden yalnızca hâlâ yerel olan, henüz kimsenin pull etmediği commit'leri amend etmen gerektiğini söylüyor?$$, NULL, NULL,
           $$Amend etmek commit'i yeni biriyle değiştirir. Başka biri zaten eski sürümü pull ettiyse, branch'in artık o pozisyonda onların sahip olduğu kopyadan farklı bir commit'e sahip olur -- paylaşılan geçmişte bir sapma.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.876213',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Amend edilen commit'ler GitHub tarafından otomatik olarak reddedilir.$$, FALSE, 0),
    ($$Amend etmek yavaş bir işlemdir ve günde yalnızca bir kez çalıştırılabilir.$$, FALSE, 1),
    ($$Amend etmek commit'in yerine geçer, bu yüzden başka biri zaten eski sürüme sahipse geçmişleriniz birbirinden sapar.$$, TRUE, 2),
    ($$Git, bir commit push edildikten sonra onu fiziksel olarak amend edemez.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 134, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'working-with-commits')
      AND language = 'tr'
      AND question = $$HEAD~2 neyi ifade eder?$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$HEAD~2 neyi ifade eder?$$, NULL, NULL,
           $$HEAD~1, HEAD~2 vb., HEAD'e göreceli önceki commit'lere referans verir -- HEAD~2, mevcut commit'ten iki önceki commit anlamına gelir.$$, 'n8n-ai-judge', '2026-08-28 19:57:49.890096',
           now(), now()
    FROM topic
    WHERE slug = 'working-with-commits'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Repository'deki ikinci branch'i.$$, FALSE, 0),
    ($$Tam olarak 2 dakika önce atılmış bir commit'i.$$, FALSE, 1),
    ($$HEAD'in gelecekte iki pozisyon sonrasındaki commit'i.$$, FALSE, 2),
    ($$Mevcut commit'ten iki önceki commit'i.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'working-with-commits'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;
