-- Portable promotion-style migration linking the EN Practical Git &
-- GitHub Workflow quiz questions to the topic's existing fixed quiz --
-- same pattern as git-fundamentals/V467-V468, working-with-commits/
-- V469-V470, undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, rebase-and-
-- squash/V479-V480, merge-conflicts/V481-V482, stash/V483-V484, and
-- advanced-git-and-best-practices/V485-V486 (see those files for the
-- full rationale). This is the final Git & GitHub course topic to
-- receive a "Test Your Knowledge" quiz.
--
-- Development Question IDs: 295, 296, 297, 298, 299, 300, 301, 302, 303, 304
-- Topic: practical-git-github-workflow (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript. One of the 10 is a
-- CODE_OUTPUT question grounded in the lesson's real embedded
-- FullWorkflowDemo.sh rebase-conflict output (a genuine command-output
-- interpretation scenario, not forced -- see chat transcript for the
-- review of why it was included).
--
-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 295, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$Before staging any changes, the scenario runs `git status` and `git diff`. According to the lesson, why?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Before staging any changes, the scenario runs `git status` and `git diff`. According to the lesson, why?$$, NULL, NULL,
           $$The scenario checks `git status` and `git diff` specifically to see exactly what changed before staging anything — a deliberate review step, not an automatic check.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.269593',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$To check exactly what changed before staging anything.$$, TRUE, 0),
    ($$To automatically fix any syntax errors in the edited file.$$, FALSE, 1),
    ($$To check whether the remote repository is reachable.$$, FALSE, 2),
    ($$To see whether the feature branch has already been merged.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 296, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$In the scenario, after realizing a database migration file was missing, the developer runs `git commit --amend --no-edit`. What does `--no-edit` do here?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In the scenario, after realizing a database migration file was missing, the developer runs `git commit --amend --no-edit`. What does `--no-edit` do here?$$, NULL, NULL,
           $$`--no-edit` keeps the previous commit message unchanged while still updating the commit to include the newly staged migration file — exactly what's needed when you're only adding a forgotten file, not changing the message.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.300947',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Opens the commit message in an editor so it can be rewritten.$$, FALSE, 0),
    ($$Keeps the previous commit message unchanged while still updating the commit to include the newly staged migration file.$$, TRUE, 1),
    ($$Skips running any pre-commit hooks.$$, FALSE, 2),
    ($$Prevents the amended commit from ever being pushed.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 297, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$After the reviewer requests a change (serializing `dueDate` as ISO-8601), why does the developer create a new commit and push it, rather than amending an already-pushed commit?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$After the reviewer requests a change (serializing `dueDate` as ISO-8601), why does the developer create a new commit and push it, rather than amending an already-pushed commit?$$, NULL, NULL,
           $$Once work has been pushed and is under review, new work becomes new commits, not rewrites of what's already visible to the reviewer — that's why the ISO-8601 fix is a new commit, not an amend.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.308861',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Because `git commit --amend` only works on commits that have never been staged.$$, FALSE, 0),
    ($$Because GitHub automatically rejects any amended commit on an open Pull Request.$$, FALSE, 1),
    ($$Because once work has been pushed and is under review, new work becomes new commits, not rewrites of what's already visible to the reviewer.$$, TRUE, 2),
    ($$Because amending would require opening a brand-new Pull Request.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 298, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$While the PR was under review, a teammate merged an unrelated change into `main`. Why does the scenario use `git rebase origin/main` to catch up, rather than `git merge origin/main`?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$While the PR was under review, a teammate merged an unrelated change into `main`. Why does the scenario use `git rebase origin/main` to catch up, rather than `git merge origin/main`?$$, NULL, NULL,
           $$Rebasing your own not-yet-merged feature branch onto an updated `main` is a completely normal, safe part of working with a team, precisely because nobody else has pulled that branch — and it keeps the eventual history clean, which is exactly why the scenario rebases instead of merging.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.31615',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Because `git merge` cannot be used with a remote-tracking branch like `origin/main`.$$, FALSE, 0),
    ($$Because rebasing is required before every push, regardless of the branch's state.$$, FALSE, 1),
    ($$Because merging would automatically close the open Pull Request.$$, FALSE, 2),
    ($$Because rebasing your own not-yet-merged feature branch onto an updated `main` is a completely normal, safe part of working with a team, precisely because nobody else has pulled that branch — and it keeps the eventual history clean.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 299, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$Why is force-pushing with `--force-with-lease` considered safe in this specific scenario?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why is force-pushing with `--force-with-lease` considered safe in this specific scenario?$$, NULL, NULL,
           $$Force-pushing with `--force-with-lease` is safe here specifically because nobody else has pulled this feature branch, so overwriting its remote history with the rebased commits doesn't discard anyone else's work.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.323826',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Because nobody else has pulled this feature branch, so overwriting its remote history with the rebased commits doesn't discard anyone else's work.$$, TRUE, 0),
    ($$Because `--force-with-lease` never actually overwrites anything on the remote.$$, FALSE, 1),
    ($$Because the branch is `main`, which is always safe to force-push.$$, FALSE, 2),
    ($$Because the Pull Request being open makes force-pushing automatically safe regardless of who else has pulled.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 300, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$What happens to the branch's five work-in-progress commits when the reviewer chooses 'Squash and merge'?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What happens to the branch's five work-in-progress commits when the reviewer chooses 'Squash and merge'?$$, NULL, NULL,
           $$Squash and merge combines the branch's five work-in-progress commits — including the amend and the review-feedback fix — into a single, clean commit on `main`.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.331121',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$They are each merged into `main` as five separate commits, unchanged.$$, FALSE, 0),
    ($$They become a single, clean commit on `main`.$$, TRUE, 1),
    ($$They are deleted entirely, and none of the changes reach `main`.$$, FALSE, 2),
    ($$They are converted into five separate Pull Requests for individual review.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 301, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$The lesson's full workflow example shows the output above when the rebase hits a conflict in `Task.java`. According to it, what is the correct resolution?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$The lesson's full workflow example shows the output above when the rebase hits a conflict in `Task.java`. According to it, what is the correct resolution?$$, $$Auto-merging Task.java
CONFLICT (content): Merge conflict in Task.java
error: could not apply 4f5a6b7... Add dueDate field to Task entity

public class Task {
    private String title;
<<<<<<< HEAD
    private Priority priority;
=======
    private LocalDate dueDate;
>>>>>>> 4f5a6b7 (Add dueDate field to Task entity)
    // ...
}$$, $$bash$$,
           $$The lesson's workflow example states the correct resolution directly: both fields are needed — someone else added `priority` on `main` while this branch added `dueDate` — so the correct resolution keeps both, rather than picking one side.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.338223',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Keep only `priority`, since it came from `main` and should always take precedence.$$, FALSE, 0),
    ($$Abort the rebase, since two people adding different fields to the same class can never be resolved.$$, FALSE, 1),
    ($$Keep both fields — `priority` from `main` and `dueDate` from this branch — since someone else added `priority` while this branch added `dueDate`.$$, TRUE, 2),
    ($$Keep only `dueDate`, and discard the `priority` field entirely.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 302, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$According to the lesson's Key Takeaways, which of the following are true about this workflow? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Key Takeaways, which of the following are true about this workflow? (Select all that apply)$$, NULL, NULL,
           $$The Key Takeaways state that this entire workflow uses commands you already know (only the order is new), and that rebasing your own unshared branch onto an updated `main`, then force-pushing with `--force-with-lease`, is a completely normal, safe practice.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.344933',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Every command used in this workflow is one you already know individually — nothing here is new syntax, only a realistic order of operations.$$, TRUE, 0),
    ($$Once a commit has been pushed and is under review, it should be amended directly rather than followed by a new commit.$$, FALSE, 1),
    ($$Rebasing your own not-yet-merged feature branch onto an updated `main`, then force-pushing with `--force-with-lease`, is a completely normal, safe part of working with a team.$$, TRUE, 2),
    ($$Squash and merge leaves all of the branch's original work-in-progress commits visible on `main` afterward.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 303, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$After the Pull Request is merged, the scenario runs `git switch main`, `git pull`, and `git branch -d add-task-due-date`. Which of the following are true about this cleanup? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$After the Pull Request is merged, the scenario runs `git switch main`, `git pull`, and `git branch -d add-task-due-date`. Which of the following are true about this cleanup? (Select all that apply)$$, NULL, NULL,
           $$`git branch -d` succeeds because the branch is already merged into `main`, and `git pull` is what actually brings the newly merged, squashed commit into your local `main` — deleting a local branch has no effect on GitHub, and this cleanup only happens after the PR is merged.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.351977',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Deleting the local branch also deletes it from GitHub automatically.$$, FALSE, 0),
    ($$`git pull` is necessary here to bring the newly merged, squashed commit into the local `main` branch.$$, TRUE, 1),
    ($$This cleanup must happen before the Pull Request can be merged on GitHub.$$, FALSE, 2),
    ($$`git branch -d` succeeds here because the branch's work is already merged into `main`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 304, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'en'
      AND question = $$Which of the following are true about pushing in this scenario? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about pushing in this scenario? (Select all that apply)$$, NULL, NULL,
           $$`-u` is only needed on a branch's first push, to establish tracking; after that, plain `git push` works for any push that doesn't rewrite existing commits, like the review-feedback fix — but a rebase, which does rewrite history, requires a force push instead.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.359894',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$`git push -u origin add-task-due-date` is used for the branch's first push, to establish the tracking relationship.$$, TRUE, 0),
    ($$Every subsequent push in the scenario, including the review-feedback fix, also needs the `-u` flag.$$, FALSE, 1),
    ($$A plain `git push` succeeds without issue after the rebase, since GitHub always accepts rebased branches.$$, FALSE, 2),
    ($$After responding to review feedback, a plain `git push` is enough, since that commit doesn't rewrite any existing history.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

