-- Portable promotion-style migration linking the TR Practical Git &
-- GitHub Workflow quiz questions to the topic's existing fixed quiz --
-- same pattern as git-fundamentals/V467-V468, working-with-commits/
-- V469-V470, undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, rebase-and-
-- squash/V479-V480, merge-conflicts/V481-V482, stash/V483-V484, and
-- advanced-git-and-best-practices/V485-V486 (see those files for the
-- full rationale). This is the final Git & GitHub course topic to
-- receive a "Test Your Knowledge" quiz.
--
-- Development Question IDs: 305, 306, 307, 308, 309, 310, 311, 312, 313, 314
-- Topic: practical-git-github-workflow (language: tr)
-- Turkish counterparts of the English questions in V487 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 305, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Herhangi bir değişikliği stage'lemeden önce, senaryo `git status` ve `git diff` çalıştırıyor. Derse göre neden?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Herhangi bir değişikliği stage'lemeden önce, senaryo `git status` ve `git diff` çalıştırıyor. Derse göre neden?$$, NULL, NULL,
           $$Senaryo, herhangi bir şeyi stage'lemeden önce tam olarak neyin değiştiğini görmek için özellikle `git status` ve `git diff` çalıştırıyor — bilinçli bir gözden geçirme adımı, otomatik bir kontrol değil.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.367121',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Herhangi bir şeyi stage'lemeden önce tam olarak neyin değiştiğini kontrol etmek için.$$, TRUE, 0),
    ($$Düzenlenen dosyadaki sözdizimi hatalarını otomatik olarak düzeltmek için.$$, FALSE, 1),
    ($$Remote repository'nin erişilebilir olup olmadığını kontrol etmek için.$$, FALSE, 2),
    ($$Feature branch'in zaten merge edilip edilmediğini görmek için.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 306, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Senaryoda, bir veritabanı migration dosyasının eksik olduğunu fark ettikten sonra, geliştirici `git commit --amend --no-edit` çalıştırıyor. `--no-edit` burada ne yapar?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Senaryoda, bir veritabanı migration dosyasının eksik olduğunu fark ettikten sonra, geliştirici `git commit --amend --no-edit` çalıştırıyor. `--no-edit` burada ne yapar?$$, NULL, NULL,
           $$`--no-edit`, önceki commit mesajını değiştirmeden korurken, commit'i yeni stage'lenen migration dosyasını içerecek şekilde günceller — yalnızca unutulan bir dosya eklerken, mesajı değiştirmeden, tam olarak ihtiyaç duyulan şey budur.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.374407',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Commit mesajını yeniden yazılabilmesi için bir editörde açar.$$, FALSE, 0),
    ($$Önceki commit mesajını değiştirmeden korurken, commit'i yeni stage'lenen migration dosyasını içerecek şekilde günceller.$$, TRUE, 1),
    ($$Herhangi bir pre-commit hook'unun çalışmasını atlar.$$, FALSE, 2),
    ($$Amend edilen commit'in asla push edilmesini engeller.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 307, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Reviewer bir değişiklik istedikten sonra (`dueDate`'i ISO-8601 olarak serileştirmek), geliştirici neden zaten push edilmiş bir commit'i amend etmek yerine yeni bir commit oluşturup push ediyor?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Reviewer bir değişiklik istedikten sonra (`dueDate`'i ISO-8601 olarak serileştirmek), geliştirici neden zaten push edilmiş bir commit'i amend etmek yerine yeni bir commit oluşturup push ediyor?$$, NULL, NULL,
           $$İş push edildikten ve incelemeye alındıktan sonra, yeni iş yeni commit'ler haline gelir, reviewer'ın zaten gördüğü şeylerin yeniden yazılması değil — ISO-8601 düzeltmesinin bir amend değil yeni bir commit olmasının nedeni tam olarak budur.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.381522',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Çünkü `git commit --amend`, yalnızca hiç stage edilmemiş commit'lerde çalışır.$$, FALSE, 0),
    ($$Çünkü GitHub, açık bir Pull Request'teki herhangi bir amend edilmiş commit'i otomatik olarak reddeder.$$, FALSE, 1),
    ($$Çünkü iş push edildikten ve incelemeye alındıktan sonra, yeni iş yeni commit'ler haline gelir, reviewer'ın zaten gördüğü şeylerin yeniden yazılması değil.$$, TRUE, 2),
    ($$Çünkü amend etmek yepyeni bir Pull Request açmayı gerektirir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 308, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$PR incelenirken, bir takım arkadaşı `main`'e ilgisiz bir değişiklik merge etti. Senaryo neden güncel kalmak için `git merge origin/main` yerine `git rebase origin/main` kullanıyor?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$PR incelenirken, bir takım arkadaşı `main`'e ilgisiz bir değişiklik merge etti. Senaryo neden güncel kalmak için `git merge origin/main` yerine `git rebase origin/main` kullanıyor?$$, NULL, NULL,
           $$Kendi henüz merge edilmemiş feature branch'ini güncellenmiş bir `main` üzerine rebase etmek, tam olarak kimsenin o branch'i pull etmemiş olması nedeniyle, bir takımla çalışmanın tamamen normal, güvenli bir parçasıdır — ve nihai geçmişi temiz tutar, ki senaryonun merge etmek yerine rebase etmesinin tam olarak nedeni budur.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.389068',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Çünkü `git merge`, `origin/main` gibi bir remote-tracking branch ile kullanılamaz.$$, FALSE, 0),
    ($$Çünkü branch'in durumundan bağımsız olarak her push'tan önce rebase etmek gereklidir.$$, FALSE, 1),
    ($$Çünkü merge etmek açık Pull Request'i otomatik olarak kapatır.$$, FALSE, 2),
    ($$Çünkü kendi henüz merge edilmemiş feature branch'ini güncellenmiş bir `main` üzerine rebase etmek, tam olarak kimsenin o branch'i pull etmemiş olması nedeniyle, bir takımla çalışmanın tamamen normal, güvenli bir parçasıdır — ve nihai geçmişi temiz tutar.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 309, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Bu spesifik senaryoda `--force-with-lease` ile force-push yapmak neden güvenli sayılıyor?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu spesifik senaryoda `--force-with-lease` ile force-push yapmak neden güvenli sayılıyor?$$, NULL, NULL,
           $$`--force-with-lease` ile force-push yapmak burada özellikle güvenlidir çünkü bu feature branch'i kimse pull etmemiştir, bu yüzden remote geçmişinin rebase edilmiş commit'lerin üzerine yazılması kimsenin işini kaybettirmez.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.395713',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Çünkü bu feature branch'i kimse pull etmemiştir, bu yüzden remote geçmişinin rebase edilmiş commit'lerin üzerine yazılması kimsenin işini kaybettirmez.$$, TRUE, 0),
    ($$Çünkü `--force-with-lease` remote'ta aslında hiçbir şeyin üzerine yazmaz.$$, FALSE, 1),
    ($$Çünkü branch `main`'dir, ki bu her zaman force-push için güvenlidir.$$, FALSE, 2),
    ($$Çünkü Pull Request'in açık olması, kim başka pull etmiş olursa olsun force-push'u otomatik olarak güvenli yapar.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 310, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Reviewer 'Squash and merge'i seçtiğinde, branch'in beş work-in-progress commit'ine ne olur?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Reviewer 'Squash and merge'i seçtiğinde, branch'in beş work-in-progress commit'ine ne olur?$$, NULL, NULL,
           $$Squash and merge, branch'in beş work-in-progress commit'ini — amend ve inceleme-geri-bildirimi düzeltmesi dahil — `main`'de tek, temiz bir commit'te birleştirir.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.402482',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Her biri, değişmeden, `main`'e beş ayrı commit olarak merge edilir.$$, FALSE, 0),
    ($$Tek, temiz bir commit'te `main`'de birleşirler.$$, TRUE, 1),
    ($$Tamamen silinirler, ve değişikliklerin hiçbiri `main`'e ulaşmaz.$$, FALSE, 2),
    ($$Bireysel inceleme için beş ayrı Pull Request'e dönüştürülürler.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 311, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Dersin tam workflow örneği, rebase `Task.java`'da bir conflict'e çarptığında yukarıdaki çıktıyı gösteriyor. Buna göre, doğru çözüm nedir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin tam workflow örneği, rebase `Task.java`'da bir conflict'e çarptığında yukarıdaki çıktıyı gösteriyor. Buna göre, doğru çözüm nedir?$$, $$Auto-merging Task.java
CONFLICT (content): Merge conflict in Task.java
error: could not apply 4f5a6b7... Add dueDate field to Task entity

public class Task {
    private String title;
<<<<<<< HEAD
    private Priority priority;
=======
    private LocalDate dueDate;
>>>>>>> 4f5a6b7 (Add dueDate field to Task entity)
    // ...
}$$, $$bash$$,
           $$Dersin workflow örneği doğru çözümü doğrudan belirtiyor: her iki alan da gereklidir — başka biri `main`'de `priority`'yi eklerken bu branch `dueDate`'i eklemiştir — bu yüzden doğru çözüm, bir tarafı seçmek yerine ikisini de korumaktır.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.409621',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Yalnızca `priority`'yi koru, çünkü `main`'den geldi ve her zaman önceliklidir.$$, FALSE, 0),
    ($$Rebase'i iptal et, çünkü iki kişinin aynı sınıfa farklı alanlar eklemesi asla çözülemez.$$, FALSE, 1),
    ($$Her iki alanı da koru — `main`'den `priority`'yi ve bu branch'ten `dueDate`'i — çünkü başka biri `priority`'yi eklerken bu branch `dueDate`'i eklemiştir.$$, TRUE, 2),
    ($$Yalnızca `dueDate`'i koru, ve `priority` alanını tamamen at.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 312, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Dersin Anahtar Çıkarımları'na göre, bu workflow hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Anahtar Çıkarımları'na göre, bu workflow hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Anahtar Çıkarımlar, bu workflow'un tamamının zaten bildiğin komutları kullandığını (yalnızca sıra yeni) ve kendi paylaşılmamış branch'ini güncellenmiş bir `main` üzerine rebase edip sonra `--force-with-lease` ile force-push yapmanın tamamen normal, güvenli bir pratik olduğunu belirtiyor.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.416956',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Bu workflow'da kullanılan her komut, zaten tek tek bildiğin bir komuttur — burada yeni bir sözdizimi yok, yalnızca gerçekçi bir işlem sırası.$$, TRUE, 0),
    ($$Bir commit push edildikten ve incelemeye alındıktan sonra, yeni bir commit yerine doğrudan amend edilmelidir.$$, FALSE, 1),
    ($$Kendi henüz merge edilmemiş feature branch'ini güncellenmiş bir `main` üzerine rebase etmek, sonra `--force-with-lease` ile force-push yapmak, bir takımla çalışmanın tamamen normal, güvenli bir parçasıdır.$$, TRUE, 2),
    ($$Squash and merge, branch'in tüm orijinal work-in-progress commit'lerini sonrasında `main`'de görünür bırakır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 313, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Pull Request merge edildikten sonra, senaryo `git switch main`, `git pull`, ve `git branch -d add-task-due-date` çalıştırıyor. Bu temizlik hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Pull Request merge edildikten sonra, senaryo `git switch main`, `git pull`, ve `git branch -d add-task-due-date` çalıştırıyor. Bu temizlik hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git branch -d`, branch zaten `main`'e merge edildiği için başarılı olur, ve `git pull` aslında yeni merge edilmiş, squash edilmiş commit'i yerel `main`'ine getiren şeydir — yerel bir branch'i silmenin GitHub üzerinde hiçbir etkisi yoktur, ve bu temizlik yalnızca PR merge edildikten sonra gerçekleşir.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.423746',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Yerel branch'i silmek, onu GitHub'dan da otomatik olarak siler.$$, FALSE, 0),
    ($$`git pull`, yeni merge edilmiş, squash edilmiş commit'i yerel `main` branch'ine getirmek için gereklidir.$$, TRUE, 1),
    ($$Bu temizlik, Pull Request GitHub'da merge edilebilmeden önce gerçekleşmelidir.$$, FALSE, 2),
    ($$`git branch -d` burada başarılı olur çünkü branch'in işi zaten `main`'e merge edilmiştir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 314, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'practical-git-github-workflow')
      AND language = 'tr'
      AND question = $$Bu senaryoda push etmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu senaryoda push etmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`-u`, yalnızca bir branch'in ilk push'unda, tracking'i kurmak için gereklidir; ondan sonra, var olan commit'leri yeniden yazmayan herhangi bir push için (inceleme-geri-bildirimi düzeltmesi gibi) düz `git push` yeterlidir — ama geçmişi gerçekten yeniden yazan bir rebase, bunun yerine bir force push gerektirir.$$, 'n8n-ai-judge', '2026-08-30 00:50:14.430511',
           now(), now()
    FROM topic
    WHERE slug = 'practical-git-github-workflow'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$`git push -u origin add-task-due-date`, tracking ilişkisini kurmak için branch'in ilk push'unda kullanılır.$$, TRUE, 0),
    ($$Senaryodaki sonraki her push, inceleme-geri-bildirimi düzeltmesi dahil, `-u` flag'ine de ihtiyaç duyar.$$, FALSE, 1),
    ($$Rebase'ten sonra düz bir `git push`, GitHub her zaman rebase edilmiş branch'leri kabul ettiği için sorunsuz başarılı olur.$$, FALSE, 2),
    ($$İnceleme geri bildirimine yanıt verdikten sonra, düz bir `git push` yeterlidir, çünkü o commit var olan hiçbir geçmişi yeniden yazmaz.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'practical-git-github-workflow'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

