-- Portable promotion-style migration linking the EN Stash quiz
-- questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478,
-- rebase-and-squash/V479-V480, and merge-conflicts/V481-V482 (see those
-- files for the full rationale).
--
-- Development Question IDs: 255, 256, 257, 258, 259, 260, 261, 262, 263, 264
-- Topic: stash (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript. One of the 10 is a
-- CODE_OUTPUT question grounded in the lesson's real `git stash list`
-- sample output (a genuine command-output interpretation scenario, not
-- forced -- see chat transcript for the review of why it was included).
--
-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 255, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$According to the lesson, what is `git stash`, fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is `git stash`, fundamentally?$$, NULL, NULL,
           $$`git stash` takes your uncommitted changes — both staged and unstaged — and saves them aside in temporary storage, restoring your working tree to match the last commit, so you can switch tasks without finishing what you were doing.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.887448',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$It takes your uncommitted changes (staged and unstaged) and saves them aside in temporary storage, restoring your working tree to match the last commit.$$, TRUE, 0),
    ($$It permanently deletes uncommitted changes so you can start fresh.$$, FALSE, 1),
    ($$It creates a new branch containing your uncommitted changes.$$, FALSE, 2),
    ($$It automatically commits your changes with a generic message.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 256, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$By default, does `git stash` include brand-new, untracked files?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$By default, does `git stash` include brand-new, untracked files?$$, NULL, NULL,
           $$By default, `git stash` only stashes changes to files Git is already tracking — brand-new, untracked files are left alone unless you pass `-u` or `--all`.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.915242',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Yes, `git stash` always includes every untracked file automatically.$$, FALSE, 0),
    ($$No — only changes to files Git is already tracking are stashed by default; untracked files are left alone unless you pass `-u` or `--all`.$$, TRUE, 1),
    ($$Yes, but only ignored files are included, never regular untracked files.$$, FALSE, 2),
    ($$No, and there is no way to include untracked files in a stash.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 257, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$What's the key difference between `git stash apply` and `git stash pop`?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What's the key difference between `git stash apply` and `git stash pop`?$$, NULL, NULL,
           $$`git stash apply` restores a stash's changes without removing it from the list, so you can reuse it later; `git stash pop` restores the changes and removes the stash in one step, which is the more common everyday choice.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.921719',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$`apply` only works on the oldest stash, while `pop` only works on the newest.$$, FALSE, 0),
    ($$`apply` restores untracked files, while `pop` restores only tracked files.$$, FALSE, 1),
    ($$`apply` restores a stash's changes without removing it from the list; `pop` restores the changes and removes it in one step.$$, TRUE, 2),
    ($$`apply` deletes the stash immediately, while `pop` keeps it forever.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 258, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$What happens to the corresponding stash entry after you run `git stash pop`?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What happens to the corresponding stash entry after you run `git stash pop`?$$, NULL, NULL,
           $$`git stash pop` applies the stash's changes and removes it from the list in the same step — it 'cleans up after itself,' unlike `apply`.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.929617',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$It stays in the list exactly as before, unchanged.$$, FALSE, 0),
    ($$It's automatically renamed to `stash@{0}` regardless of its original index.$$, FALSE, 1),
    ($$It's converted into a regular commit on the current branch.$$, FALSE, 2),
    ($$It's removed from the stash list, since `pop` applies the changes and cleans up after itself in one step.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 259, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$Why does the lesson warn about `git stash drop` and `git stash clear`?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson warn about `git stash drop` and `git stash clear`?$$, NULL, NULL,
           $$Both `git stash drop` and `git stash clear` permanently discard stashed changes with no confirmation prompt, so the lesson warns you to be certain before running either.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.935444',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Both commands permanently discard the stashed changes with no confirmation prompt, so you need to be certain before running either.$$, TRUE, 0),
    ($$Because they require special administrator permissions to run.$$, FALSE, 1),
    ($$Because they silently create a merge conflict.$$, FALSE, 2),
    ($$Because they only work if the working tree is completely clean.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 260, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$Why does the lesson recommend giving a stash a message with `git stash push -m`?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson recommend giving a stash a message with `git stash push -m`?$$, NULL, NULL,
           $$With several stashes stacked up, the default `WIP on <branch>: <hash> <message>` description can be hard to tell apart, so giving a stash a memorable message with `git stash push -m` makes it easier to identify later.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.942317',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Because unnamed stashes are automatically deleted after 24 hours.$$, FALSE, 0),
    ($$With several stashes stacked up, the default `WIP on <branch>: <hash> <message>` description can get hard to tell apart, so a memorable message makes them easier to identify later.$$, TRUE, 1),
    ($$Because `git stash` without a message fails with an error.$$, FALSE, 2),
    ($$Because the message is required for `git stash pop` to work at all.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 261, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$You run `git stash list` and see the following output. According to the lesson, which stash is the most recent one?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You run `git stash list` and see the following output. According to the lesson, which stash is the most recent one?$$, $$stash@{0}: WIP on add-password-reset: 8a1b2c3 Add PasswordController
stash@{1}: WIP on main: a1b2c3d Fix typo in README$$, $$bash$$,
           $$In `git stash list`, `stash@{0}` is always the most recent stash — here that's the one stashed from `add-password-reset`, while `stash@{1}` is the older one, from `main`.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.948544',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$`stash@{1}`, the one stashed from `main`.$$, FALSE, 0),
    ($$Neither — the most recent stash never appears in `git stash list`.$$, FALSE, 1),
    ($$`stash@{0}`, the one stashed from `add-password-reset`.$$, TRUE, 2),
    ($$Both are equally recent — the list doesn't indicate any order.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 262, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$Which of the following are true about `git stash -u` and `git stash --all`? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about `git stash -u` and `git stash --all`? (Select all that apply)$$, NULL, NULL,
           $$Plain `git stash` doesn't include untracked files; `-u` adds untracked files to the stash, while `--all` goes further and also includes ignored files.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.953913',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git stash -u` includes untracked files in the stash, in addition to tracked changes.$$, TRUE, 0),
    ($$`git stash --all` includes untracked files, but never ignored files.$$, FALSE, 1),
    ($$Plain `git stash`, with no flags, does not include untracked files.$$, TRUE, 2),
    ($$`git stash -u` and `git stash --all` behave identically in every case.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 263, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$Which of the following are true about stashes and their indexes, according to the lesson? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about stashes and their indexes, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$Stashes stack up so you can have more than one saved at once, and you can apply or pop a specific one by referencing its index, such as `stash@{1}`.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.960158',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$`stash@{0}` always refers to the oldest stash you've saved.$$, FALSE, 0),
    ($$Stashes stack up, so you can have more than one saved at the same time.$$, TRUE, 1),
    ($$Once you have more than one stash, `git stash pop` requires you to specify an index.$$, FALSE, 2),
    ($$You can apply or pop a specific stash by referencing its index, such as `stash@{1}`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 264, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes section recommends running `git stash list` regularly since it's easy to forget a stash exists, and its Best Practices note that stashed work sitting around for more than a day or two is usually a sign it should have been a real commit instead.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.965803',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$It's easy to forget a stash exists, which is why running `git stash list` regularly is a good habit.$$, TRUE, 0),
    ($$Using `apply` instead of `pop` out of habit has no real downside, since the two behave identically.$$, FALSE, 1),
    ($$Untracked files are stashed by default, so there's no need to think about `-u` or `--all`.$$, FALSE, 2),
    ($$If work sits stashed for more than a day or two, that's usually a sign it should have been a proper commit instead.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

