-- Portable promotion-style migration linking the TR Stash quiz
-- questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478,
-- rebase-and-squash/V479-V480, and merge-conflicts/V481-V482 (see those
-- files for the full rationale).
--
-- Development Question IDs: 265, 266, 267, 268, 269, 270, 271, 272, 273, 274
-- Topic: stash (language: tr)
-- Turkish counterparts of the English questions in V483 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 265, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Derse göre `git stash`, temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre `git stash`, temelde nedir?$$, NULL, NULL,
           $$`git stash`, commit edilmemiş değişikliklerini — hem stage edilmiş hem edilmemiş — alır ve geçici bir depolama alanına kaydeder, working tree'ni son commit'e uyacak şekilde geri yükler, böylece yaptığın şeyi bitirmeden görev değiştirebilirsin.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.975466',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Commit edilmemiş değişikliklerini (stage edilmiş ve edilmemiş) alıp geçici bir depolama alanına kaydeder, working tree'ni son commit'e uyacak şekilde geri yükler.$$, TRUE, 0),
    ($$Commit edilmemiş değişiklikleri kalıcı olarak siler, böylece sıfırdan başlayabilirsin.$$, FALSE, 1),
    ($$Commit edilmemiş değişikliklerini içeren yeni bir branch oluşturur.$$, FALSE, 2),
    ($$Değişikliklerini otomatik olarak genel bir mesajla commit eder.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 266, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Varsayılan olarak, `git stash` yepyeni, takip edilmeyen dosyaları da dahil eder mi?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Varsayılan olarak, `git stash` yepyeni, takip edilmeyen dosyaları da dahil eder mi?$$, NULL, NULL,
           $$Varsayılan olarak, `git stash` yalnızca Git'in zaten takip ettiği dosyalardaki değişiklikleri stash'ler — yepyeni, takip edilmeyen dosyalar, `-u` ya da `--all` geçmedikçe dokunulmadan bırakılır.$$, 'n8n-ai-judge', '2026-08-30 00:15:14.994286',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Evet, `git stash` her zaman her takip edilmeyen dosyayı otomatik olarak dahil eder.$$, FALSE, 0),
    ($$Hayır — varsayılan olarak yalnızca Git'in zaten takip ettiği dosyalardaki değişiklikler stash'lenir; takip edilmeyen dosyalar, `-u` ya da `--all` geçmedikçe dokunulmadan bırakılır.$$, TRUE, 1),
    ($$Evet, ama yalnızca ignore edilen dosyalar dahil edilir, normal takip edilmeyen dosyalar asla.$$, FALSE, 2),
    ($$Hayır, ve takip edilmeyen dosyaları bir stash'e dahil etmenin bir yolu yoktur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 267, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$`git stash apply` ile `git stash pop` arasındaki temel fark nedir?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git stash apply` ile `git stash pop` arasındaki temel fark nedir?$$, NULL, NULL,
           $$`git stash apply`, bir stash'in değişikliklerini listeden kaldırmadan geri yükler, böylece daha sonra tekrar kullanabilirsin; `git stash pop` ise değişiklikleri geri yükler ve stash'i tek adımda kaldırır, ki bu daha yaygın gündelik seçimdir.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.003037',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$`apply` yalnızca en eski stash'te çalışır, `pop` ise yalnızca en yenisinde.$$, FALSE, 0),
    ($$`apply` takip edilmeyen dosyaları geri yükler, `pop` ise yalnızca takip edilenleri.$$, FALSE, 1),
    ($$`apply`, bir stash'in değişikliklerini listeden kaldırmadan geri yükler; `pop` ise değişiklikleri geri yükler ve tek adımda kaldırır.$$, TRUE, 2),
    ($$`apply` stash'i hemen siler, `pop` ise onu sonsuza kadar tutar.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 268, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$`git stash pop` çalıştırdıktan sonra, karşılık gelen stash girişine ne olur?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git stash pop` çalıştırdıktan sonra, karşılık gelen stash girişine ne olur?$$, NULL, NULL,
           $$`git stash pop`, stash'in değişikliklerini uygular ve aynı adımda listeden kaldırır — `apply`'ın aksine 'arkasını temizler.'$$, 'n8n-ai-judge', '2026-08-30 00:15:15.009382',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Listede olduğu gibi, değişmeden kalır.$$, FALSE, 0),
    ($$Orijinal index'i ne olursa olsun otomatik olarak `stash@{0}` olarak yeniden adlandırılır.$$, FALSE, 1),
    ($$Mevcut branch'te normal bir commit'e dönüştürülür.$$, FALSE, 2),
    ($$Stash listesinden kaldırılır, çünkü `pop` değişiklikleri uygular ve tek adımda arkasını temizler.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 269, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Ders, `git stash drop` ve `git stash clear` hakkında neden uyarıyor?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, `git stash drop` ve `git stash clear` hakkında neden uyarıyor?$$, NULL, NULL,
           $$Hem `git stash drop` hem `git stash clear`, stash'lenmiş değişiklikleri hiçbir onay istemi olmadan kalıcı olarak atar, bu yüzden ders herhangi birini çalıştırmadan önce emin olmanı söylüyor.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.015568',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Her iki komut da stash'lenmiş değişiklikleri hiçbir onay istemi olmadan kalıcı olarak atar, bu yüzden herhangi birini çalıştırmadan önce emin olmalısın.$$, TRUE, 0),
    ($$Çünkü çalıştırmak için özel yönetici izinleri gerektirirler.$$, FALSE, 1),
    ($$Çünkü sessizce bir merge conflict'i oluştururlar.$$, FALSE, 2),
    ($$Çünkü yalnızca working tree tamamen temizse çalışırlar.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 270, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Ders, `git stash push -m` ile bir stash'e mesaj vermeyi neden öneriyor?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, `git stash push -m` ile bir stash'e mesaj vermeyi neden öneriyor?$$, NULL, NULL,
           $$Birkaç stash birikince, varsayılan `WIP on <branch>: <hash> <message>` açıklaması birbirinden ayırt etmesi zor hale gelebilir, bu yüzden `git stash push -m` ile akılda kalıcı bir mesaj vermek onları daha sonra tanımayı kolaylaştırır.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.02202',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Çünkü isimsiz stash'ler 24 saat sonra otomatik olarak silinir.$$, FALSE, 0),
    ($$Birkaç stash birikince, varsayılan `WIP on <branch>: <hash> <message>` açıklaması birbirinden ayırt etmesi zor hale gelebilir, bu yüzden akılda kalıcı bir mesaj onları daha sonra tanımayı kolaylaştırır.$$, TRUE, 1),
    ($$Çünkü mesajsız `git stash` bir hatayla başarısız olur.$$, FALSE, 2),
    ($$Çünkü mesaj, `git stash pop`'un çalışması için gereklidir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 271, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$`git stash list` çalıştırıyorsun ve aşağıdaki çıktıyı görüyorsun. Derse göre, hangi stash en yenisidir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git stash list` çalıştırıyorsun ve aşağıdaki çıktıyı görüyorsun. Derse göre, hangi stash en yenisidir?$$, $$stash@{0}: WIP on add-password-reset: 8a1b2c3 Add PasswordController
stash@{1}: WIP on main: a1b2c3d Fix typo in README$$, $$bash$$,
           $$`git stash list`'te, `stash@{0}` her zaman en son stash'tir — burada bu, `add-password-reset`'ten stash'lenen; `stash@{1}` ise daha eski olan, `main`'den stash'lenen.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.027459',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$`stash@{1}`, `main`'den stash'lenen.$$, FALSE, 0),
    ($$Hiçbiri — en son stash `git stash list`'te asla görünmez.$$, FALSE, 1),
    ($$`stash@{0}`, `add-password-reset`'ten stash'lenen.$$, TRUE, 2),
    ($$İkisi de eşit derecede yenidir — liste herhangi bir sıra belirtmez.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 272, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$`git stash -u` ve `git stash --all` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git stash -u` ve `git stash --all` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Düz `git stash`, takip edilmeyen dosyaları dahil etmez; `-u`, takip edilmeyen dosyaları stash'e ekler, `--all` ise daha ileri gidip ignore edilen dosyaları da dahil eder.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.032319',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git stash -u`, takip edilen değişikliklere ek olarak takip edilmeyen dosyaları da stash'e dahil eder.$$, TRUE, 0),
    ($$`git stash --all`, takip edilmeyen dosyaları dahil eder, ama ignore edilenleri asla.$$, FALSE, 1),
    ($$Hiçbir flag olmadan düz `git stash`, takip edilmeyen dosyaları dahil etmez.$$, TRUE, 2),
    ($$`git stash -u` ve `git stash --all`, her durumda birebir aynı şekilde davranır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 273, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Derse göre stash'ler ve index'leri hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre stash'ler ve index'leri hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Stash'ler birikir, bu yüzden aynı anda birden fazlasına sahip olabilirsin, ve `stash@{1}` gibi bir index'e referans vererek belirli birini apply ya da pop edebilirsin.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.037769',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$`stash@{0}` her zaman kaydettiğin en eski stash'e işaret eder.$$, FALSE, 0),
    ($$Stash'ler birikir, bu yüzden aynı anda birden fazlasına sahip olabilirsin.$$, TRUE, 1),
    ($$Birden fazla stash'in olduğunda, `git stash pop` bir index belirtmeni gerektirir.$$, FALSE, 2),
    ($$`stash@{1}` gibi bir index'e referans vererek belirli bir stash'i apply ya da pop edebilirsin.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 274, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'stash')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, bir stash'in var olduğunu unutmak kolay olduğu için düzenli olarak `git stash list` çalıştırmayı öneriyor, En İyi Pratikler bölümü ise bir gün ya da ikiden fazla stash'lenmiş duran işin genellikle gerçek bir commit olması gerektiğinin işareti olduğunu belirtiyor.$$, 'n8n-ai-judge', '2026-08-30 00:15:15.043021',
           now(), now()
    FROM topic
    WHERE slug = 'stash'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Bir stash'in var olduğunu unutmak kolaydır, bu yüzden düzenli olarak `git stash list` çalıştırmak iyi bir alışkanlıktır.$$, TRUE, 0),
    ($$Alışkanlıktan `pop` yerine `apply` kullanmanın gerçek bir dezavantajı yoktur, çünkü ikisi birebir aynı davranır.$$, FALSE, 1),
    ($$Takip edilmeyen dosyalar varsayılan olarak stash'lenir, bu yüzden `-u` ya da `--all`'ı düşünmene gerek yoktur.$$, FALSE, 2),
    ($$İş bir gün ya da ikiden fazla stash'lenmiş durursa, bu genellikle onun yerine düzgün bir commit olması gerektiğinin bir işaretidir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'stash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

