-- Portable promotion-style migration linking the EN GitHub & Remotes
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, and branches-and-merging/V473-V474 (see
-- those files for the full rationale).
--
-- Development Question IDs: 175, 176, 177, 178, 179, 180, 181, 182, 183, 184
-- Topic: github-and-remotes (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 175, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$According to the lesson, what is a remote, fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is a remote, fundamentally?$$, NULL, NULL,
           $$A remote is a named reference to another copy of the repository (usually on GitHub) — just a URL Git remembers, not a live connection or mount.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.827924',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$A named reference to another copy of the repository, usually hosted on GitHub — not a live connection.$$, TRUE, 0),
    ($$A live network connection that keeps your local repository automatically synced with GitHub.$$, FALSE, 1),
    ($$A mounted folder that shows GitHub's files directly inside your local project.$$, FALSE, 2),
    ($$A special branch that only GitHub can create.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 176, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$How does the lesson describe the relationship between your local repository and a remote repository on GitHub?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$How does the lesson describe the relationship between your local repository and a remote repository on GitHub?$$, NULL, NULL,
           $$The lesson is explicit that both the local and remote repositories are complete, independent copies, each with its own full commit history — nothing syncs automatically in the background.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.851427',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$The remote is a partial, server-only copy that only stores commit metadata.$$, FALSE, 0),
    ($$Both are complete, independent copies of the project, each with its own full commit history.$$, TRUE, 1),
    ($$The local repository is temporary and only the remote copy is considered permanent.$$, FALSE, 2),
    ($$The remote automatically stays in sync with the local repository in the background.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 177, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$You created a repository locally with `git init` and want to connect it to a new, empty GitHub repository. According to the lesson, what should you do?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You created a repository locally with `git init` and want to connect it to a new, empty GitHub repository. According to the lesson, what should you do?$$, NULL, NULL,
           $$For a repo that already exists locally (`git init`) and needs to connect to a new empty GitHub repo, the lesson's example is `git remote add origin <url>` followed by `git push -u origin main` — `git clone` is for the opposite situation, where the repo already exists on GitHub.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.859821',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Run `git clone` to download the empty GitHub repository over your local one.$$, FALSE, 0),
    ($$Run `git fetch origin` to pull the GitHub repository's structure into your local one.$$, FALSE, 1),
    ($$Run `git remote add origin <url>`, then `git push -u origin main`.$$, TRUE, 2),
    ($$Run `git pull origin main` before doing anything else.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 178, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$What does the lesson call 'the single most important distinction' in this lesson?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does the lesson call 'the single most important distinction' in this lesson?$$, NULL, NULL,
           $$The lesson explicitly calls this 'the single most important distinction': `git fetch` downloads remote changes without integrating them, while `git pull` is fetch + merge.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.86728',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$The difference between `git remote` and `git remote -v`.$$, FALSE, 0),
    ($$The difference between `origin` and other remote names.$$, FALSE, 1),
    ($$The difference between deleting a local branch and deleting a remote branch.$$, FALSE, 2),
    ($$That `git fetch` downloads remote changes without integrating them, while `git pull` is fetch + merge.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 179, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$After running `git fetch origin`, what has happened to your local `main` branch?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$After running `git fetch origin`, what has happened to your local `main` branch?$$, NULL, NULL,
           $$After a fetch, local `main` hasn't moved at all — Git has only updated its record of where `origin/main` currently points.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.874395',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Nothing — `main` hasn't moved; only Git's record of where `origin/main` points has been updated.$$, TRUE, 0),
    ($$`main` has been fast-forwarded to match `origin/main`.$$, FALSE, 1),
    ($$`main` has been merged with `origin/main`, creating a merge commit.$$, FALSE, 2),
    ($$`main` has been deleted and replaced with `origin/main`.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 180, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$Which of the following are true about `git fetch`, according to the lesson? (Select all that apply)$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about `git fetch`, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$`git fetch` downloads new commits from the remote without touching your working tree or local branches — it does not merge anything or upload anything.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.880915',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$It downloads new commits from the remote.$$, TRUE, 0),
    ($$It automatically merges the downloaded commits into your current branch.$$, FALSE, 1),
    ($$It does not touch your working tree or local branches.$$, TRUE, 2),
    ($$It uploads your local commits to the remote.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 181, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$Why might Git refuse to run `git pull`?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why might Git refuse to run `git pull`?$$, NULL, NULL,
           $$Because `pull` ends with a merge, it's subject to the same safety rule as switching branches: Git refuses if that merge would overwrite uncommitted changes it can't safely combine.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.887207',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Because `git pull` can only be run once per day.$$, FALSE, 0),
    ($$Because the merge that `pull` ends with would overwrite uncommitted changes it can't safely combine.$$, TRUE, 1),
    ($$Because `git pull` requires administrator privileges.$$, FALSE, 2),
    ($$Because the remote repository has been deleted.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 182, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$What does the `-u` flag do when you run `git push -u origin add-password-reset` for a brand-new local branch?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does the `-u` flag do when you run `git push -u origin add-password-reset` for a brand-new local branch?$$, NULL, NULL,
           $$`-u` (`--set-upstream`) establishes the tracking relationship the first time you push a new branch, so future plain `git push`/`git pull` on that branch know where to send and receive commits.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.893795',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$It force-pushes the branch, overwriting any conflicting history on the remote.$$, FALSE, 0),
    ($$It deletes any existing branch on the remote with the same name first.$$, FALSE, 1),
    ($$It establishes the tracking relationship, so future plain `git push`/`git pull` on that branch know where to send/receive commits.$$, TRUE, 2),
    ($$It automatically merges the branch into `main` on the remote.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 183, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$Which of the following are true about deleting branches, according to the lesson? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about deleting branches, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$A local branch and its remote copy are independent — deleting the local one has no effect on the remote. Removing a branch on GitHub itself requires `git push origin --delete <branch>`.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.899847',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Deleting a local branch with `git branch -d` also deletes it on the remote.$$, FALSE, 0),
    ($$A local branch and its remote copy are independent — deleting one has no effect on the other.$$, TRUE, 1),
    ($$There is no way to delete a branch on GitHub itself.$$, FALSE, 2),
    ($$Deleting a branch on GitHub requires `git push origin --delete <branch>`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 184, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes section warns that `git fetch` doesn't touch your files, only Git's knowledge of the remote, and its Best Practices recommend always using `-u` on a new branch's first push.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.905641',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Assuming `git fetch` updates your files is a mistake — it only updates Git's knowledge of the remote, not your working tree.$$, TRUE, 0),
    ($$It's fine to skip `-u` on the first push of a new branch since Git sets it up automatically anyway.$$, FALSE, 1),
    ($$You should avoid running `git fetch` before starting work each day since it wastes time.$$, FALSE, 2),
    ($$A good habit is to always use `-u` the first time you push a new branch, since it pays off on every push/pull after that.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

