-- Portable promotion-style migration linking the TR GitHub & Remotes
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, and branches-and-merging/V473-V474 (see
-- those files for the full rationale).
--
-- Development Question IDs: 185, 186, 187, 188, 189, 190, 191, 192, 193, 194
-- Topic: github-and-remotes (language: tr)
-- Turkish counterparts of the English questions in V475 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 185, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Derse göre bir remote, temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir remote, temelde nedir?$$, NULL, NULL,
           $$Bir remote, repository'nin başka bir kopyasına (genellikle GitHub'da) adlandırılmış bir referanstır — Git'in hatırladığı yalnızca bir URL'dir, canlı bir bağlantı ya da mount değildir.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.911546',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Repository'nin başka bir kopyasına, genellikle GitHub'da barındırılana, adlandırılmış bir referans — canlı bir bağlantı değil.$$, TRUE, 0),
    ($$Yerel repository'ni GitHub ile otomatik olarak senkronize tutan canlı bir ağ bağlantısı.$$, FALSE, 1),
    ($$GitHub'ın dosyalarını doğrudan yerel projenin içinde gösteren mount edilmiş bir klasör.$$, FALSE, 2),
    ($$Yalnızca GitHub'ın oluşturabileceği özel bir branch.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 186, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Ders, yerel repository'n ile GitHub'daki bir remote repository arasındaki ilişkiyi nasıl tanımlıyor?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, yerel repository'n ile GitHub'daki bir remote repository arasındaki ilişkiyi nasıl tanımlıyor?$$, NULL, NULL,
           $$Ders, hem yerel hem remote repository'nin eksiksiz, bağımsız kopyalar olduğunu ve her birinin kendi tam commit geçmişine sahip olduğunu açıkça belirtiyor — arka planda hiçbir şey otomatik senkronize olmaz.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.917825',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Remote, yalnızca commit metadata'sı saklayan kısmi, sadece-sunucu bir kopyadır.$$, FALSE, 0),
    ($$İkisi de eksiksiz, bağımsız kopyalardır, her birinin kendi tam commit geçmişi vardır.$$, TRUE, 1),
    ($$Yerel repository geçicidir, yalnızca remote kopya kalıcı sayılır.$$, FALSE, 2),
    ($$Remote, arka planda yerel repository ile otomatik olarak senkronize kalır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 187, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Bir repository'yi `git init` ile yerel olarak oluşturdun ve onu yeni, boş bir GitHub repository'sine bağlamak istiyorsun. Derse göre ne yapmalısın?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bir repository'yi `git init` ile yerel olarak oluşturdun ve onu yeni, boş bir GitHub repository'sine bağlamak istiyorsun. Derse göre ne yapmalısın?$$, NULL, NULL,
           $$Zaten yerel olarak var olan (`git init`) ve yeni, boş bir GitHub repository'sine bağlanması gereken bir repo için dersin örneği `git remote add origin <url>`, ardından `git push -u origin main`'dir — `git clone` ise tam tersi durum içindir, repo zaten GitHub'da var olduğunda.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.924104',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Boş GitHub repository'sini yerel olanının üzerine indirmek için `git clone` çalıştır.$$, FALSE, 0),
    ($$GitHub repository'sinin yapısını yerel olanına çekmek için `git fetch origin` çalıştır.$$, FALSE, 1),
    ($$`git remote add origin <url>` çalıştır, sonra `git push -u origin main`.$$, TRUE, 2),
    ($$Başka bir şey yapmadan önce `git pull origin main` çalıştır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 188, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Ders, bu derste 'en önemli tek ayrım' olarak neyi adlandırıyor?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, bu derste 'en önemli tek ayrım' olarak neyi adlandırıyor?$$, NULL, NULL,
           $$Ders bunu açıkça 'en önemli tek ayrım' olarak adlandırıyor: `git fetch`, remote değişikliklerini entegre etmeden indirir, `git pull` ise fetch + merge'dir.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.930789',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$`git remote` ile `git remote -v` arasındaki fark.$$, FALSE, 0),
    ($$`origin` ile diğer remote isimleri arasındaki fark.$$, FALSE, 1),
    ($$Yerel bir branch'i silmek ile remote bir branch'i silmek arasındaki fark.$$, FALSE, 2),
    ($$`git fetch`'in remote değişikliklerini entegre etmeden indirmesi, `git pull`'un ise fetch + merge olması.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 189, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$`git fetch origin` çalıştırdıktan sonra, yerel `main` branch'ine ne olmuştur?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git fetch origin` çalıştırdıktan sonra, yerel `main` branch'ine ne olmuştur?$$, NULL, NULL,
           $$Bir fetch'ten sonra, yerel `main` hiç hareket etmemiştir — Git yalnızca `origin/main`'in şu an nereye işaret ettiğine dair kaydını güncellemiştir.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.936987',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Hiçbir şey — `main` hareket etmemiştir; yalnızca Git'in `origin/main`'in nereye işaret ettiğine dair kaydı güncellenmiştir.$$, TRUE, 0),
    ($$`main`, `origin/main`'e uyacak şekilde fast-forward edilmiştir.$$, FALSE, 1),
    ($$`main`, `origin/main` ile merge edilmiş, bir merge commit oluşturulmuştur.$$, FALSE, 2),
    ($$`main` silinmiş ve `origin/main` ile değiştirilmiştir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 190, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Derse göre `git fetch` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre `git fetch` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git fetch`, working tree'ne ya da yerel branch'lerine dokunmadan remote'tan yeni commit'leri indirir — hiçbir şeyi merge etmez ya da yüklemez.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.943001',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Remote'tan yeni commit'leri indirir.$$, TRUE, 0),
    ($$İndirilen commit'leri otomatik olarak mevcut branch'ine merge eder.$$, FALSE, 1),
    ($$Working tree'ne ya da yerel branch'lerine dokunmaz.$$, TRUE, 2),
    ($$Yerel commit'lerini remote'a yükler.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 191, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Git neden `git pull`'u çalıştırmayı reddedebilir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Git neden `git pull`'u çalıştırmayı reddedebilir?$$, NULL, NULL,
           $$`pull` bir merge ile sona erdiği için, branch değiştirmekle aynı güvenlik kuralına tabidir: Git, o merge güvenle birleştiremeyeceği commit edilmemiş değişikliklerin üzerine yazacaksa reddeder.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.949112',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Çünkü `git pull` günde yalnızca bir kez çalıştırılabilir.$$, FALSE, 0),
    ($$Çünkü `pull`'un sonundaki merge, güvenle birleştiremeyeceği commit edilmemiş değişikliklerin üzerine yazacaktır.$$, TRUE, 1),
    ($$Çünkü `git pull` yönetici izinleri gerektirir.$$, FALSE, 2),
    ($$Çünkü remote repository silinmiştir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 192, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Yepyeni bir yerel branch için `git push -u origin add-password-reset` çalıştırdığında `-u` flag'i ne yapar?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Yepyeni bir yerel branch için `git push -u origin add-password-reset` çalıştırdığında `-u` flag'i ne yapar?$$, NULL, NULL,
           $$`-u` (`--set-upstream`), yeni bir branch'i ilk kez push ederken tracking ilişkisini kurar, böylece sonraki düz `git push`/`git pull`, o branch'te commit'leri nereye gönderip nereden alacağını bilir.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.955419',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Branch'i force-push eder, remote'taki çakışan geçmişin üzerine yazar.$$, FALSE, 0),
    ($$Remote'ta aynı isimde var olan bir branch'i önce siler.$$, FALSE, 1),
    ($$Tracking ilişkisini kurar, böylece sonraki düz `git push`/`git pull`, o branch'te commit'leri nereye gönderip nereden alacağını bilir.$$, TRUE, 2),
    ($$Branch'i remote'ta otomatik olarak `main`'e merge eder.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 193, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Derse göre branch silmekle ilgili aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre branch silmekle ilgili aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Yerel bir branch ile remote kopyası bağımsızdır — yerel olanı silmenin remote üzerinde hiçbir etkisi yoktur. GitHub'ın kendisinde bir branch'i kaldırmak `git push origin --delete <branch>` gerektirir.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.961435',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$`git branch -d` ile yerel bir branch'i silmek, onu remote'ta da siler.$$, FALSE, 0),
    ($$Yerel bir branch ile onun remote kopyası bağımsızdır — birini silmenin diğeri üzerinde hiçbir etkisi yoktur.$$, TRUE, 1),
    ($$GitHub'ın kendisinde bir branch'i silmenin bir yolu yoktur.$$, FALSE, 2),
    ($$GitHub'da bir branch'i silmek `git push origin --delete <branch>` gerektirir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 194, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'github-and-remotes')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, `git fetch`'in dosyalarına dokunmadığını, yalnızca Git'in remote hakkındaki bilgisini güncellediğini uyarıyor, En İyi Pratikler bölümü ise yeni bir branch'in ilk push'unda her zaman `-u` kullanmayı öneriyor.$$, 'n8n-ai-judge', '2026-08-29 15:47:43.967491',
           now(), now()
    FROM topic
    WHERE slug = 'github-and-remotes'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$`git fetch`'in dosyalarını güncellediğini varsaymak bir hatadır — yalnızca Git'in remote hakkındaki bilgisini günceller, working tree'ni değil.$$, TRUE, 0),
    ($$Git zaten otomatik kurduğu için yeni bir branch'in ilk push'unda `-u`'yu atlamak sorun değildir.$$, FALSE, 1),
    ($$Zaman kaybettirdiği için her gün işe başlamadan önce `git fetch` çalıştırmaktan kaçınmalısın.$$, FALSE, 2),
    ($$Yeni bir branch'i push ederken ilk seferde her zaman `-u` kullanmak iyi bir alışkanlıktır, çünkü bundan sonraki her push/pull'da karşılığını alırsın.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'github-and-remotes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

