-- Promotion batch
-- Topic: if-else (language: en x6, tr x6)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 6 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/if-else.md and content/tr/if-else.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$A developer coming from C writes `if (count)` in Java, where `count` is an `int`. What happens?$$,
           NULL, NULL,
           $$Java only accepts a `boolean` expression as a condition and never converts a number to `boolean` implicitly, so `if (count)` is a compile error. Running the block whenever the value is nonzero is how C behaves; Java deliberately rejected that idiom.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$The code does not compile, because the condition must be a `boolean` expression$$, TRUE, 0),
        ($$It compiles, and the block runs whenever `count` is not zero$$, FALSE, 1),
        ($$It compiles, but the block never runs because an `int` counts as `false`$$, FALSE, 2),
        ($$It compiles with a warning, and `count` is converted to `boolean` at runtime$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`int sayi = 5;` tanımlandıktan sonra aşağıdaki `if` satırlarından hangisi Java'da derlenir?$$,
           NULL, NULL,
           $$`sayi > 0` bir `boolean` üretir, bu yüzden koşul olarak geçerlidir. Java sayısal bir değeri `boolean`'a kendiliğinden çevirmez: `if (sayi)` ve `if (1)` derlenmez. `if (sayi = 0)` de derlenmez, çünkü bu bir karşılaştırma değil atamadır ve sonucu `int`'tir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$`if (sayi)`$$, FALSE, 0),
        ($$`if (sayi = 0)`$$, FALSE, 1),
        ($$`if (sayi > 0)`$$, TRUE, 2),
        ($$`if (1)`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (CODE_OUTPUT, BEGINNER)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int score = 95;
String grade;

if (score >= 60) {
    grade = "D";
} else if (score >= 90) {
    grade = "A";
} else {
    grade = "F";
}

System.out.println(grade);$$, $$java$$,
           $$Conditions are checked top to bottom and the first one that is `true` wins. `95 >= 60` is already `true`, so `grade` becomes `D` and the rest of the chain is skipped. `score >= 90` would also be `true`, but it is never evaluated, because the broader condition was written before the more specific one.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$`A`$$, FALSE, 0),
        ($$`D`$$, TRUE, 1),
        ($$`F`$$, FALSE, 2),
        ($$Nothing, because the code does not compile$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (CODE_OUTPUT, BEGINNER)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int sicaklik = 35;

if (sicaklik > 20) {
    System.out.println("Ilık");
} else if (sicaklik > 30) {
    System.out.println("Sıcak");
} else {
    System.out.println("Soğuk");
}$$, $$java$$,
           $$Koşullar yukarıdan aşağıya kontrol edilir ve `true` olan ilk koşulun bloğu çalışır. `35 > 20` zaten `true` olduğu için `Ilık` yazdırılır ve zincirin kalanı atlanır. `35 > 30` da doğrudur ama o koşula hiç gelinmez; bir zincirde en fazla bir blok çalıştığı için iki satır birden de yazdırılmaz.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$`Sıcak`$$, FALSE, 0),
        ($$Önce `Ilık`, sonra `Sıcak`$$, FALSE, 1),
        ($$`Soğuk`$$, FALSE, 2),
        ($$`Ilık`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int stock = 0;

if (stock > 0)
    System.out.println("In stock");
    System.out.println("Ships today");$$, $$java$$,
           $$Without braces, an `if` covers only the single statement right after it. The condition is `false`, so `In stock` is skipped, but the second `println` is not part of the `if` at all and always runs. The indentation only makes it look as if both lines belong to the condition.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$Nothing is printed$$, FALSE, 0),
        ($$`In stock`, then `Ships today`$$, FALSE, 1),
        ($$`Ships today`$$, TRUE, 2),
        ($$`In stock`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$boolean uye = false;

if (uye)
    System.out.println("Hoş geldin");
    System.out.println("İndirim uygulandı");

System.out.println("Bitti");$$, $$java$$,
           $$Süslü parantez olmadığında `if` yalnızca hemen ardından gelen tek ifadeyi kapsar. Koşul `false` olduğu için `Hoş geldin` atlanır; ikinci `println` ise girintisine rağmen `if`'in dışındadır ve her zaman çalışır. Bu yüzden yalnızca `Bitti` yazdırılmaz, `İndirim uygulandı` da yazdırılır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$Önce `İndirim uygulandı`, sonra `Bitti`$$, TRUE, 0),
        ($$Yalnızca `Bitti`$$, FALSE, 1),
        ($$`Hoş geldin`, `İndirim uygulandı` ve `Bitti`$$, FALSE, 2),
        ($$Hiçbir şey yazdırmaz$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Which of these statements about `==` in Java are true? (Select all that apply)$$,
           NULL, NULL,
           $$`0.1 + 0.2 == 0.3` is `false` because binary floating point cannot store these decimals exactly, and for objects such as `String`, `==` compares references, which is why `.equals()` is used for content. For primitives like `int`, `==` compares the values themselves, and like every comparison operator it produces a `boolean`, so it works directly as a condition.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$`0.1 + 0.2 == 0.3` evaluates to `false`$$, TRUE, 0),
        ($$For two `int` values, `==` compares references, not values$$, FALSE, 1),
        ($$`==` cannot be used directly as an `if` condition$$, FALSE, 2),
        ($$For two `String` objects, `==` compares references, not content$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdaki kontrollerden hangileri `==` ile yapıldığında beklenmedik sonuç verebilir? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$Ondalıklı sayılar ikili kayan nokta ile tam olarak saklanamadığı için `double` değerleri `==` ile karşılaştırmak risklidir; bunun yerine farkın küçük bir eşikten az olup olmadığına bakılır. `String` gibi nesnelerde `==` içeriği değil referansı karşılaştırır, içerik için `.equals()` gerekir. `int` gibi ilkel tiplerde ise `==` doğrudan değeri karşılaştırır ve güvenlidir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$İki `double` değerin eşit olup olmadığını kontrol etmek$$, TRUE, 0),
        ($$İki `String`'in içeriğinin aynı olup olmadığını kontrol etmek$$, TRUE, 1),
        ($$İki `int` değerin eşit olup olmadığını kontrol etmek$$, FALSE, 2),
        ($$Bir `int` değerin sıfıra eşit olup olmadığını kontrol etmek$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$In `if (user != null && user.isActive())`, what happens when `user` is `null`?$$,
           NULL, NULL,
           $$`&&` is short-circuited: once the left side is `false`, the result is already known and the right side is never evaluated. That is exactly why this pattern is safe. If both sides were always evaluated, calling a method on `null` would throw a `NullPointerException`.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$`user.isActive()` is called and throws a `NullPointerException`$$, FALSE, 0),
        ($$`user.isActive()` is never called, because the left side is already `false`$$, TRUE, 1),
        ($$Both sides are evaluated, and the combined result is `false`$$, FALSE, 2),
        ($$The code does not compile, because a method call cannot follow a `null` check$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`girisYapti() || misafirModuAcik()` ifadesinde `girisYapti()` `true` döndürürse ne olur?$$,
           NULL, NULL,
           $$`||` kısa devre değerlendirilir: sol taraf `true` ise sonuç zaten bellidir ve sağ taraf hiç çalıştırılmaz. Bu yüzden `misafirModuAcik()` çağrılmaz. Sağ tarafın çağrılıp sonucunun yok sayılması gibi bir durum yoktur; metot hiç çalışmadığı için varsa yan etkisi de gerçekleşmez.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$`misafirModuAcik()` çağrılır ama döndürdüğü değer yok sayılır$$, FALSE, 0),
        ($$Her iki metot da çağrılır ve sonuçları birleştirilir$$, FALSE, 1),
        ($$`misafirModuAcik()` hiç çağrılmaz, çünkü sonuç zaten `true` olarak bellidir$$, TRUE, 2),
        ($$Önce `misafirModuAcik()`, ardından `girisYapti()` çağrılır$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why can a ternary operator appear on the right-hand side of an assignment, while an `if`/`else` cannot?$$,
           NULL, NULL,
           $$The ternary operator is an expression: it evaluates directly to a value, which can then be assigned. `if`/`else` is a statement and produces no value. Both need a `boolean` condition, so the type of the condition is not what separates them.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en6
         CROSS JOIN (VALUES
        ($$The ternary operator accepts any type as its condition, while `if`/`else` needs a `boolean`$$, FALSE, 0),
        ($$The ternary operator can check several conditions at once, while `if`/`else` checks only one$$, FALSE, 1),
        ($$The ternary operator is an expression that evaluates to a value, while `if`/`else` is a statement$$, TRUE, 2),
        ($$The ternary operator is evaluated at compile time, while `if`/`else` runs at runtime$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Üçlü (ternary) operatör hangi durumda bir `if`/`else` yerine uygun bir tercihtir?$$,
           NULL, NULL,
           $$Üçlü operatör doğrudan bir değere değerlendirilen bir ifadedir; basit bir koşula göre tek bir değer seçmek, örneğin bir atama yapmak için uygundur. İkiden fazla sonuç gerektiğinde iç içe yazmak teknik olarak çalışır ama okunabilirliği hızla bozar; o durumda `else if` zinciri tercih edilir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'if-else'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr6
         CROSS JOIN (VALUES
        ($$İkiden fazla sonuç arasında seçim yapılacağında, iç içe yazılarak$$, FALSE, 0),
        ($$Her dalda birden fazla satır kod çalıştırılacağında$$, FALSE, 1),
        ($$Koşul `boolean` değil de sayısal bir değer olduğunda$$, FALSE, 2),
        ($$Basit bir koşula göre tek bir değer üretmek gerektiğinde, örneğin bir atamada$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);
