-- Promotion batch
-- Topic: for-loop (language: en x6, tr x6)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 6 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/for-loop.md and content/tr/for-loop.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In `for (int i = 0; i < 5; i++)`, when does `i++` run?$$,
           NULL, NULL,
           $$The update part runs at the end of every iteration, after the body, and the condition is then checked again. Running once before the loop starts describes the initialization (`int i = 0`), not the update.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$At the end of every iteration, before the condition is checked again$$, TRUE, 0),
        ($$Once, before the loop starts$$, FALSE, 1),
        ($$At the start of every iteration, before the body$$, FALSE, 2),
        ($$Only when the condition becomes `false`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`for (int i = 0; i < 3; i++)` döngüsünde `int i = 0` kısmı kaç kez çalışır?$$,
           NULL, NULL,
           $$Başlangıç kısmı döngü başlamadan önce yalnızca bir kez çalışır. Her adımda tekrarlananlar koşul kontrolü (`i < 3`) ve adımın sonundaki güncellemedir (`i++`); başlangıç her adımda yeniden çalışsaydı sayaç hiç ilerleyemezdi.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$Her adımın başında bir kez$$, FALSE, 0),
        ($$Her adımın sonunda bir kez$$, FALSE, 1),
        ($$Yalnızca bir kez, döngü başlamadan önce$$, TRUE, 2),
        ($$Koşul her kontrol edildiğinde$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (MULTIPLE_CHOICE, BEGINNER)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of these can be written as the update part of a `for` loop to change the counter `i`? (Select all that apply)$$,
           NULL, NULL,
           $$All three parts of a `for` are flexible: `i--` counts down and `i += 2` advances two at a time. `i++` is only the most common form, not the only one. `i + 1` merely computes a value without storing it, so it does not change `i`, and Java does not even accept it as a statement.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$`i + 1`, to advance one at a time$$, FALSE, 0),
        ($$Only `i++`; no other update expression compiles$$, FALSE, 1),
        ($$`i--`, to count down$$, TRUE, 2),
        ($$`i += 2`, to advance two at a time$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (MULTIPLE_CHOICE, BEGINNER)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`for` döngüsünün kısımları hakkında aşağıdakilerden hangileri doğrudur? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$`for`'un üç kısmı da esnektir: sayaç `i--` ile geriye doğru sayabilir, adım büyüklüğü de `i += 2` gibi farklı bir değer olabilir. Sayacın `0`'dan başlaması yalnızca en yaygın biçimdir, zorunluluk değildir; koşulda da `<` dışında `<=` gibi başka karşılaştırmalar kullanılabilir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$Sayaç her zaman `0`'dan başlamak zorundadır$$, FALSE, 0),
        ($$Sayaç `i--` ile geriye doğru sayabilir$$, TRUE, 1),
        ($$Koşulda yalnızca `<` operatörü kullanılabilir$$, FALSE, 2),
        ($$Adım büyüklüğü 1 olmak zorunda değildir; `i += 2` yazılabilir$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (CODE_OUTPUT, BEGINNER)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$for (int i = 1; i <= 5; i++) {
    if (i == 3) {
        break;
    }
    System.out.println(i);
}

System.out.println("Done");$$, $$java$$,
           $$When `i` reaches 3, `break` ends the loop immediately, even though `i <= 5` is still `true`, and control jumps to the line after the loop. So 3 is never printed and neither are 4 and 5. Skipping only 3 and carrying on with 4 and 5 is what `continue` would do.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$`1`, `2`, `4`, `5`, then `Done`$$, FALSE, 0),
        ($$`1`, `2`, then `Done`$$, TRUE, 1),
        ($$`1`, `2`, `3`, then `Done`$$, FALSE, 2),
        ($$`1`, then `2`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (CODE_OUTPUT, BEGINNER)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int[] sayilar = {4, 9, 7, 2};

for (int i = 0; i < sayilar.length; i++) {
    if (sayilar[i] == 7) {
        System.out.println("Bulundu: " + i);
        break;
    }
    System.out.println("Kontrol: " + sayilar[i]);
}$$, $$java$$,
           $$Döngü 4 ve 9 için `Kontrol` satırını yazdırır. 7'ye gelindiğinde indeksi olan 2 yazdırılır ve `break` döngüyü tamamen sonlandırır; bu yüzden ne 7 için `Kontrol` satırı ne de kalan eleman olan 2 işlenir. Aranan bulunduktan sonra kalan elemanlara bakmamak, `break`'in aramalardaki tipik kullanımıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$`Kontrol: 4`, `Kontrol: 9`, sonra `Bulundu: 2`$$, TRUE, 0),
        ($$`Kontrol: 4`, `Kontrol: 9`, `Bulundu: 2`, sonra `Kontrol: 2`$$, FALSE, 1),
        ($$`Kontrol: 4`, `Kontrol: 9`, `Kontrol: 7`, sonra `Bulundu: 2`$$, FALSE, 2),
        ($$Yalnızca `Bulundu: 2`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (CODE_OUTPUT, BEGINNER)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$for (int i = 1; i <= 5; i++) {
    if (i % 2 == 0) {
        continue;
    }
    System.out.println(i);
}$$, $$java$$,
           $$For even values of `i`, `continue` skips the rest of that iteration, so `println` is not reached, and the loop moves on to the update step. The loop itself does not end, which is why 3 and 5 are still printed. Stopping after 1 is what `break` would do.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$`1`$$, FALSE, 0),
        ($$`2`, then `4`$$, FALSE, 1),
        ($$`1`, `2`, `3`, `4`, then `5`$$, FALSE, 2),
        ($$`1`, `3`, then `5`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (CODE_OUTPUT, BEGINNER)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int toplam = 0;

for (int i = 1; i <= 4; i++) {
    if (i == 2) {
        continue;
    }
    toplam += i;
}

System.out.println(toplam);$$, $$java$$,
           $$`i` 2 olduğunda `continue` o adımın kalanını atlar, yani 2 toplama eklenmez; döngü ise sürer ve 3 ile 4 eklenir: 1 + 3 + 4 = 8. Sonucun 10 olması hiçbir adımın atlanmadığı, 1 olması ise döngünün `break` ile tamamen bittiği anlamına gelirdi.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$`10`$$, FALSE, 0),
        ($$`8`$$, TRUE, 1),
        ($$`1`$$, FALSE, 2),
        ($$`3`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$A loop is written as `for (;;)`. In normal control flow, what makes it stop?$$,
           NULL, NULL,
           $$With all three parts left out there is no condition that could ever become `false`, so the loop does not end on its own. In normal control flow it is left through a `break` or a `return` in the body. Outside normal flow, an uncaught exception or the program exiting would end it as well. It is valid Java, used deliberately when you cannot know in advance when to stop.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$A `break` or a `return` in its body, since it has no condition that could end it$$, TRUE, 0),
        ($$Nothing has to, since the compiler rejects a `for` that has no condition$$, FALSE, 1),
        ($$Its hidden counter, which ends the loop once it reaches a built-in limit$$, FALSE, 2),
        ($$A `continue` in its body, since skipping a step also leaves the loop$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$İstenmeden oluşan bir sonsuz `for` döngüsünün en yaygın sebebi hangisidir?$$,
           NULL, NULL,
           $$Güncelleme adımı koşulu hiçbir zaman `false` yapmıyorsa, örneğin `i++` yazılmamışsa, döngü kendiliğinden bitemez ve program takılır. Sayacı `for`'un kendi başlangıç kısmında tanımlamak ise tam tersine önerilen bir pratiktir; yalnızca sayacın kapsamını daraltır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$Sayaç değişkenini `for`'un kendi başlangıç kısmında tanımlamak$$, FALSE, 0),
        ($$Koşulda `<=` yerine `<` kullanmak$$, FALSE, 1),
        ($$Güncelleme adımının koşulu hiçbir zaman `false` yapmaması, örneğin `i++` yazmayı unutmak$$, TRUE, 2),
        ($$Döngüyü `break` ile erken bitirmek$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$A loop over `int[] values` is written as `for (int i = 0; i <= values.length; i++)` and reads `values[i]` in its body. What goes wrong?$$,
           NULL, NULL,
           $$Valid indexes run from `0` to `length - 1`. With `<=`, the loop runs one extra time with `i` equal to `values.length`, an index that does not exist, and Java throws `ArrayIndexOutOfBoundsException`. The loop does end and every real element is read; the problem is the one read past the end.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en6
         CROSS JOIN (VALUES
        ($$The last element of the array is never read$$, FALSE, 0),
        ($$The last iteration reads an index that does not exist and throws `ArrayIndexOutOfBoundsException`$$, TRUE, 1),
        ($$The loop never ends, because the condition stays `true`$$, FALSE, 2),
        ($$The code does not compile, because `<=` cannot be combined with `.length`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`i` sayacı `0`'dan başlıyorsa, bir dizinin tüm elemanlarını tam olarak bir kez gezen koşul hangisidir?$$,
           NULL, NULL,
           $$Geçerli indeksler `0` ile `length - 1` arasındadır, bu yüzden doğru koşul `i < dizi.length`'tir. `i <= dizi.length` bir adım fazla çalışır ve var olmayan bir indekse erişerek `ArrayIndexOutOfBoundsException` fırlatır; `i < dizi.length - 1` ise son elemanı atlar.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'for-loop'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr6
         CROSS JOIN (VALUES
        ($$`i <= dizi.length`$$, FALSE, 0),
        ($$`i < dizi.length - 1`$$, FALSE, 1),
        ($$`i <= dizi.length + 1`$$, FALSE, 2),
        ($$`i < dizi.length`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);
