-- Promotion batch
-- Topic: nested-loops (language: en x5, tr x5)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 5 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/nested-loops.md and content/tr/nested-loops.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (CODE_OUTPUT, BEGINNER)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int count = 0;

for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 4; j++) {
        count++;
    }
}

System.out.println(count);$$, $$java$$,
           $$For each of the outer loop's 3 steps the inner loop runs completely, 4 times, so the body runs 3 × 4 = 12 times. Adding the two counts to get 7 misses that the inner loop starts over on every outer step.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$`12`$$, TRUE, 0),
        ($$`7`$$, FALSE, 1),
        ($$`4`$$, FALSE, 2),
        ($$`3`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (CODE_OUTPUT, BEGINNER)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$for (int satir = 1; satir <= 2; satir++) {
    for (int sutun = 1; sutun <= 3; sutun++) {
        System.out.print(satir * sutun + " ");
    }
    System.out.println();
}$$, $$java$$,
           $$Dış döngünün her adımında iç döngü baştan sona çalışır: `satir` 1 iken `sutun` 1, 2, 3 değerlerini alır ve `1 2 3` yazdırılır; satır sonu basıldıktan sonra `satir` 2 olur ve iç döngü yeniden baştan başlayarak `2 4 6` yazdırır. İç döngü her dış adımda sıfırlandığı için çıktı iki satır, üçer sayıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$İlk satırda `1 2`, ikinci satırda `2 4`, üçüncü satırda `3 6`$$, FALSE, 0),
        ($$Tek satırda `1 2 3 2 4 6`$$, FALSE, 1),
        ($$İlk satırda `1 2 3`, ikinci satırda `2 4 6`$$, TRUE, 2),
        ($$İlk satırda `1 2 3`, ikinci satırda `4 5 6`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int[][] matrix = {{1, 2, 3}, {4, 5}};
int total = 0;

for (int row = 0; row < matrix.length; row++) {
    for (int col = 0; col < matrix[row].length; col++) {
        total += matrix[row][col];
    }
}

System.out.println(total);$$, $$java$$,
           $$The outer loop walks the 2 rows and the inner loop walks each row's own columns, because its bound is `matrix[row].length`: 3 for the first row and 2 for the second. Every value is added once, giving 15. Using a fixed column count instead would read past the end of the shorter row.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$`6`$$, FALSE, 0),
        ($$`15`$$, TRUE, 1),
        ($$`12`$$, FALSE, 2),
        ($$`9`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int[][] tablo = {{1, 2, 3}, {4, 5}};

System.out.println(tablo.length);
System.out.println(tablo[1].length);$$, $$java$$,
           $$`tablo.length` satır sayısını verir: 2. `tablo[1].length` ise ikinci satırın kendi uzunluğudur ve o satırda iki eleman vardır. Satırlar farklı uzunlukta olabildiği için iç döngünün sınırı sabit bir sayı ya da ilk satırın uzunluğu değil, her satırın kendi `length` değeri olmalıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$`2`, sonra `3`$$, FALSE, 0),
        ($$`5`, sonra `2`$$, FALSE, 1),
        ($$`3`, sonra `2`$$, FALSE, 2),
        ($$`2`, sonra `2`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$for (int row = 1; row <= 2; row++) {
    for (int col = 1; col <= 3; col++) {
        if (col == 2) {
            break;
        }
        System.out.println(row + "-" + col);
    }
}$$, $$java$$,
           $$An unlabeled `break` ends only the innermost loop it is written in. On each row the inner loop prints column 1 and is cut off at column 2, but the outer loop carries on, so the second row is processed as well. Stopping after `1-1` would require a labeled `break` aimed at the outer loop.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$`1-1`$$, FALSE, 0),
        ($$`1-1`, `1-3`, `2-1`, then `2-3`$$, FALSE, 1),
        ($$`1-1`, then `2-1`$$, TRUE, 2),
        ($$`1-1`, `1-2`, `2-1`, then `2-2`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$for (int i = 1; i <= 2; i++) {
    for (int j = 1; j <= 3; j++) {
        if (j == 2) {
            continue;
        }
        System.out.println(i + "" + j);
    }
}$$, $$java$$,
           $$Etiketsiz `continue` yalnızca yazıldığı iç döngünün o adımını atlar. `j` 2 olduğunda yazdırma atlanır, ama iç döngü 3 ile sürer; dış döngü de hiçbir adımını atlamadan iki kez çalışır. `j` 2'ye gelince iç döngünün tamamen bitmesi `break`'in davranışı olurdu.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$`11`, `13`, `21`, sonra `23`$$, TRUE, 0),
        ($$`11`, sonra `21`$$, FALSE, 1),
        ($$`11`, sonra `13`$$, FALSE, 2),
        ($$`11`, `12`, `13`, `21`, `22`, sonra `23`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Inside the inner loop of two nested loops, a search finds its match and must stop both loops at once. Which statement does that?$$,
           NULL, NULL,
           $$A label placed before the outer loop lets `break` name the loop it should end, so `break searchLoop;` leaves the inner and the outer loop together. A plain `break` would stop only the inner loop and the outer one would keep searching. A labeled `continue` does not stop anything; it moves on to the outer loop's next step.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$A plain `break;`$$, FALSE, 0),
        ($$`continue` with the outer loop's label$$, FALSE, 1),
        ($$Two `break;` statements, one after the other$$, FALSE, 2),
        ($$`break` with the outer loop's label, such as `break searchLoop;`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$İç döngüde yazılmış `continue satirDongusu;` ifadesi ne yapar? (`satirDongusu` dış döngünün etiketidir.)$$,
           NULL, NULL,
           $$Etiketli `continue`, iç döngünün kalanını bırakıp doğrudan dış döngünün bir sonraki adımına atlar. Döngüleri sonlandırmaz; ikisini birden bitiren etiketli `break`'tir. Etiketsiz `continue` ise yalnızca iç döngünün o adımını atlar ve iç döngü kaldığı yerden sürer.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Hem iç hem dış döngüyü tamamen sonlandırır$$, FALSE, 0),
        ($$İç döngünün kalanını bırakıp dış döngünün bir sonraki adımına geçer$$, TRUE, 1),
        ($$Yalnızca iç döngünün o adımını atlar; iç döngü sürer$$, FALSE, 2),
        ($$Dış döngüyü ilk adımından yeniden başlatır$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Two nested loops each run over the same `n` elements. When `n` grows from 10 to 100, how does the number of times the inner body runs change?$$,
           NULL, NULL,
           $$The body runs `n × n` times: 100 times for `n` equal to 10, and 10,000 times for `n` equal to 100. A tenfold increase in the data therefore means a hundredfold increase in work. Growth in step with `n` is what a single loop would give, not two nested ones.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$From 100 to 10,000: a hundredfold increase$$, TRUE, 0),
        ($$From 10 to 100: a tenfold increase$$, FALSE, 1),
        ($$From 20 to 200: a tenfold increase$$, FALSE, 2),
        ($$From 100 to 1,000: a tenfold increase$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`n` elemanlı bir veri üzerinde aynı boyutta iki iç içe döngü çalışıyor. `n` iki katına çıkarsa gövdenin çalışma sayısı nasıl değişir?$$,
           NULL, NULL,
           $$Gövde `n × n` kez çalışır. `n` iki katına çıkınca bu sayı (2n) × (2n), yani dört katı olur. İki katına çıkmak tek bir döngünün davranışıdır; iç içe döngülerde artış doğrusal değil kareseldir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'nested-loops'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$İki katına çıkar$$, FALSE, 0),
        ($$Üç katına çıkar$$, FALSE, 1),
        ($$Dört katına çıkar$$, TRUE, 2),
        ($$Sekiz katına çıkar$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);
