-- Promotion batch
-- Topic: while-do-while (language: en x5, tr x5)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 5 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/while-do-while.md and content/tr/while-do-while.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$When is `while` a better fit than `for`?$$,
           NULL, NULL,
           $$`for` bundles initialization, condition and increment because those usually belong to a counter. When the repetition is about a state, such as retrying until a connection succeeds, there is only a condition, and `while` expresses that directly. A known number of iterations is exactly the case `for` was made for.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$When the repetition depends on a state or condition rather than on a counter$$, TRUE, 0),
        ($$When the number of iterations is known in advance$$, FALSE, 1),
        ($$When the loop needs `break` or `continue` in its body$$, FALSE, 2),
        ($$When the body has to run at least once$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdaki işlerden hangisi `for` yerine `while` ile daha doğal ifade edilir?$$,
           NULL, NULL,
           $$Bir bağlantı başarılı olana kadar yeniden denemek bir sayaca değil bir duruma bağlıdır: kaç adım süreceği bilinmez, yalnızca ne zaman duracağı bilinir. `while` tam olarak bu "yalnızca bir koşulum var" durumu içindir. Diğer üç iş adım sayısı belli olan, sayaçla yürüyen tekrarlar olduğu için `for`'a uygundur.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$Bir işlemi tam 10 kez tekrarlamak$$, FALSE, 0),
        ($$Bir dizinin elemanlarını indeksleriyle sırayla gezmek$$, FALSE, 1),
        ($$Bir bağlantı başarılı olana kadar yeniden denemek$$, TRUE, 2),
        ($$1'den 100'e kadar olan sayıları toplamak$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (CODE_OUTPUT, BEGINNER)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int n = 10;
int steps = 0;

while (n > 1) {
    n = n / 2;
    steps++;
}

System.out.println(steps);$$, $$java$$,
           $$The body runs while `n > 1`: integer division takes `n` from 10 to 5, then to 2, then to 1, counting three steps. With `n` equal to 1 the condition is `false` and the loop stops. A fourth step would need the condition to be checked after the body, which is how `do-while` works, not `while`.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$`2`$$, FALSE, 0),
        ($$`3`$$, TRUE, 1),
        ($$`4`$$, FALSE, 2),
        ($$`5`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (CODE_OUTPUT, BEGINNER)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int sayac = 3;

while (sayac > 0) {
    System.out.println(sayac);
    sayac--;
}

System.out.println("Kalkış");$$, $$java$$,
           $$Koşul her adımdan önce kontrol edilir. `sayac` 3, 2 ve 1 iken koşul doğrudur ve değer yazdırılır; 0 olduğunda `sayac > 0` yanlış olur ve gövde bir daha çalışmaz. Bu yüzden 0 yazdırılmaz; döngüden sonra yalnızca `Kalkış` yazdırılır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$`3`, `2`, `1`, `0`, sonra `Kalkış`$$, FALSE, 0),
        ($$`2`, `1`, `0`, sonra `Kalkış`$$, FALSE, 1),
        ($$Yalnızca `Kalkış`$$, FALSE, 2),
        ($$`3`, `2`, `1`, sonra `Kalkış`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which task is the most natural fit for `do-while` rather than `while`?$$,
           NULL, NULL,
           $$`do-while` checks its condition after the body, so the body always runs at least once. Input validation needs exactly that: the value cannot be checked before it has been read. A queue that may already be empty is the opposite case, where the body should be able to run zero times.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$Processing a queue that may already be empty$$, FALSE, 0),
        ($$Repeating a block exactly ten times$$, FALSE, 1),
        ($$Asking the user for a value until it is valid$$, TRUE, 2),
        ($$Reading every element of an array of known size$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`do-while` döngüsünde koşul en baştan `false` ise ne olur?$$,
           NULL, NULL,
           $$`do-while` koşulu gövdeden sonra kontrol eder; bu yüzden koşul baştan `false` olsa bile gövde bir kez çalışır, ardından koşul kontrol edilir ve döngü biter. Gövdenin hiç çalışmaması, koşulu gövdeden önce kontrol eden `while`'ın davranışıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$Gövde bir kez çalışır, sonra döngü biter$$, TRUE, 0),
        ($$Gövde hiç çalışmaz$$, FALSE, 1),
        ($$Gövde, bir `break` ile durdurulana kadar çalışır$$, FALSE, 2),
        ($$Kod derlenmez, çünkü koşul hiçbir zaman `true` olamaz$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$int count = 5;

while (count < 3) {
    System.out.println("while: " + count);
    count++;
}

do {
    System.out.println("do-while: " + count);
    count++;
} while (count < 3);$$, $$java$$,
           $$`count < 3` is `false` from the start. `while` checks before the body, so its body never runs and `count` stays 5. `do-while` checks after the body, so its body runs once and prints `do-while: 5` before the condition ends the loop. That zero-times versus one-time difference is the only thing separating the two loops.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$`while: 5`, then `do-while: 6`$$, FALSE, 0),
        ($$`while: 5`$$, FALSE, 1),
        ($$Nothing is printed$$, FALSE, 2),
        ($$`do-while: 5`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$int kalan = 0;

do {
    System.out.println("Deneme");
    kalan--;
} while (kalan > 0);

System.out.println("Bitti");$$, $$java$$,
           $$`kalan > 0` baştan yanlıştır, ama `do-while` koşulu gövdeden sonra kontrol ettiği için `Deneme` bir kez yazdırılır. Ardından koşul yanlış çıkar, döngü biter ve `Bitti` yazdırılır. Aynı döngü `while` ile yazılsaydı gövde hiç çalışmaz, yalnızca `Bitti` yazdırılırdı.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Yalnızca `Bitti`$$, FALSE, 0),
        ($$`Deneme`, sonra `Bitti`$$, TRUE, 1),
        ($$`Deneme`, `Deneme`, sonra `Bitti`$$, FALSE, 2),
        ($$`Deneme` durmadan yazdırılır$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Which of these are real mistakes when writing `while` and `do-while` loops? (Select all that apply)$$,
           NULL, NULL,
           $$If nothing in the body updates the variable the condition depends on, the condition never changes and the loop runs forever. A `do-while` must end with `} while (condition);`, and leaving out that `;` is a compile error. Using `break`, or writing a `while` whose body may run zero times, are both normal and often exactly what is intended.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$Never updating the variable the condition depends on$$, TRUE, 0),
        ($$Ending a `while` loop early with `break`$$, FALSE, 1),
        ($$Leaving out the `;` after `while (condition)` at the end of a `do-while`$$, TRUE, 2),
        ($$Writing a `while` whose body may run zero times$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdakilerden hangileri bir derleme hatasına ya da istenmeyen bir sonsuz döngüye yol açar? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$`do-while`'ın kapanış satırı `} while (kosul);` biçimindedir; sondaki `;` yazılmazsa kod derlenmez. Koşulun bağlı olduğu değişken gövdede hiç güncellenmezse koşul değişmez ve döngü bitmez. Koşulu baştan `false` olan bir `while` ise yalnızca gövdesini hiç çalıştırmaz; `break` ile erken çıkmak da geçerli bir kullanımdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'while-do-while'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$Koşulu en baştan `false` olan bir `while` yazmak$$, FALSE, 0),
        ($$Bir `while` döngüsünü `break` ile erken bitirmek$$, FALSE, 1),
        ($$`do-while`'ın sonundaki `while (kosul)` ifadesinden sonra `;` yazmamak$$, TRUE, 2),
        ($$Koşulun bağlı olduğu değişkeni gövdede hiç güncellememek$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);
