-- Promotion batch
-- Topic: what-is-react (language: en x5, tr x5)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 5 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/what-is-react.md and content/tr/what-is-react.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$On an e-commerce page, the product card, the cart icon and the search box are each built as a separate, reusable piece and then combined. What does React call these pieces?$$,
           NULL, NULL,
           $$React splits a page into small, reusable pieces called components and builds the whole page by combining them. A framework is a different idea altogether: a complete structure you work inside, not a piece of a page.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$Components$$, TRUE, 0),
        ($$Frameworks$$, FALSE, 1),
        ($$Libraries$$, FALSE, 2),
        ($$Applications$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$React'te bir web sayfası nasıl oluşturulur?$$,
           NULL, NULL,
           $$React'te sayfa, component adı verilen küçük ve yeniden kullanılabilir parçalara bölünür; bütün sayfa bu parçaların birleştirilmesiyle kurulur. Arayüzün tek parça hâlinde yazılması, React'in çözmeye çalıştığı durumun kendisidir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$Tüm arayüz tek bir büyük dosyada, tek parça yazılarak$$, FALSE, 0),
        ($$Her sayfa için ayrı bir HTML dosyası elle hazırlanarak$$, FALSE, 1),
        ($$Küçük, yeniden kullanılabilir component'ler birleştirilerek$$, TRUE, 2),
        ($$Sayfa her tıklamada sunucuda baştan üretilerek$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$How does updating the UI change when you use React?$$,
           NULL, NULL,
           $$With React you describe what the UI should look like for the current data. When the data changes, React updates the UI to match. Finding the right element in the DOM and changing it yourself is the manual approach that React replaces.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$You find each element in the DOM and change it by hand$$, FALSE, 0),
        ($$You change the data, and React updates the UI to match$$, TRUE, 1),
        ($$You reload the page whenever the data changes$$, FALSE, 2),
        ($$You rewrite the page's HTML after every change$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$React'ten önce, sayfadaki bir sayacı artırmak genellikle ne gerektiriyordu?$$,
           NULL, NULL,
           $$React'ten önce DOM'a elle dokunmak gerekiyordu: doğru elementi bulan ve onu değiştiren kodu geliştirici kendisi yazardı, sayfa büyüdükçe de bunu takip etmek zorlaşırdı. Yalnızca veriyi değiştirip arayüzün kendiliğinden güncellenmesi, React'in getirdiği yaklaşımdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$Yalnızca veriyi değiştirmeyi; arayüz kendiliğinden güncellenirdi$$, FALSE, 0),
        ($$Sayacı ayrı bir component olarak tanımlamayı$$, FALSE, 1),
        ($$Sayfanın tamamını sunucudan yeniden istemeyi$$, FALSE, 2),
        ($$Doğru elementi bulup onu elle değiştiren kodu yazmayı$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$React describes itself as a library rather than a framework. What follows from that in practice?$$,
           NULL, NULL,
           $$A library focuses on one question, here how to build the UI. For other needs such as routing or form handling you pick and add separate libraries, for example React Router. Having all of that built in, under the tool's own rules, is what defines a framework such as Angular.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$Routing, form handling and HTTP requests all come built in$$, FALSE, 0),
        ($$It can only build small parts of a page, never a whole application$$, FALSE, 1),
        ($$For needs such as routing, you choose and add separate libraries yourself$$, TRUE, 2),
        ($$It has to be combined with a framework such as Angular$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Angular gibi bir framework'ü, React gibi bir library'den ayıran nedir?$$,
           NULL, NULL,
           $$Bir framework routing, form yönetimi, HTTP istekleri gibi pek çok şeyi kendi kurallarıyla hazır sunar ve onun yapısı içinde çalışılır. Yalnızca arayüzün nasıl kurulacağına odaklanmak ise library'nin, yani React'in tanımıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$Routing ve form yönetimi gibi pek çok şeyi kendi kurallarıyla hazır sunması$$, TRUE, 0),
        ($$Yalnızca arayüzün nasıl kurulacağı sorusuna odaklanması$$, FALSE, 1),
        ($$Ek ihtiyaçlar için ayrı kütüphanelerin seçilip eklenmesini gerektirmesi$$, FALSE, 2),
        ($$Yalnızca mobil uygulama geliştirmek için kullanılabilmesi$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In a single page application, what happens when the user clicks a link?$$,
           NULL, NULL,
           $$The browser does not reload the whole page from scratch. JavaScript updates only the part that needs to change, which is why there is no brief white flash between pages. A full reload from the server is the traditional behavior that an SPA avoids.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$The browser reloads the entire page from the server$$, FALSE, 0),
        ($$The new page opens in a separate browser tab$$, FALSE, 1),
        ($$The application starts again from its first screen$$, FALSE, 2),
        ($$JavaScript updates only the part of the page that needs to change$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bir SPA'nın kullanıcıya daha hızlı ve akıcı gelmesinin sebebi nedir?$$,
           NULL, NULL,
           $$SPA'da bir bağlantıya tıklandığında tarayıcı sayfayı baştan yüklemez; JavaScript yalnızca değişmesi gereken kısmı günceller. Bu yüzden sayfalar arasında kısa süreli beyaz "yeniden yükleniyor" görüntüsü oluşmaz.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Tüm sayfalar baştan itibaren aynı anda ekranda durur$$, FALSE, 0),
        ($$Tıklamada sayfanın tamamı değil, yalnızca değişen kısmı güncellenir$$, TRUE, 1),
        ($$Her tıklamada sayfa sunucudan daha hızlı yeniden indirilir$$, FALSE, 2),
        ($$Uygulama internet bağlantısına hiç ihtiyaç duymaz$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (MULTIPLE_CHOICE, BEGINNER)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Besides websites, where are React's core ideas used? (Select all that apply)$$,
           NULL, NULL,
           $$The same ideas power mobile apps through React Native and desktop apps through tools such as Electron. React Router is a routing library for web apps, and Angular is a separate framework rather than a way of running React somewhere else.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$Mobile apps, with React Native$$, TRUE, 0),
        ($$Mobile apps, with React Router$$, FALSE, 1),
        ($$Desktop apps, with tools such as Electron$$, TRUE, 2),
        ($$Desktop apps, with Angular$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (MULTIPLE_CHOICE, BEGINNER)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdaki eşleştirmelerden hangileri doğrudur? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$React'in temel fikirleri iOS/Android uygulamalarında React Native ile, masaüstü uygulamalarında Electron gibi araçlarla kullanılır. React Router web uygulamaları için bir routing kütüphanesidir; Angular ise React'i başka bir ortamda çalıştıran bir araç değil, ayrı bir framework'tür.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'what-is-react'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$Mobil uygulamalar: React Router$$, FALSE, 0),
        ($$Masaüstü uygulamaları: Angular$$, FALSE, 1),
        ($$Mobil uygulamalar: React Native$$, TRUE, 2),
        ($$Masaüstü uygulamaları: Electron gibi araçlar$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);
