-- Promotion batch
-- Topic: threads (language: en x7, tr x7)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 7 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/threads.md and content/tr/threads.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$public class Demo {
    public static void main(String[] args) throws InterruptedException {
        Thread worker = new Thread(() -> { });

        System.out.println(worker.getState());

        worker.start();
        worker.join();

        System.out.println(worker.getState());
    }
}$$, $$java$$,
           $$Before `start()` is called the thread object exists but has not begun, so its state is `NEW`. `join()` makes the main thread wait until `run()` has finished, and a thread whose `run()` has finished is `TERMINATED`. `RUNNABLE` would be seen only while the thread is still running or waiting for the CPU.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$`NEW`, then `TERMINATED`$$, TRUE, 0),
        ($$`NEW`, then `RUNNABLE`$$, FALSE, 1),
        ($$`RUNNABLE`, then `TERMINATED`$$, FALSE, 2),
        ($$`NEW`, then `WAITING`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$Thread isci = new Thread(() -> System.out.println("çalışıyor"));

System.out.println(isci.getState());$$, $$java$$,
           $$`Thread` nesnesi oluşturulmuş ama `start()` hiç çağrılmamıştır; bu durumda thread `NEW` durumundadır ve `run()` içindeki kod çalışmaz. Bu yüzden `çalışıyor` yazdırılmaz. `RUNNABLE` durumu ancak `start()` çağrıldıktan sonra görülür.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$`NEW`, sonra `çalışıyor`$$, FALSE, 0),
        ($$`çalışıyor`, sonra `TERMINATED`$$, FALSE, 1),
        ($$Yalnızca `NEW`$$, TRUE, 2),
        ($$Yalnızca `RUNNABLE`$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What does this code print?$$,
           $$Thread worker = new Thread(() ->
        System.out.println(Thread.currentThread().getName()));

worker.run();$$, $$java$$,
           $$Calling `run()` directly does not start a new thread; it is an ordinary method call that executes on the calling thread, which here is `main`. Only `start()` launches a new thread, and the name printed would then be that thread's own name instead.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$`Thread-0`$$, FALSE, 0),
        ($$`main`$$, TRUE, 1),
        ($$`main`, then `Thread-0`$$, FALSE, 2),
        ($$Nothing, because a thread that was never started cannot run$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (CODE_OUTPUT, INTERMEDIATE)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Bu kod ne yazdırır?$$,
           $$public class Demo {
    public static void main(String[] args) throws InterruptedException {
        Thread isci = new Thread(() -> System.out.println("işçi bitti"));

        isci.start();
        isci.join();

        System.out.println("main bitti");
    }
}$$, $$java$$,
           $$`join()`, çağıran thread'i (burada main) hedef thread tamamen bitene kadar bekletir. Bu yüzden `main bitti` satırı her zaman `işçi bitti`'den sonra yazdırılır. `join()` olmasaydı sıra işletim sisteminin zamanlayıcısına kalırdı ve garanti edilemezdi.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$`main bitti`, sonra `işçi bitti`$$, FALSE, 0),
        ($$İki satır da yazdırılır, ama sıraları her çalıştırmada değişebilir$$, FALSE, 1),
        ($$Yalnızca `main bitti`$$, FALSE, 2),
        ($$`işçi bitti`, sonra `main bitti`$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (SINGLE_CHOICE, ADVANCED)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Two threads each run `counter++` 100,000 times on the same unprotected `int`. Why can the final value be less than 200,000?$$,
           NULL, NULL,
           $$`counter++` looks like one operation but is three: read the value, increment it, write it back. When two threads interleave those steps, one thread writes a result based on a stale read and the other's increment is lost. Both threads really do share the same variable; that sharing is precisely what makes the lost updates possible.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$Each thread increments its own private copy of `counter`, and only one copy survives$$, FALSE, 0),
        ($$The second thread can start counting only after the first one has finished$$, FALSE, 1),
        ($$`counter++` is three separate steps, and interleaved steps overwrite each other's updates$$, TRUE, 2),
        ($$An `int` loses precision once two threads have written to it$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (SINGLE_CHOICE, ADVANCED)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdaki durumlardan hangisi bir race condition'a yol açar?$$,
           NULL, NULL,
           $$Race condition, birden fazla thread aynı paylaşılan durumu korumasız değiştirdiğinde ortaya çıkar; sonuç her çalıştırmada farklı ve yanlış olabilir. Yalnızca kendi yerel değişkenleriyle çalışan thread'ler ortak bir şeyi değiştirmediği için böyle bir risk taşımaz; `join()` ve `sleep()` de tek başına paylaşılan veriyi bozmaz.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$İki thread'in aynı paylaşılan değişkeni korumasız biçimde değiştirmesi$$, TRUE, 0),
        ($$İki thread'in yalnızca kendi yerel değişkenleriyle çalışması$$, FALSE, 1),
        ($$Bir thread'in `join()` ile diğerinin bitmesini beklemesi$$, FALSE, 2),
        ($$Bir thread'in `sleep()` ile bir süre duraklaması$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (MULTIPLE_CHOICE, ADVANCED)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Which of these statements about `volatile` are true? (Select all that apply)$$,
           NULL, NULL,
           $$`volatile` solves a visibility problem: every read and write goes to main memory, so one thread's change cannot stay hidden from the others. It does not make anything atomic, so `counter++` on a `volatile int` is still the same three-step race. It involves no lock either, so it does not restrict how many threads access the variable.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$It guarantees that a value written by one thread becomes visible to the others$$, TRUE, 0),
        ($$It makes compound operations such as `counter++` atomic$$, FALSE, 1),
        ($$It lets only one thread at a time access the variable$$, FALSE, 2),
        ($$`counter++` on a `volatile int` is still a race condition$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (MULTIPLE_CHOICE, ADVANCED)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$`volatile` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$`volatile` yalnızca görünürlüğü garanti eder: bir thread'in yazdığı değer, örneğin bir durdurma bayrağı, diğer thread'lerce görülür. Atomiklik sağlamaz ve bir kilit de içermez; bu yüzden birden fazla adımdan oluşan işlemlerde `synchronized`'ın yerini tutmaz, okuyan thread'i de bekletmez.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Yalnızca görünürlüğü garanti eder, atomikliği garanti etmez$$, TRUE, 0),
        ($$Bir thread'in yazdığı durdurma bayrağının diğer thread tarafından görülmesini sağlar$$, TRUE, 1),
        ($$Her durumda `synchronized`'ın yerine kullanılabilir$$, FALSE, 2),
        ($$Değişkeni okuyan thread'i, yazma bitene kadar kilitte bekletir$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (SINGLE_CHOICE, ADVANCED)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Why should `wait()` be called inside a `while` loop rather than a single `if`?$$,
           NULL, NULL,
           $$A thread can wake up without any `notify()` having been called, a so-called spurious wakeup, and even after a real notification the condition may no longer hold. A `while` loop re-checks the condition after every wakeup, whereas an `if` checks it only once and then carries on regardless.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$`wait()` releases the lock only when it is called from inside a loop$$, FALSE, 0),
        ($$A woken thread must re-check the condition, because it can wake without it being true$$, TRUE, 1),
        ($$`notify()` can wake only threads that are waiting inside a loop$$, FALSE, 2),
        ($$A `while` loop keeps the thread from ever entering the waiting state$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (SINGLE_CHOICE, ADVANCED)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$`wait()` ya da `notify()`, bir `synchronized` blok ya da metodun dışında çağrılırsa ne olur?$$,
           NULL, NULL,
           $$İkisi de üzerinde çağrıldıkları nesnenin kilidine (monitor) ihtiyaç duyar; kilit tutulmadan çağrılırlarsa `IllegalMonitorStateException` fırlatılır. Bu bir derleme hatası değildir, kod derlenir ve hata çalışma anında ortaya çıkar; çağrı sessizce yok sayılmaz.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$Kod derlenmez$$, FALSE, 0),
        ($$Çağrı hiçbir etki yapmadan yok sayılır$$, FALSE, 1),
        ($$`IllegalMonitorStateException` fırlatılır$$, TRUE, 2),
        ($$Thread, bir `interrupt()` gelene kadar bekler$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / EN (SINGLE_CHOICE, ADVANCED)
WITH new_question_en6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$When using `ReentrantLock`, why must `unlock()` be called inside a `finally` block?$$,
           NULL, NULL,
           $$`synchronized` releases its lock automatically, but `ReentrantLock` does not. If the code between `lock()` and `unlock()` throws and `unlock()` is not in `finally`, the lock stays held forever and every thread waiting for it blocks. `finally` guarantees the release on both the normal and the exceptional path.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en6
         CROSS JOIN (VALUES
        ($$Otherwise the compiler rejects the call to `unlock()`$$, FALSE, 0),
        ($$Because `finally` makes `unlock()` run before the locked code starts$$, FALSE, 1),
        ($$Otherwise an exception in the locked code would leave the lock held forever$$, TRUE, 2),
        ($$Because the lock is released automatically and `finally` only documents that$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 6 / TR (SINGLE_CHOICE, ADVANCED)
WITH new_question_tr6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$`ReentrantLock`'un `synchronized`'a göre sunduğu ek esneklik hangisidir?$$,
           NULL, NULL,
           $$`tryLock()` ile bir thread kilidi almayı dener; kilit meşgulse sonsuza kadar beklemek yerine hemen vazgeçip başka bir iş yapabilir. `synchronized` bunu yapamaz. Buna karşılık `ReentrantLock` kilidi kendiliğinden bırakmaz; `unlock()`'un `finally` içinde elle çağrılması gerekir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr6.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr6
         CROSS JOIN (VALUES
        ($$Kilidin, `unlock()` çağrılmasa da kendiliğinden bırakılması$$, FALSE, 0),
        ($$Aynı anda birden fazla thread'in kilitli bölgeye girebilmesi$$, FALSE, 1),
        ($$Kilitlerin her zaman aynı sırayla alınmasını kendiliğinden sağlaması$$, FALSE, 2),
        ($$`tryLock()` ile kilidi almayı deneyip, meşgulse beklemeden vazgeçebilmek$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 7 / EN (SINGLE_CHOICE, ADVANCED)
WITH new_question_en7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Thread A holds `lockA` and waits for `lockB`, while thread B holds `lockB` and waits for `lockA`. What is the most common way to prevent this situation?$$,
           NULL, NULL,
           $$The deadlock exists only because the two threads take the locks in opposite orders. If every thread always acquires them in the same order, one of them gets both and the other simply waits its turn. `volatile` concerns visibility and has no effect on locking, and a pause between the two acquisitions only changes the timing.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en7.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en7
         CROSS JOIN (VALUES
        ($$Declare both lock objects as `volatile`$$, FALSE, 0),
        ($$Pause with `Thread.sleep()` between acquiring the two locks$$, FALSE, 1),
        ($$Mark one of the two threads as a daemon thread$$, FALSE, 2),
        ($$Make every thread acquire the locks in the same order$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 7 / TR (SINGLE_CHOICE, ADVANCED)
WITH new_question_tr7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdakilerden hangisi bir deadlock'u tanımlar?$$,
           NULL, NULL,
           $$Deadlock'ta iki ya da daha fazla thread, her biri diğerinin tuttuğu kilidi bekleyerek birbirini sonsuza kadar engeller ve hiçbiri ilerleyemez. Bir güncellemenin kaybolması race condition'dır; `sleep()` sırasında `interrupt()` ile uyanmak ise bir iptal isteğinin normal biçimde ulaşmasıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'threads'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr7.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr7
         CROSS JOIN (VALUES
        ($$İki thread'in aynı değişkeni korumasız değiştirmesi sonucu bir güncellemenin kaybolması$$, FALSE, 0),
        ($$İki thread'in, her biri diğerinin tuttuğu kilidi bekleyerek birbirini sonsuza kadar engellemesi$$, TRUE, 1),
        ($$`sleep()` içindeki bir thread'in `interrupt()` ile uyandırılması$$, FALSE, 2),
        ($$Tüm kullanıcı thread'leri bitince JVM'in daemon thread'leri beklemeden kapanması$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);
