-- Promotion batch
-- Topic: build-deployment (language: en x5, tr x5)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 5 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/build-deployment.md and content/tr/build-deployment.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$What is needed to serve the `dist/` folder that `npm run build` produces?$$,
           NULL, NULL,
           $$The build output is plain static `.html`, `.js` and `.css` files. Any static file server can serve them, with no backend, no React and not even Node.js running. The Vite development server is the tool for development, not for serving the build.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$Any static file server; no backend or Node.js is needed$$, TRUE, 0),
        ($$A running Node.js process that executes React$$, FALSE, 1),
        ($$The Vite development server started by `npm run dev`$$, FALSE, 2),
        ($$A backend server that renders each page on request$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`npm run build` çalıştırıldığında ne olur?$$,
           NULL, NULL,
           $$Build, kodu küçültür, gereksiz olanı atar ve statik `.html`/`.js`/`.css` dosyalarını `dist/` klasörüne yazar; deploy edilen şey tam olarak bu klasördür. Kodun her değişiklikte tarayıcıya anında gönderilmesi ise `npm run dev`'in geliştirme sırasındaki davranışıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$Kod, her değişiklikte tarayıcıya anında yeniden gönderilir$$, FALSE, 0),
        ($$Proje kendiliğinden yayınlanır ve canlı bir adres üretilir$$, FALSE, 1),
        ($$Kod küçültülür ve statik dosyalar `dist/` klasörüne yazılır$$, TRUE, 2),
        ($$`.env` dosyasındaki değerler git deposuna eklenir$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$A `.env` file contains `API_SECRET=abc123`, without the `VITE_` prefix. What happens to this variable in the built client code?$$,
           NULL, NULL,
           $$Vite bakes only variables prefixed with `VITE_` into the code at build time. Anything without the prefix is never bundled into the client at all, a deliberate choice that keeps a secret key from leaking into browser code. The build itself succeeds.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$It is bundled just like a `VITE_` variable$$, FALSE, 0),
        ($$It is not bundled into the client code at all$$, TRUE, 1),
        ($$It is bundled, but only for development builds$$, FALSE, 2),
        ($$It makes `npm run build` fail with an error$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Vite, ortam değişkenlerini istemci koduna nasıl yerleştirir?$$,
           NULL, NULL,
           $$Vite, `VITE_` ön ekiyle başlayan değişkenleri build sırasında koda gömer. Ön eki olmayanlar istemci koduna hiç girmez; bu, gizli bir anahtarın yanlışlıkla tarayıcı koduna sızmasını önleyen bilinçli bir tercihtir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$Build sırasında; `.env` dosyasındaki tüm değişkenleri$$, FALSE, 0),
        ($$Sayfa her açıldığında sunucudan okuyarak; tüm değişkenleri$$, FALSE, 1),
        ($$Yalnızca `npm run dev` çalışırken; ön eki olmayanları$$, FALSE, 2),
        ($$Build sırasında; yalnızca `VITE_` ön ekiyle başlayanları$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`.env` sets `VITE_SHOW_BANNER=false`, and the code checks `if (import.meta.env.VITE_SHOW_BANNER)`. Why is the banner still shown?$$,
           NULL, NULL,
           $$Every value in `import.meta.env` is a string. The string `"false"` is not empty, so it is truthy and the condition passes. A flag therefore has to be compared explicitly, with `=== "true"`.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$Variables whose value is `false` are dropped during the build$$, FALSE, 0),
        ($$`import.meta.env` can only be read while the app is loading$$, FALSE, 1),
        ($$Every value there is a string, and the string `"false"` is truthy$$, TRUE, 2),
        ($$The check runs before the `.env` file has been read$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$`import.meta.env` içinden okunan bir feature flag'in açık olup olmadığı nasıl kontrol edilmelidir?$$,
           NULL, NULL,
           $$`import.meta.env` içindeki her değer bir string'dir; `"false"` bile boş olmayan bir string olduğu için truthy sayılır. Bu yüzden değer `=== "true"` ile açıkça karşılaştırılmalıdır; doğrudan `if` içine yazmak kapalı bir bayrağı da açık gösterir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$`=== "true"` ile açıkça karşılaştırılarak, çünkü tüm değerler string'dir$$, TRUE, 0),
        ($$Doğrudan `if` içine yazılarak, çünkü değerler boolean olarak gelir$$, FALSE, 1),
        ($$`=== true` ile karşılaştırılarak, çünkü Vite değerleri boolean'a çevirir$$, FALSE, 2),
        ($$`!== undefined` ile karşılaştırılarak, çünkü kapalı bayraklar tanımsızdır$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (SINGLE_CHOICE, BEGINNER)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$How do other developers usually learn which environment variables a project needs?$$,
           NULL, NULL,
           $$A `.env.example` file is committed. It names the variables that are needed without containing real values, and each developer copies it into their own `.env`. The real `.env` stays out of git, usually through `.gitignore`.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$The real `.env` file is committed to git$$, FALSE, 0),
        ($$The values are written into `package.json`$$, FALSE, 1),
        ($$The values are copied into the `dist/` folder$$, FALSE, 2),
        ($$A `.env.example` file without real values is committed$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (SINGLE_CHOICE, BEGINNER)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`.env` dosyaları neden genellikle git'e eklenmez?$$,
           NULL, NULL,
           $$Gerçek değerler kişiye ya da ortama özel olabilir; bu yüzden `.env` dosyası `.gitignore`'a eklenir. Onun yerine hangi değişkenlerin gerektiğini gerçek değerler olmadan gösteren bir `.env.example` commit edilir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Git, adı nokta ile başlayan dosyaları saklayamadığı için$$, FALSE, 0),
        ($$Gerçek değerler kişiye ya da ortama özel olabildiği için$$, TRUE, 1),
        ($$Vite bu dosyayı her build'de sildiği için$$, FALSE, 2),
        ($$Dosya yalnızca production ortamında okunduğu için$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Once a Vite project is connected to Vercel, which of these happen automatically? (Select all that apply)$$,
           NULL, NULL,
           $$Every push to `main` triggers a new production deployment, and every Pull Request gets its own preview deployment, so a change can be seen live before merging. Your environment variables are not picked up from a local file; you add them yourself. For a monorepo you also set the project folder yourself.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$Every push to `main` triggers a new production deployment$$, TRUE, 0),
        ($$The variables from your local `.env` file are uploaded$$, FALSE, 1),
        ($$Every Pull Request gets its own preview deployment$$, TRUE, 2),
        ($$The right project folder of a monorepo is selected$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (MULTIPLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Vercel, bir Vite projesi için aşağıdakilerden hangilerini kendiliğinden doğru ayarlar? (Uygun olan tüm seçenekleri işaretleyin)$$,
           NULL, NULL,
           $$Vercel Vite projelerini otomatik tanır; build komutu (`npm run build`) ve çıktı klasörü (`dist`) senin için doğru ayarlanır. Ortam değişkenlerini ise kendin eklemen gerekir; monorepo'da ilgili proje klasörünü de sen belirtirsin.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'build-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$`.env` dosyandaki ortam değişkenlerini$$, FALSE, 0),
        ($$Monorepo içindeki proje klasörünü$$, FALSE, 1),
        ($$Build komutunu (`npm run build`)$$, TRUE, 2),
        ($$Çıktı klasörünü (`dist`)$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);
