-- Promotion batch
-- Topic: react-spring-boot-deployment (language: en x5, tr x5)
--
-- Generated by .claude/skills/quiz-questions/build_quiz.py from a hand-authored spec:
-- 5 concept pairs, each an EN and an independently written TR question on the
-- same concept, grounded in content/en/react-spring-boot-deployment.md and content/tr/react-spring-boot-deployment.md. Not produced
-- by n8n and not ingested via /api/internal/questions/ingest, so no dev ids exist.
-- status = 'PUBLISHED', source = 'CLAUDE'. Option order is assigned by the script.

-- Pair 1 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Why is the Spring Boot backend deployed to a different platform than the React app on Vercel?$$,
           NULL, NULL,
           $$Vercel is built for static sites and short-lived serverless functions. Spring Boot needs a continuously running Java server process with embedded Tomcat, which Vercel cannot host. The usual pattern is therefore React on Vercel and the backend on a platform made for long-running servers.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en1
         CROSS JOIN (VALUES
        ($$Vercel cannot host the continuously running Java process Spring Boot needs$$, TRUE, 0),
        ($$Vercel does not let a frontend send requests to any backend$$, FALSE, 1),
        ($$A Spring Boot application cannot return JSON to a React app$$, FALSE, 2),
        ($$A frontend and its backend are never allowed to share a platform$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 1 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Vercel hangi tür uygulamalar için tasarlanmıştır?$$,
           NULL, NULL,
           $$Vercel statik siteler ve kısa ömürlü serverless fonksiyonlar için tasarlanmıştır. Spring Boot'un ihtiyaç duyduğu, gömülü Tomcat ile sürekli çalışan Java sunucu sürecini barındıramaz; bu yüzden backend uzun süre çalışan sunucular için kurulmuş ayrı bir platforma deploy edilir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr1.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr1
         CROSS JOIN (VALUES
        ($$Sürekli çalışan Java sunucu süreçleri için$$, FALSE, 0),
        ($$Gömülü Tomcat ile çalışan Spring Boot uygulamaları için$$, FALSE, 1),
        ($$Statik siteler ve kısa ömürlü serverless fonksiyonlar için$$, TRUE, 2),
        ($$Uzun süre açık kalan veritabanı sunucuları için$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$The backend address is read from `VITE_API_BASE_URL`. What differs between local development and production?$$,
           NULL, NULL,
           $$Only the value of the variable differs: locally it points at Spring Boot on `localhost:8080`, and in production at the real address the hosting platform gives you. The code that reads the variable and calls the backend never changes.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en2
         CROSS JOIN (VALUES
        ($$The `fetch` calls are rewritten for production$$, FALSE, 0),
        ($$Only the variable's value; the code stays the same$$, TRUE, 1),
        ($$A different component is rendered in production$$, FALSE, 2),
        ($$The variable gets a different name on Vercel$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 2 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Yerel geliştirme sırasında `VITE_API_BASE_URL` neyi gösterir?$$,
           NULL, NULL,
           $$Yerelde bu değişken `localhost:8080`'de çalışan Spring Boot uygulamasını gösterir. Production'da ise Vercel'in ortam değişkenlerinde, Render'ın verdiği gerçek adresi gösterir; kod iki durumda da aynıdır.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr2.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr2
         CROSS JOIN (VALUES
        ($$Render'ın verdiği gerçek backend adresini$$, FALSE, 0),
        ($$Vercel'in verdiği frontend adresini$$, FALSE, 1),
        ($$`dist/` klasöründeki statik dosyaları$$, FALSE, 2),
        ($$`localhost:8080`'de çalışan Spring Boot uygulamasını$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$A component that talked to `json-server` during development now talks to a deployed Spring Boot app. What has to change in its `useEffect` + `fetch` logic?$$,
           NULL, NULL,
           $$Nothing has to change. All `fetch` sees is a URL and a JSON response, so the component behaves the same whatever sits at the other end. The loading and error handling stays exactly as it was.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en3
         CROSS JOIN (VALUES
        ($$The loading and error states must be removed$$, FALSE, 0),
        ($$`fetch` must be replaced by a Spring-specific client$$, FALSE, 1),
        ($$Nothing; `fetch` only sees a URL and a JSON response$$, TRUE, 2),
        ($$The response must be converted from XML to JSON$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 3 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Deploy edilmiş bir Spring Boot backend'inden veri çeken component hangi kalıbı kullanır?$$,
           NULL, NULL,
           $$Daha önce görülen `useEffect` + `fetch` + yükleniyor/hata kalıbının aynısı kullanılır. Karşı tarafta `json-server` yerine gerçek bir Spring Boot uygulamasının olması component'i etkilemez; `fetch` yalnızca bir URL ve bir JSON yanıtı görür.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr3.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr3
         CROSS JOIN (VALUES
        ($$Daha önce görülen `useEffect` + `fetch` + yükleniyor/hata kalıbının aynısını$$, TRUE, 0),
        ($$Yalnızca production'da çalışan, Vercel'e özel bir kalıbı$$, FALSE, 1),
        ($$`fetch` yerine veritabanına doğrudan bağlanan bir kalıbı$$, FALSE, 2),
        ($$Her istekten önce sayfayı baştan yükleyen bir kalıbı$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / EN (SINGLE_CHOICE, ADVANCED)
WITH new_question_en4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$`CORS_ALLOWED_ORIGIN` is set to `https://my-app.vercel.app/`, with a trailing slash. What happens to requests from the deployed frontend?$$,
           NULL, NULL,
           $$The origin has to match exactly, including `https://` and with no trailing `/`. With the extra slash it does not match, and the browser blocks the request with a CORS error. Nothing about this depends on the HTTP method.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en4
         CROSS JOIN (VALUES
        ($$They succeed, since a trailing slash is ignored when origins are compared$$, FALSE, 0),
        ($$They succeed for `GET` requests and fail for all other methods$$, FALSE, 1),
        ($$The backend answers with a 404 before CORS is ever checked$$, FALSE, 2),
        ($$The browser blocks them with a CORS error, since the origin must match exactly$$, TRUE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 4 / TR (SINGLE_CHOICE, ADVANCED)
WITH new_question_tr4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'ADVANCED', 'PUBLISHED', 'CLAUDE',
           $$Gerçek bir deployment'ta backend, izin verdiği origin'i nereden okur?$$,
           NULL, NULL,
           $$İzin verilen origin, `application.properties` üzerinden `CORS_ALLOWED_ORIGIN` ortam değişkeninden gelir. Bu değişkeni Vercel'in verdiği gerçek adresle doldurmak yeterlidir; koda sabit bir domain yazılmaz ve kod değişmez.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr4.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr4
         CROSS JOIN (VALUES
        ($$Koda sabit olarak yazılmış bir domain'den$$, FALSE, 0),
        ($$`CORS_ALLOWED_ORIGIN` ortam değişkeninden; kod değişmez$$, TRUE, 1),
        ($$Tarayıcının her istekte gönderdiği bir başlıktan$$, FALSE, 2),
        ($$Vercel'in kendiliğinden ürettiği bir dosyadan$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / EN (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_en5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$React needs the backend's address, and the backend needs React's address. In which order are they deployed and configured?$$,
           NULL, NULL,
           $$The backend goes first because it produces the URL that React needs in `VITE_API_BASE_URL`. Deploying React then produces the second URL, which goes into `CORS_ALLOWED_ORIGIN` back on the backend. Setting the CORS variable any earlier is impossible, because the frontend's address does not exist yet.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_en5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_en5
         CROSS JOIN (VALUES
        ($$Backend first, then React with the backend URL, then the CORS variable$$, TRUE, 0),
        ($$React first, then the CORS variable, then the backend$$, FALSE, 1),
        ($$The CORS variable first, then both applications together$$, FALSE, 2),
        ($$Backend first, then the CORS variable, then React$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);

-- Pair 5 / TR (SINGLE_CHOICE, INTERMEDIATE)
WITH new_question_tr5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE', 'PUBLISHED', 'CLAUDE',
           $$Backend'deki `CORS_ALLOWED_ORIGIN` hiç doldurulmazsa tarayıcıda ne görülür?$$,
           NULL, NULL,
           $$Frontend backend'e ulaşır, ama tarayıcı yanıtı JavaScript'e vermeyi reddeder. Bu yüzden Network sekmesinde başarılı (200) bir istek, konsolda ise bir CORS hatası görülür. İstek gönderilmemiş ya da 404 dönmüş değildir.$$,
           'claude-code@anthropic.com', now(), now(), now()
    FROM topic
    WHERE slug = 'react-spring-boot-deployment'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
SELECT new_question_tr5.id, v.option_text, v.is_correct, v.sort_order
FROM new_question_tr5
         CROSS JOIN (VALUES
        ($$Network sekmesinde 404 ile sonuçlanan bir istek$$, FALSE, 0),
        ($$Hiç gönderilmemiş bir istek ve boş bir Network sekmesi$$, FALSE, 1),
        ($$Network sekmesinde başarılı (200) bir istek, konsolda bir CORS hatası$$, TRUE, 2),
        ($$Başarılı bir istek ve normal biçimde gösterilen veri$$, FALSE, 3)
    ) AS v(option_text, is_correct, sort_order);
