-- Promotion batch
-- Development Question IDs: 369, 371, 374, 377, 378, 379
-- Generated: 2026-08-31 (this migration file's authoring date)
-- All 6 questions were generated by the real n8n large-scale question
-- generation pipeline (n8n/workflows/question-generation-enum-test.json,
-- Faz 152's fixed AI Judge, workflow-execution id resolved via Topic
-- Selection -> {topicSlug: "arrays", overrideCount: 8}), grounded in
-- content/en/arrays.md and content/tr/arrays.md, and PUBLISHED automatically
-- in development by the AI Judge's own APPROVE verdict via
-- QuestionReviewService#autoPublish (POST /api/internal/questions/{id}/
-- auto-publish) -- never a manual/bypass publish. 8 sibling PENDING_REVIEW
-- questions from the same run (dev ids 367, 368, 370, 372, 373, 375, 376,
-- 380 -- REJECT verdicts) plus 1 validation failure and 1 within-batch
-- duplicate are intentionally NOT included here; they remain untouched in
-- development for human review.
--
-- These development IDs are DOCUMENTATION/PROVENANCE ONLY -- no development
-- id is used as a foreign key value anywhere below. topic_id is resolved by
-- Topic.slug (globally unique, stable across environments); question_option
-- rows reference the newly generated id of the INSERT immediately above them
-- via a WITH ... RETURNING id CTE, so this migration is correct regardless of
-- what this environment's own auto-generated ids turn out to be -- same
-- pattern as question-promotion/V431 and V489.
--
-- Duplicate-promotion safety (bkz. docs/known-constraints.md "Faz D"): this
-- project intentionally has no promoted_at column or unique constraint yet --
-- before writing a NEW promotion migration, grep existing
-- db/migration/question-promotion/*.sql header comments for these same
-- Development Question IDs to confirm they were not already promoted (done
-- for this migration -- no overlap with V431's ids 44/45/46/47/48/53/54/55/57/58
-- or V489's string-topic ids).

-- Dev question id 369 (topic: arrays, language: en)
WITH new_question_369 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$What will happen if you try to access an index that is out of bounds in an array?$$, NULL, NULL,
           $$Accessing an out-of-bounds index will throw an ArrayIndexOutOfBoundsException, which is a runtime error indicating that the index is not valid for the array's size.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.83085',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$It will return null.$$, FALSE, 0 FROM new_question_369
        UNION ALL SELECT id, $$It will throw an ArrayIndexOutOfBoundsException.$$, TRUE, 1 FROM new_question_369
        UNION ALL SELECT id, $$It will silently return a default value.$$, FALSE, 2 FROM new_question_369
        UNION ALL SELECT id, $$It will print an error message to the console.$$, FALSE, 3 FROM new_question_369;

-- Dev question id 371 (topic: arrays, language: en)
WITH new_question_371 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$When using Arrays.asList() on an array, what type of List is returned?$$, NULL, NULL,
           $$Arrays.asList() returns a fixed-size List view that wraps the original array, which means it does not create a copy and modifications to the List affect the original array.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.867879',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$A resizable List that can add and remove elements.$$, FALSE, 0 FROM new_question_371
        UNION ALL SELECT id, $$A fixed-size List view of the original array.$$, TRUE, 1 FROM new_question_371
        UNION ALL SELECT id, $$A deep copy of the original array.$$, FALSE, 2 FROM new_question_371
        UNION ALL SELECT id, $$An empty List.$$, FALSE, 3 FROM new_question_371;

-- Dev question id 374 (topic: arrays, language: tr)
WITH new_question_374 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Bir dizinin boyutu ne zaman belirlenir?$$, NULL, NULL,
           $$Dizinin boyutu oluşturulduğu anda belirlenir ve bir daha değişmez. Bu, dizilerin dinamik boyutlu koleksiyonlardan en temel farkıdır.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.877639',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Oluşturulduğu anda$$, TRUE, 0 FROM new_question_374
        UNION ALL SELECT id, $$Program çalışırken$$, FALSE, 1 FROM new_question_374
        UNION ALL SELECT id, $$Eleman eklenirken$$, FALSE, 2 FROM new_question_374
        UNION ALL SELECT id, $$Bir metot çağrıldığında$$, FALSE, 3 FROM new_question_374;

-- Dev question id 377 (topic: arrays, language: tr)
WITH new_question_377 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Arrays.asList() metodu ne tür bir görünüm döner?$$, NULL, NULL,
           $$Arrays.asList() metodu, orijinal diziyi sabit boyutlu bir liste görünümü ile sarar. Bu görünüm üzerinden yazmak orijinal diziyi de değiştirir.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.888023',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Dinamik boyutlu bir liste$$, FALSE, 0 FROM new_question_377
        UNION ALL SELECT id, $$Sabit boyutlu bir liste görünümü$$, TRUE, 1 FROM new_question_377
        UNION ALL SELECT id, $$Yeni bir kopya$$, FALSE, 2 FROM new_question_377
        UNION ALL SELECT id, $$Boş bir liste$$, FALSE, 3 FROM new_question_377;

-- Dev question id 378 (topic: arrays, language: tr, type: CODE_OUTPUT)
WITH new_question_378 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Aşağıdaki kodun çıktısı ne olacaktır?$$,
           $$int[] numbers = {1, 2, 3};
System.out.println(Arrays.toString(numbers));$$, $$java$$,
           $$Kod, dizinin içeriğini Arrays.toString() metodu ile yazdırdığı için [1, 2, 3] şeklinde bir çıktı verir.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.898912',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$[1, 2, 3]$$, TRUE, 0 FROM new_question_378
        UNION ALL SELECT id, $$[I@7ea987ac$$, FALSE, 1 FROM new_question_378
        UNION ALL SELECT id, $$1, 2, 3$$, FALSE, 2 FROM new_question_378
        UNION ALL SELECT id, $$null$$, FALSE, 3 FROM new_question_378;

-- Dev question id 379 (topic: arrays, language: tr)
WITH new_question_379 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Bir dizinin elemanlarını karşılaştırmak için hangi metodu kullanmalıyız?$$, NULL, NULL,
           $$İki dizinin içeriğini karşılaştırmak için Arrays.equals() metodunu kullanmalıyız, çünkü == operatörü yalnızca referansı karşılaştırır.$$, $$n8n-ai-judge$$, '2026-08-31 17:07:53.910214',
           now(), now()
    FROM topic WHERE slug = 'arrays'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Arrays.compare()$$, FALSE, 0 FROM new_question_379
        UNION ALL SELECT id, $$Arrays.equals()$$, TRUE, 1 FROM new_question_379
        UNION ALL SELECT id, $$Arrays.compareTo()$$, FALSE, 2 FROM new_question_379
        UNION ALL SELECT id, $$== operatörü$$, FALSE, 3 FROM new_question_379;
