-- Promotion batch
-- Development Question IDs: 444, 445, 446, 447, 448, 449, 450, 451, 459, 460, 461, 462
-- Generated: 2026-08-31 (this migration file's authoring date)
-- All 12 questions were generated by the real n8n large-scale question
-- generation pipeline (n8n/workflows/question-generation-enum-test.json,
-- Topic Selection -> {topicSlug: "file-reading", overrideCount: 8}),
-- grounded in content/en/file-reading.md and content/tr/file-reading.md.
-- Generation for this batch used gpt-4 (not the production-default
-- gpt-4o-mini) via the OPENAI_MODEL env var at execution time, per an
-- explicit one-off request -- no workflow file change was needed since
-- Generate Batch/AI Judge Call OpenAI already read $env.OPENAI_MODEL; the
-- production default is unchanged.
--
-- 8 EN questions (444-451) were AI-Judge auto-published (5 on the first
-- attempt; 447, 450, 451 initially failed with a genuine OpenAI 429
-- rate-limit error on gpt-4's 10k-TPM budget -- NOT a content rejection --
-- and were re-judged individually afterward, getting real APPROVE
-- verdicts, then auto-published via QuestionReviewService#autoPublish).
--
-- The FIRST TR generation attempt (dev ids 452-458) came back with a known
-- n8n HTTP transport-layer bug (bkz. docs/known-constraints.md "Faz 148"):
-- Turkish text deterministically corrupted into CJK-range characters
-- (garbled, unreadable). 3 of those (454, 456, 457) had already been
-- AI-Judge auto-published before the corruption was caught on independent
-- human review -- the Judge does not check for text-encoding corruption,
-- only content correctness. Since QuestionReviewService#reject only
-- transitions from PENDING_REVIEW (409 otherwise), the 3 already-published
-- corrupted rows were corrected directly to REJECTED via a targeted UPDATE
-- (data-integrity fix, not a content override -- same class of fix as the
-- literal-backslash-n correction on the Scanner batch); the other 4
-- corrupted PENDING_REVIEW rows (452, 453, 455, 458) were rejected through
-- the normal QuestionReviewService#reject endpoint. NONE of the 7 corrupted
-- TR questions are included in this migration.
--
-- A scoped TR-only top-up run ({topicSlug: "file-reading", onlyLanguage:
-- "tr", overrideCount: 8}, the existing Faz 146/153 top-up mechanism) was
-- then run to obtain replacement TR content -- this second attempt came
-- back with clean, uncorrupted text (verified with a CJK Unicode-range
-- regex check against question/explanation/option text, same defensive
-- check used in the translation workflow's Validate Translation step, bkz.
-- Faz 148) and produced 4 AI-Judge-approved, auto-published TR questions
-- (459-462) -- all 4 passed independent human review and are included here.
--
-- Every one of the 12 included questions (8 EN AI-Judge auto-published, 4
-- TR AI-Judge auto-published) was independently re-reviewed by a human
-- against content/en/file-reading.md / content/tr/file-reading.md for
-- factual correctness, lesson-groundedness, whether the marked-correct
-- option directly answers the question stem (not merely whether it is
-- factually true), and distractor quality -- 0 defects found, none of the
-- Judge's own APPROVE verdicts were overridden.
--
-- These development IDs are DOCUMENTATION/PROVENANCE ONLY -- no development
-- id is used as a foreign key value anywhere below. topic_id is resolved by
-- Topic.slug (globally unique, stable across environments); question_option
-- rows reference the newly generated id of the INSERT immediately above them
-- via a WITH ... RETURNING id CTE, so this migration is correct regardless of
-- what this environment's own auto-generated ids turn out to be -- same
-- pattern as question-promotion/V431, V489, V520, V521, V525, and V529.
--
-- Duplicate-promotion safety (bkz. docs/known-constraints.md "Faz D"): this
-- project intentionally has no promoted_at column or unique constraint yet --
-- before writing a NEW promotion migration, grep existing
-- db/migration/question-promotion/*.sql header comments for these same
-- Development Question IDs to confirm they were not already promoted (done
-- for this migration -- no overlap with V431's ids 44-58, V489's string-topic
-- ids, V520/V521's arrays ids 367-380, V525's scanner ids 394-407, or V529's
-- wrapper-classes ids 420-431).

-- Dev question id 444 (topic: file-reading, language: en)
WITH new_question_444 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Which of the following is the correct way to count the number of lines in a file using the java.nio.file API without loading the entire file into memory?$$, NULL, NULL,
           $$Files.lines(path).count() is the correct way to count lines in a file without loading the entire file into memory. This method returns a Stream<String> and reads the file lazily. Files.readAllLines(path).size() loads the entire file into memory, which is not suitable for large files. Files.readString(path).lines().count() and Files.readString(path).split("\n").length would both load the entire file into memory as a single string, which is not efficient for large files.$$, $$n8n-ai-judge$$, '2026-08-31 23:27:53.752339',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Files.lines(path).count()$$, TRUE, 0 FROM new_question_444
        UNION ALL SELECT id, $$Files.readAllLines(path).size()$$, FALSE, 1 FROM new_question_444
        UNION ALL SELECT id, $$Files.readString(path).lines().count()$$, FALSE, 2 FROM new_question_444
        UNION ALL SELECT id, $$Files.readString(path).split("\n").length$$, FALSE, 3 FROM new_question_444;

-- Dev question id 445 (topic: file-reading, language: en)
WITH new_question_445 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$What is the consequence of using Files.lines(path) without try-with-resources?$$, NULL, NULL,
           $$Using Files.lines(path) without try-with-resources leads to a resource leak because the Stream<String> it returns holds a real file handle underneath. If not closed, the resource leaks. It doesn't lead to a compile error or a NoSuchFileException. It is also not related to the performance of the code.$$, $$n8n-ai-judge$$, '2026-08-31 23:27:53.786742',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$It leads to a compile error$$, FALSE, 0 FROM new_question_445
        UNION ALL SELECT id, $$It throws a NoSuchFileException$$, FALSE, 1 FROM new_question_445
        UNION ALL SELECT id, $$It leads to a resource leak$$, TRUE, 2 FROM new_question_445
        UNION ALL SELECT id, $$It decreases the performance of the code$$, FALSE, 3 FROM new_question_445;

-- Dev question id 446 (topic: file-reading, language: en)
WITH new_question_446 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$What does the Path.of(...) method do?$$, NULL, NULL,
           $$Path.of(...) creates an object that represents a file location. It does not touch the filesystem, it's just an 'address'. It does not create a new file, check if a file exists or read the file.$$, $$n8n-ai-judge$$, '2026-08-31 23:27:53.814284',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Creates a new file at the given location$$, FALSE, 0 FROM new_question_446
        UNION ALL SELECT id, $$Checks if a file exists at the given location$$, FALSE, 1 FROM new_question_446
        UNION ALL SELECT id, $$Reads a file at the given location$$, FALSE, 2 FROM new_question_446
        UNION ALL SELECT id, $$Creates an object that represents a file location$$, TRUE, 3 FROM new_question_446;

-- Dev question id 447 (topic: file-reading, language: en, type: CODE_OUTPUT)
WITH new_question_447 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$What will be the output of the following code if the file 'data.txt' contains the lines 'Hello', 'World', 'Java'?$$,
           $$Path path = Path.of("data.txt");
System.out.println(Files.readAllLines(path).size());$$, $$java$$,
           $$Files.readAllLines(path).size() reads all lines from the file into a List<String> and returns the size of the list, which is the number of lines in the file. In this case, the file contains three lines, so the output will be 3.$$, $$n8n-ai-judge$$, '2026-08-31 23:30:40.062472',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$1$$, FALSE, 0 FROM new_question_447
        UNION ALL SELECT id, $$2$$, FALSE, 1 FROM new_question_447
        UNION ALL SELECT id, $$3$$, TRUE, 2 FROM new_question_447
        UNION ALL SELECT id, $$4$$, FALSE, 3 FROM new_question_447;

-- Dev question id 448 (topic: file-reading, language: en)
WITH new_question_448 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$Which of the following are best practices when reading files in Java?$$, NULL, NULL,
           $$Using Files.readAllLines()/Files.readString() for small-to-medium files and Files.lines() for very large files are recommended practices. Using every resource that holds a file handle inside try-with-resources is also a best practice to prevent resource leaks. Catching NoSuchFileException when using the java.nio.file API is the correct exception handling. Using BufferedReader for small files is not a best practice, it can be used for any file size.$$, $$n8n-ai-judge$$, '2026-08-31 23:27:53.825513',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Use Files.readAllLines()/Files.readString() for small-to-medium files$$, TRUE, 0 FROM new_question_448
        UNION ALL SELECT id, $$Use BufferedReader for small files$$, FALSE, 1 FROM new_question_448
        UNION ALL SELECT id, $$Use every resource that holds a file handle inside try-with-resources$$, TRUE, 2 FROM new_question_448
        UNION ALL SELECT id, $$Catch NoSuchFileException when using the java.nio.file API$$, TRUE, 3 FROM new_question_448;

-- Dev question id 449 (topic: file-reading, language: en)
WITH new_question_449 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$Which of the following methods reads the entire file into a single String, including line separators?$$, NULL, NULL,
           $$Files.readString() reads the entire file into a single String, including line separators. Files.readAllLines() strips line separators and returns a List. BufferedReader.readLine() reads one line at a time, and Files.lines() reads the file lazily and returns a Stream<String>.$$, $$n8n-ai-judge$$, '2026-08-31 23:27:53.835531',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$Files.readString()$$, TRUE, 0 FROM new_question_449
        UNION ALL SELECT id, $$Files.readAllLines()$$, FALSE, 1 FROM new_question_449
        UNION ALL SELECT id, $$BufferedReader.readLine()$$, FALSE, 2 FROM new_question_449
        UNION ALL SELECT id, $$Files.lines()$$, FALSE, 3 FROM new_question_449;

-- Dev question id 450 (topic: file-reading, language: en)
WITH new_question_450 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$Which exception is thrown when a file does not exist and you try to read it using the java.nio.file API?$$, NULL, NULL,
           $$When using the java.nio.file API, a missing file throws NoSuchFileException. FileNotFoundException is thrown by the classic java.io classes like FileReader/FileInputStream.$$, $$n8n-ai-judge$$, '2026-08-31 23:30:43.06241',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$IOException$$, FALSE, 0 FROM new_question_450
        UNION ALL SELECT id, $$FileNotFoundException$$, FALSE, 1 FROM new_question_450
        UNION ALL SELECT id, $$NoSuchFileException$$, TRUE, 2 FROM new_question_450
        UNION ALL SELECT id, $$FileNotReadableException$$, FALSE, 3 FROM new_question_450;

-- Dev question id 451 (topic: file-reading, language: en)
WITH new_question_451 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$What does the BufferedReader.readLine() method return when there's nothing left to read?$$, NULL, NULL,
           $$BufferedReader.readLine() returns null exactly once, when there's nothing left to read. It does not return an empty string, a special EOF character or throw an EOFException.$$, $$n8n-ai-judge$$, '2026-08-31 23:30:45.821241',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$An empty string$$, FALSE, 0 FROM new_question_451
        UNION ALL SELECT id, $$A special EOF character$$, FALSE, 1 FROM new_question_451
        UNION ALL SELECT id, $$null$$, TRUE, 2 FROM new_question_451
        UNION ALL SELECT id, $$Throws an EOFException$$, FALSE, 3 FROM new_question_451;

-- Dev question id 459 (topic: file-reading, language: tr)
WITH new_question_459 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER',
           'PUBLISHED', 'OPENAI',
           $$`Files.lines(path)` metodu ne tür bir değer döndürür?$$, NULL, NULL,
           $$`Files.lines(path)` metodu, bir `Stream<String>` döndürür. Bu `Stream`, altında gerçek bir dosya tanıtıcısı tutar ve bu nedenle try-with-resources bloğu içinde kullanılmalıdır.$$, $$n8n-ai-judge$$, '2026-08-31 23:32:16.70264',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$`Stream<String>`$$, TRUE, 0 FROM new_question_459
        UNION ALL SELECT id, $$`List<String>`$$, FALSE, 1 FROM new_question_459
        UNION ALL SELECT id, $$`String`$$, FALSE, 2 FROM new_question_459
        UNION ALL SELECT id, $$`File`$$, FALSE, 3 FROM new_question_459;

-- Dev question id 460 (topic: file-reading, language: tr)
WITH new_question_460 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$Java'da dosya okuma için hangi API'ler kullanılabilir?$$, NULL, NULL,
           $$Java'da dosya okumak için iki API vardır: klasik `java.io` (`BufferedReader`+`FileReader`, satır satır okuma için) ve modern `java.nio.file` (`Path`+`Files`, `readAllLines()`/`readString()`/`lines()` ile çoğu işlemi tek satıra indirger).$$, $$n8n-ai-judge$$, '2026-08-31 23:32:16.713873',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$`java.io`$$, TRUE, 0 FROM new_question_460
        UNION ALL SELECT id, $$`java.nio.file`$$, TRUE, 1 FROM new_question_460
        UNION ALL SELECT id, $$`java.util`$$, FALSE, 2 FROM new_question_460
        UNION ALL SELECT id, $$`java.lang`$$, FALSE, 3 FROM new_question_460;

-- Dev question id 461 (topic: file-reading, language: tr)
WITH new_question_461 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$Aşağıdakilerden hangisi `BufferedReader` kullanırken dikkate alınmalıdır?$$, NULL, NULL,
           $$`BufferedReader` gerçek bir dosya tanıtıcısı tuttuğu için try-with-resources bloğu içinde kullanılmalıdır. Ayrıca, `readLine()` metodu dosyanın sonuna gelindiğinde tam olarak bir kez `null` döner ve bu, döngünün doğal bitiş koşuludur.$$, $$n8n-ai-judge$$, '2026-08-31 23:32:16.72377',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$`BufferedReader`'ı try-with-resources bloğu içinde kullanmalıyız$$, TRUE, 0 FROM new_question_461
        UNION ALL SELECT id, $$`readLine()` metodu dosyanın sonuna gelindiğinde `null` döner$$, TRUE, 1 FROM new_question_461
        UNION ALL SELECT id, $$`BufferedReader`'ı kapatmaya gerek yoktur$$, FALSE, 2 FROM new_question_461
        UNION ALL SELECT id, $$`readLine()` metodu dosyanın sonuna gelindiğinde bir istisna fırlatır$$, FALSE, 3 FROM new_question_461;

-- Dev question id 462 (topic: file-reading, language: tr)
WITH new_question_462 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'INTERMEDIATE',
           'PUBLISHED', 'OPENAI',
           $$`Files.readString()` ve `Files.readAllLines()` metotları için hangi istisna tipi yakalanmalıdır?$$, NULL, NULL,
           $$Modern `java.nio.file` API'sinde (`Files.readString()`, `Files.readAllLines()` vb.) eksik bir dosya `NoSuchFileException` fırlatır. Bu, klasik `java.io`'nun `FileNotFoundException`'ı değildir. Bu iki istisna, her ikisi de `IOException`'ı genişletse de, birbiriyle ilişkisiz istisna sınıflarıdır.$$, $$n8n-ai-judge$$, '2026-08-31 23:32:16.733553',
           now(), now()
    FROM topic WHERE slug = 'file-reading'
    RETURNING id
)
INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT id, $$`NoSuchFileException`$$, TRUE, 0 FROM new_question_462
        UNION ALL SELECT id, $$`FileNotFoundException`$$, FALSE, 1 FROM new_question_462
        UNION ALL SELECT id, $$`IOException`$$, FALSE, 2 FROM new_question_462
        UNION ALL SELECT id, $$`FileException`$$, FALSE, 3 FROM new_question_462;
