-- Portable promotion-style migration linking the EN Undoing
-- Changes quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468 and working-with-commits/V469-V470 (see those
-- files for the full rationale).
--
-- Development Question IDs: 135, 136, 137, 138, 139, 140, 141, 142, 143, 144
-- Topic: undoing-changes (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 135, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$If you've edited a file but haven't staged it yet, what does running `git restore <file>` do?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$If you've edited a file but haven't staged it yet, what does running `git restore <file>` do?$$, NULL, NULL,
           $$`git restore` only ever touches the working tree — it discards the uncommitted edit and reverts to the last committed version. It never unstages a file (that requires `--staged`) or touches HEAD.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.352347',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Discards the uncommitted edit in the working tree, reverting the file to the last committed version.$$, TRUE, 0),
    ($$Unstages the file, moving it back from the staging area to the working tree.$$, FALSE, 1),
    ($$Moves HEAD back to the previous commit, undoing the last commit.$$, FALSE, 2),
    ($$Creates a new commit that reverses the change.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 136, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$You ran `git add UserService.java` by mistake and want to unstage it without discarding your edits. Which command should you use?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You ran `git add UserService.java` by mistake and want to unstage it without discarding your edits. Which command should you use?$$, NULL, NULL,
           $$`git restore --staged` moves a file back from the staging area to the working tree without touching the edit itself — exactly what's needed to undo a mistaken `git add` while keeping the changes.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.383539',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$git reset --hard HEAD~1$$, FALSE, 0),
    ($$git restore --staged UserService.java$$, TRUE, 1),
    ($$git revert HEAD$$, FALSE, 2),
    ($$git restore UserService.java$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 137, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$You run `git reset --soft HEAD~1`. Which of the following are true? (Select all that apply)$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You run `git reset --soft HEAD~1`. Which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$`git reset --soft HEAD~1` moves HEAD back one commit but leaves the staging area and working tree untouched, so everything from that commit sits in the staging area ready to be re-committed — nothing is discarded.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.393503',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$The working tree files are overwritten to match the earlier commit.$$, FALSE, 0),
    ($$The change is permanently discarded and cannot be recovered.$$, FALSE, 1),
    ($$The branch's HEAD moves back one commit.$$, TRUE, 2),
    ($$Everything from the undone commit is left sitting in the staging area, ready to be re-committed.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 138, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$Running `git reset HEAD~1` with no flag has the same effect as which mode?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Running `git reset HEAD~1` with no flag has the same effect as which mode?$$, NULL, NULL,
           $$Running `git reset` with no flag defaults to `--mixed`, which moves HEAD back and resets the staging area to match, but leaves the working tree files untouched.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.401339',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Moves HEAD back only, leaving the staging area and working tree completely untouched.$$, FALSE, 0),
    ($$Creates a brand-new commit that reverses the target commit's changes.$$, FALSE, 1),
    ($$Moves HEAD back and resets the staging area to match, but leaves working tree files untouched.$$, TRUE, 2),
    ($$Moves HEAD back, resets the staging area, and also overwrites the working tree files.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 139, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$After running `git reset --mixed HEAD~1`, what state are the changes from the undone commit in?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$After running `git reset --mixed HEAD~1`, what state are the changes from the undone commit in?$$, NULL, NULL,
           $$`--mixed` leaves working tree files untouched, so the undone commit's changes end up as unstaged edits in the working tree — as if you'd made them but never run `git add`.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.408438',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$They are gone permanently, with no trace in the working tree or staging area.$$, FALSE, 0),
    ($$They sit in the working tree as unstaged edits, as if you'd made the changes but never run `git add`.$$, TRUE, 1),
    ($$They are still staged, ready to be committed again immediately.$$, FALSE, 2),
    ($$The working tree files were overwritten to remove the changes entirely.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 140, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$Why is `git reset --hard` considered the most destructive of the three reset modes described in the lesson?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why is `git reset --hard` considered the most destructive of the three reset modes described in the lesson?$$, NULL, NULL,
           $$`--hard` is the most destructive mode because, unlike `--soft` and `--mixed`, it also overwrites the working tree files to match the target commit, discarding any uncommitted work instantly and without confirmation.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.415646',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$It overwrites your working tree files to match the target commit, discarding uncommitted work with no confirmation prompt.$$, TRUE, 0),
    ($$It is the only mode that requires a network connection to run.$$, FALSE, 1),
    ($$It permanently deletes your entire local Git repository.$$, FALSE, 2),
    ($$It is the only mode that can move HEAD forward instead of backward.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 141, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$According to the lesson's Best Practices and Common Mistakes, which of the following are true? (Select all that apply)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Best Practices and Common Mistakes, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Best Practices recommend running `git status` before any reset (especially `--hard`) and defaulting to `git revert` for anything already pushed — using `git reset` on a commit someone else has pulled silently rewrites shared history, which the lesson explicitly warns against.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.422331',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$You should run `git status` before any reset, especially `--hard`, so you know exactly what you're about to lose.$$, TRUE, 0),
    ($$It's safe to use `git reset` on a commit someone else has already pulled, since Git automatically syncs shared history.$$, FALSE, 1),
    ($$`git reset --soft` should generally be avoided because it silently deletes staged changes.$$, FALSE, 2),
    ($$The default choice for anything that has already been pushed should be `git revert`, since it's the safe option for shared history.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 142, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$What is the key difference in how `git reset` and `git revert` undo a commit's effect?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What is the key difference in how `git reset` and `git revert` undo a commit's effect?$$, NULL, NULL,
           $$`git reset` rewrites history by moving HEAD backward, while `git revert` leaves existing history untouched and instead adds a brand-new commit whose changes cancel out the target commit.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.428617',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git reset` and `git revert` always produce an identical resulting history.$$, FALSE, 0),
    ($$`git reset` moves HEAD backward, rewriting history; `git revert` adds a brand-new commit that cancels out the old one, leaving existing history untouched.$$, TRUE, 1),
    ($$`git revert` moves HEAD backward and removes the commit from history, just like `git reset`.$$, FALSE, 2),
    ($$`git reset` only works on commits that have already been pushed, while `git revert` only works on local commits.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 143, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$Which of the following statements distinguish `git restore` from `git reset`? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following statements distinguish `git restore` from `git reset`? (Select all that apply)$$, NULL, NULL,
           $$`git restore` never moves HEAD — it only ever touches the working tree and, with `--staged`, the staging area. `git reset` is the command that can move HEAD to an earlier commit.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.436227',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$`git restore --staged` discards the uncommitted edit itself, not just the staged state.$$, FALSE, 0),
    ($$`git reset` can move HEAD to point at an earlier commit, something `git restore` never does.$$, TRUE, 1),
    ($$`git restore` only ever touches the working tree (and, with `--staged`, the staging area) — it never moves HEAD.$$, TRUE, 2),
    ($$`git reset` always creates a new commit instead of changing history, exactly like `git revert`.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 144, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'en'
      AND question = $$According to the lesson's decision guide, which command should you use to discard a local, unpushed commit and its changes completely?$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's decision guide, which command should you use to discard a local, unpushed commit and its changes completely?$$, NULL, NULL,
           $$The lesson's decision guide lists `git reset --hard HEAD~1` as the command for discarding a local, unpushed commit and its changes completely — the most destructive of the reset modes.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.443791',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$git restore --staged <file>$$, FALSE, 0),
    ($$git revert HEAD$$, FALSE, 1),
    ($$git reset --soft HEAD~1$$, FALSE, 2),
    ($$git reset --hard HEAD~1$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

