-- Portable promotion-style migration linking the TR Undoing
-- Changes quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468 and working-with-commits/V469-V470 (see those
-- files for the full rationale).
--
-- Development Question IDs: 145, 146, 147, 148, 149, 150, 151, 152, 153, 154
-- Topic: undoing-changes (language: tr)
-- Turkish counterparts of the English questions in V471 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 145, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Bir dosyayı düzenledin ama henüz stage'lemediysen, `git restore <dosya>` çalıştırmak ne yapar?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bir dosyayı düzenledin ama henüz stage'lemediysen, `git restore <dosya>` çalıştırmak ne yapar?$$, NULL, NULL,
           $$`git restore` yalnızca working tree'ye dokunur — commit edilmemiş düzenlemeyi atar ve dosyayı son commit edilmiş sürüme döndürür. Bir dosyayı asla unstage etmez (bunun için `--staged` gerekir) ve HEAD'e dokunmaz.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.454197',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Working tree'deki commit edilmemiş düzenlemeyi atar, dosyayı son commit edilmiş sürüme döndürür.$$, TRUE, 0),
    ($$Dosyayı staging area'dan working tree'ye geri taşıyarak unstage eder.$$, FALSE, 1),
    ($$HEAD'i önceki commit'e taşıyarak son commit'i geri alır.$$, FALSE, 2),
    ($$Değişikliği tersine çeviren yeni bir commit oluşturur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 146, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Yanlışlıkla `git add UserService.java` çalıştırdın ve düzenlemeni atmadan dosyayı unstage etmek istiyorsun. Hangi komutu kullanmalısın?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Yanlışlıkla `git add UserService.java` çalıştırdın ve düzenlemeni atmadan dosyayı unstage etmek istiyorsun. Hangi komutu kullanmalısın?$$, NULL, NULL,
           $$`git restore --staged`, düzenlemenin kendisine dokunmadan dosyayı staging area'dan working tree'ye geri taşır — yanlışlıkla yapılan bir `git add`'i, değişiklikleri koruyarak geri almak için tam olarak gereken budur.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.461262',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$git reset --hard HEAD~1$$, FALSE, 0),
    ($$git restore --staged UserService.java$$, TRUE, 1),
    ($$git revert HEAD$$, FALSE, 2),
    ($$git restore UserService.java$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 147, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$`git reset --soft HEAD~1` çalıştırıyorsun. Aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git reset --soft HEAD~1` çalıştırıyorsun. Aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git reset --soft HEAD~1`, HEAD'i bir commit geriye taşır ama staging area'yı ve working tree'yi dokunulmamış bırakır, bu yüzden o commit'teki her şey yeniden commit edilmeye hazır şekilde staging area'da oturur — hiçbir şey atılmaz.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.467587',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Working tree dosyaları önceki commit'e uyacak şekilde üzerine yazılır.$$, FALSE, 0),
    ($$Değişiklik kalıcı olarak atılır ve geri getirilemez.$$, FALSE, 1),
    ($$Branch'in HEAD'i bir commit geriye taşınır.$$, TRUE, 2),
    ($$Geri alınan commit'teki her şey, yeniden commit edilmeye hazır şekilde staging area'da kalır.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 148, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Hiçbir flag olmadan `git reset HEAD~1` çalıştırmak hangi modla aynı etkiye sahiptir?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Hiçbir flag olmadan `git reset HEAD~1` çalıştırmak hangi modla aynı etkiye sahiptir?$$, NULL, NULL,
           $$Hiçbir flag olmadan `git reset` çalıştırmak varsayılan olarak `--mixed`'e düşer; bu, HEAD'i geri taşır ve staging area'yı buna uyacak şekilde sıfırlar, ama working tree dosyalarına dokunmaz.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.473873',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Yalnızca HEAD'i geri taşır, staging area ve working tree'yi tamamen dokunulmamış bırakır.$$, FALSE, 0),
    ($$Hedef commit'in değişikliklerini tersine çeviren yepyeni bir commit oluşturur.$$, FALSE, 1),
    ($$HEAD'i geri taşır ve staging area'yı buna uyacak şekilde sıfırlar, ama working tree dosyalarına dokunmaz.$$, TRUE, 2),
    ($$HEAD'i geri taşır, staging area'yı sıfırlar, ve ayrıca working tree dosyalarını da üzerine yazar.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 149, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$`git reset --mixed HEAD~1` çalıştırdıktan sonra, geri alınan commit'teki değişiklikler hangi durumda olur?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git reset --mixed HEAD~1` çalıştırdıktan sonra, geri alınan commit'teki değişiklikler hangi durumda olur?$$, NULL, NULL,
           $$`--mixed`, working tree dosyalarına dokunmadığı için geri alınan commit'in değişiklikleri working tree'de unstaged düzenlemeler olarak kalır -- sanki onları yapmışsın ama hiç `git add` çalıştırmamışsın gibi.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.48186',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Working tree'de ya da staging area'da hiçbir iz bırakmadan kalıcı olarak kaybolur.$$, FALSE, 0),
    ($$Working tree'de unstaged düzenlemeler olarak durur -- sanki değişiklikleri yapmışsın ama hiç `git add` çalıştırmamışsın gibi.$$, TRUE, 1),
    ($$Hâlâ stage'lidir, hemen yeniden commit edilmeye hazırdır.$$, FALSE, 2),
    ($$Working tree dosyaları, değişiklikleri tamamen kaldıracak şekilde üzerine yazılmıştır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 150, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Ders, üç reset modu arasında `git reset --hard`'ı neden en yıkıcısı olarak tanımlıyor?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, üç reset modu arasında `git reset --hard`'ı neden en yıkıcısı olarak tanımlıyor?$$, NULL, NULL,
           $$`--hard` en yıkıcı moddur çünkü `--soft` ve `--mixed`'in aksine working tree dosyalarını da hedef commit'e uyacak şekilde üzerine yazar, commit edilmemiş işi hiçbir onay istemi olmadan anında atar.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.488345',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Working tree dosyalarını hedef commit'e uyacak şekilde üzerine yazar, commit edilmemiş işi hiçbir onay istemi olmadan atar.$$, TRUE, 0),
    ($$Çalışması için internet bağlantısı gerektiren tek moddur.$$, FALSE, 1),
    ($$Yerel Git deposunun tamamını kalıcı olarak siler.$$, FALSE, 2),
    ($$HEAD'i geriye değil ileriye taşıyabilen tek moddur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 151, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Dersin Best Practices ve Yaygın Hatalar bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Best Practices ve Yaygın Hatalar bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Best Practices bölümü, herhangi bir reset'ten önce (özellikle `--hard`'dan önce) `git status` çalıştırmayı ve zaten push edilmiş her şey için `git revert`'i varsayılan seçim yapmayı öneriyor -- başka birinin zaten pull ettiği bir commit'te `git reset` kullanmak paylaşılan geçmişi sessizce yeniden yazar, ders bu konuda açıkça uyarıyor.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.495283',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Herhangi bir reset'ten önce, özellikle `--hard`'dan önce, tam olarak neyi kaybedeceğini bilmek için `git status` çalıştırmalısın.$$, TRUE, 0),
    ($$Başka birinin zaten pull ettiği bir commit'te `git reset` kullanmak güvenlidir, çünkü Git paylaşılan geçmişi otomatik olarak senkronize eder.$$, FALSE, 1),
    ($$`git reset --soft` genellikle kaçınılması gereken bir komuttur çünkü stage'lenmiş değişiklikleri sessizce siler.$$, FALSE, 2),
    ($$Zaten push edilmiş herhangi bir şey için varsayılan seçim `git revert` olmalıdır, çünkü paylaşılan geçmiş için güvenli seçenek budur.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 152, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$`git reset` ile `git revert`'in bir commit'in etkisini geri almasındaki temel fark nedir?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git reset` ile `git revert`'in bir commit'in etkisini geri almasındaki temel fark nedir?$$, NULL, NULL,
           $$`git reset`, HEAD'i geriye taşıyarak geçmişi yeniden yazar; `git revert` ise var olan geçmişi dokunulmamış bırakıp hedef commit'in değişikliklerini iptal eden yepyeni bir commit ekler.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.501796',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git reset` ve `git revert` her zaman birebir aynı sonuç geçmişini üretir.$$, FALSE, 0),
    ($$`git reset`, HEAD'i geriye taşıyarak geçmişi yeniden yazar; `git revert` ise eskisini iptal eden yepyeni bir commit ekler, var olan geçmişi dokunulmamış bırakır.$$, TRUE, 1),
    ($$`git revert`, tıpkı `git reset` gibi HEAD'i geriye taşır ve commit'i geçmişten kaldırır.$$, FALSE, 2),
    ($$`git reset` yalnızca zaten push edilmiş commit'lerde çalışır, `git revert` ise yalnızca yerel commit'lerde çalışır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 153, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Aşağıdaki ifadelerden hangileri `git restore`'u `git reset`'ten ayırır? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Aşağıdaki ifadelerden hangileri `git restore`'u `git reset`'ten ayırır? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git restore` HEAD'i asla taşımaz -- yalnızca working tree'ye ve `--staged` ile staging area'ya dokunur. HEAD'i önceki bir commit'e taşıyabilen komut `git reset`'tir.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.508165',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$`git restore --staged`, yalnızca stage durumunu değil, commit edilmemiş düzenlemenin kendisini de atar.$$, FALSE, 0),
    ($$`git reset`, HEAD'i önceki bir commit'e taşıyabilir -- `git restore` bunu asla yapmaz.$$, TRUE, 1),
    ($$`git restore` yalnızca working tree'ye (ve `--staged` ile staging area'ya) dokunur -- HEAD'i asla taşımaz.$$, TRUE, 2),
    ($$`git reset`, tıpkı `git revert` gibi, geçmişi değiştirmek yerine her zaman yeni bir commit oluşturur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 154, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'undoing-changes')
      AND language = 'tr'
      AND question = $$Dersin karar rehberine göre, yerel, push edilmemiş bir commit'i ve değişikliklerini tamamen atmak için hangi komutu kullanmalısın?$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin karar rehberine göre, yerel, push edilmemiş bir commit'i ve değişikliklerini tamamen atmak için hangi komutu kullanmalısın?$$, NULL, NULL,
           $$Dersin karar rehberi, yerel, push edilmemiş bir commit'i ve değişikliklerini tamamen atmak için `git reset --hard HEAD~1`'i listeler -- reset modları arasında en yıkıcı olanı.$$, 'n8n-ai-judge', '2026-08-29 15:08:40.514761',
           now(), now()
    FROM topic
    WHERE slug = 'undoing-changes'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$git restore --staged <dosya>$$, FALSE, 0),
    ($$git revert HEAD$$, FALSE, 1),
    ($$git reset --soft HEAD~1$$, FALSE, 2),
    ($$git reset --hard HEAD~1$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'undoing-changes'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

