-- Portable promotion-style migration linking the EN Pull Requests
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474, and
-- github-and-remotes/V475-V476 (see those files for the full rationale).
--
-- Development Question IDs: 195, 196, 197, 198, 199, 200, 201, 202, 203, 204
-- Topic: pull-requests (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 195, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$According to the lesson, what is a Pull Request (PR), fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is a Pull Request (PR), fundamentally?$$, NULL, NULL,
           $$A Pull Request proposes merging one branch into another and opens a dedicated page for review before the merge happens — despite the name, it doesn't 'pull' anything by itself.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.570249',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$A GitHub feature that proposes merging one branch into another and opens a dedicated space to review it before it's merged.$$, TRUE, 0),
    ($$A command that automatically pulls and merges another developer's branch into yours.$$, FALSE, 1),
    ($$A permanent branch that always mirrors `main`.$$, FALSE, 2),
    ($$A GitHub setting that blocks anyone from pushing directly to a repository.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 196, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$In the feature-branch workflow you already know, what does a Pull Request actually replace?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In the feature-branch workflow you already know, what does a Pull Request actually replace?$$, NULL, NULL,
           $$The branch, commit, and push steps stay the same as the feature-branch workflow you already know — a PR simply replaces the local `git merge` step with a reviewed, GitHub-hosted merge.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.604804',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$The `git push` step, which is no longer necessary once a PR exists.$$, FALSE, 0),
    ($$The local `git merge` step — a PR replaces it with a reviewed, GitHub-hosted merge.$$, TRUE, 1),
    ($$The `git branch` step used to create the feature branch in the first place.$$, FALSE, 2),
    ($$The commit step — PRs commit your changes automatically.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 197, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$Why does the lesson say a PR's description deserves the same care as a good commit message?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson say a PR's description deserves the same care as a good commit message?$$, NULL, NULL,
           $$The PR description is where reviewers form their first impression of the change, which is exactly why the lesson says to treat it with the same care as a good commit message.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.613443',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Because GitHub automatically deletes PRs with empty descriptions after 24 hours.$$, FALSE, 0),
    ($$Because the description determines which branch the PR merges into.$$, FALSE, 1),
    ($$Because it's where reviewers form their first impression of the change.$$, TRUE, 2),
    ($$Because a missing description prevents the PR from being created at all.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 198, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$According to the lesson, what happens after a reviewer submits 'Request changes' and the author pushes new commits to address it?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what happens after a reviewer submits 'Request changes' and the author pushes new commits to address it?$$, NULL, NULL,
           $$GitHub automatically updates the existing PR with any new commits pushed to the same branch — no new PR is needed to address review feedback.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.620958',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$The author must close the PR and open a brand-new one with the fixes.$$, FALSE, 0),
    ($$The reviewer's 'Request changes' is automatically cleared without them looking again.$$, FALSE, 1),
    ($$GitHub asks the author to squash the new commits before they can be added.$$, FALSE, 2),
    ($$GitHub automatically updates the existing PR with the new commits — no new PR is needed.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 199, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$On most professional teams, what is typically required before the merge button on a PR becomes available?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$On most professional teams, what is typically required before the merge button on a PR becomes available?$$, NULL, NULL,
           $$On most professional teams, at least one approval is required before the merge button becomes available, typically enforced by branch protection rules.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.627769',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$At least one approval, usually enforced by branch protection rules.$$, TRUE, 0),
    ($$A minimum of ten inline comments from the reviewer.$$, FALSE, 1),
    ($$The PR must be open for at least 24 hours regardless of review status.$$, FALSE, 2),
    ($$The author must personally message the reviewer outside of GitHub.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 200, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$What does deleting a branch after its PR is merged correspond to, according to the lesson?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does deleting a branch after its PR is merged correspond to, according to the lesson?$$, NULL, NULL,
           $$Deleting a branch after its PR is merged is the remote equivalent of the `git branch -d` cleanup already known from local branches, and just as safe — the commits live on permanently in `main`'s history.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.635145',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$It has no real-world equivalent — it's a GitHub-only concept.$$, FALSE, 0),
    ($$The remote equivalent of the `git branch -d` cleanup already known from local branches — just as safe, since commits live on in `main`.$$, TRUE, 1),
    ($$The equivalent of `git branch -D`, since it discards the branch's commits permanently.$$, FALSE, 2),
    ($$A required step before the PR can be marked as merged.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 201, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$According to the lesson, what are branch protection rules?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what are branch protection rules?$$, NULL, NULL,
           $$Branch protection rules are settings a repository admin configures on GitHub to automatically enforce practices like required approvals or blocking direct pushes to `main`, rather than relying on everyone remembering to follow them.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.642477',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Automatic backups GitHub takes of every branch every night.$$, FALSE, 0),
    ($$A feature that prevents anyone from ever deleting a branch.$$, FALSE, 1),
    ($$Settings a repository admin configures to automatically enforce practices like required approvals or blocking direct pushes to `main`.$$, TRUE, 2),
    ($$A GitHub Actions workflow that runs tests before every commit.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 202, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$Which of the following are true about merging a Pull Request on GitHub, according to the lesson? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about merging a Pull Request on GitHub, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$GitHub's merge button performs the merge on the server exactly as `git merge` would locally — the difference is that it happens after review, and it's visible to the whole team with a permanent record.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.650941',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$GitHub's merge button performs the merge on the server, exactly as `git merge` would locally.$$, TRUE, 0),
    ($$Merging automatically force-pushes over the reviewer's copy of the branch.$$, FALSE, 1),
    ($$The merge happens after review, unlike a plain local `git merge`, which has no review step.$$, TRUE, 2),
    ($$Only the original author of the PR is allowed to click the merge button.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 203, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$Which of the following are true about 'Create a merge commit' vs 'Squash and merge', according to the lesson? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about 'Create a merge commit' vs 'Squash and merge', according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$'Create a merge commit' keeps every individual commit from the branch plus a merge commit tying them together; 'Squash and merge' combines every commit on the branch into a single new commit on `main`.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.658685',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$'Squash and merge' preserves every individual commit from the branch as separate commits on `main`.$$, FALSE, 0),
    ($$'Create a merge commit' keeps every individual commit from the branch, plus a merge commit tying them together.$$, TRUE, 1),
    ($$'Create a merge commit' discards the branch's commit history entirely.$$, FALSE, 2),
    ($$'Squash and merge' combines every commit on the branch into a single new commit on `main`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 204, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes warns that a vague PR title/description leaves the reviewer to reverse-engineer the change's purpose, and its Best Practices recommend keeping PRs small and focused so they get reviewed faster and more thoroughly.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.66723',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Opening a PR with a vague title and no description leaves the reviewer to reverse-engineer why the change exists from the diff alone.$$, TRUE, 0),
    ($$It's fine to merge your own PR without waiting for review, as long as you're confident in the change.$$, FALSE, 1),
    ($$Large PRs covering many unrelated changes get reviewed just as fast as small, focused ones.$$, FALSE, 2),
    ($$Keeping PRs small and focused on one thing helps them get reviewed faster and more thoroughly.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

