-- Portable promotion-style migration linking the TR Pull Requests
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474, and
-- github-and-remotes/V475-V476 (see those files for the full rationale).
--
-- Development Question IDs: 205, 206, 207, 208, 209, 210, 211, 212, 213, 214
-- Topic: pull-requests (language: tr)
-- Turkish counterparts of the English questions in V477 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 205, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre bir Pull Request (PR), temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir Pull Request (PR), temelde nedir?$$, NULL, NULL,
           $$Bir Pull Request, bir branch'in başka birine merge edilmesini önerir ve merge gerçekleşmeden önce inceleme için özel bir sayfa açar — ismine rağmen, kendi başına hiçbir şeyi 'pull' etmez.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.674751',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Bir branch'in başka birine merge edilmesini öneren ve merge edilmeden önce incelemek için özel bir alan açan bir GitHub özelliği.$$, TRUE, 0),
    ($$Başka bir geliştiricinin branch'ini otomatik olarak pull edip seninkine merge eden bir komut.$$, FALSE, 1),
    ($$Her zaman `main`'i yansıtan kalıcı bir branch.$$, FALSE, 2),
    ($$Kimsenin bir repository'ye doğrudan push yapmasını engelleyen bir GitHub ayarı.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 206, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Zaten bildiğin feature-branch workflow'unda, bir Pull Request aslında neyin yerini alır?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Zaten bildiğin feature-branch workflow'unda, bir Pull Request aslında neyin yerini alır?$$, NULL, NULL,
           $$Branch, commit ve push adımları, zaten bildiğin feature-branch workflow'uyla aynı kalır — bir PR, yalnızca yerel `git merge` adımını, incelenmiş, GitHub'da barındırılan bir merge ile değiştirir.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.681924',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Artık bir PR varken gerekli olmayan `git push` adımının.$$, FALSE, 0),
    ($$Yerel `git merge` adımının — bir PR bunu incelenmiş, GitHub'da barındırılan bir merge ile değiştirir.$$, TRUE, 1),
    ($$Feature branch'i ilk oluşturmak için kullanılan `git branch` adımının.$$, FALSE, 2),
    ($$Commit adımının — PR'lar değişikliklerini otomatik olarak commit eder.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 207, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Ders, neden bir PR'ın açıklamasının iyi bir commit mesajıyla aynı özeni hak ettiğini söylüyor?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, neden bir PR'ın açıklamasının iyi bir commit mesajıyla aynı özeni hak ettiğini söylüyor?$$, NULL, NULL,
           $$PR açıklaması, reviewer'ların değişiklik hakkındaki ilk izlenimlerini oluşturdukları yerdir, ki ders tam olarak bu yüzden ona iyi bir commit mesajıyla aynı özeni göstermeni söylüyor.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.68845',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Çünkü GitHub, boş açıklamalı PR'ları 24 saat sonra otomatik olarak siler.$$, FALSE, 0),
    ($$Çünkü açıklama, PR'ın hangi branch'e merge edileceğini belirler.$$, FALSE, 1),
    ($$Çünkü reviewer'ların değişiklik hakkındaki ilk izlenimlerini oluşturdukları yer orasıdır.$$, TRUE, 2),
    ($$Çünkü eksik bir açıklama, PR'ın oluşturulmasını tamamen engeller.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 208, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre, bir reviewer 'Request changes' gönderdikten ve yazar bunu çözmek için yeni commit'ler push ettikten sonra ne olur?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre, bir reviewer 'Request changes' gönderdikten ve yazar bunu çözmek için yeni commit'ler push ettikten sonra ne olur?$$, NULL, NULL,
           $$GitHub, aynı branch'e push edilen herhangi bir yeni commit ile var olan PR'ı otomatik olarak günceller — inceleme geri bildirimini ele almak için yeni bir PR gerekmez.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.694701',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Yazar PR'ı kapatıp düzeltmelerle yepyeni bir tane açmalıdır.$$, FALSE, 0),
    ($$Reviewer'ın 'Request changes'i, tekrar bakmasına gerek kalmadan otomatik olarak temizlenir.$$, FALSE, 1),
    ($$GitHub, eklenebilmeleri için yazardan yeni commit'leri squash etmesini ister.$$, FALSE, 2),
    ($$GitHub, var olan PR'ı bu yeni commit'lerle otomatik olarak günceller — yeni bir PR gerekmez.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 209, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Çoğu profesyonel takımda, bir PR'daki merge butonu kullanılabilir hale gelmeden önce tipik olarak ne gereklidir?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Çoğu profesyonel takımda, bir PR'daki merge butonu kullanılabilir hale gelmeden önce tipik olarak ne gereklidir?$$, NULL, NULL,
           $$Çoğu profesyonel takımda, merge butonu kullanılabilir hale gelmeden önce en az bir onay gerekir, genellikle branch protection rule'ları tarafından zorunlu kılınır.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.701291',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Genellikle branch protection rule'ları tarafından zorunlu kılınan en az bir onay.$$, TRUE, 0),
    ($$Reviewer'dan en az on satır-içi yorum.$$, FALSE, 1),
    ($$İnceleme durumundan bağımsız olarak PR'ın en az 24 saat açık kalması.$$, FALSE, 2),
    ($$Yazarın reviewer'a GitHub dışında bizzat mesaj atması.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 210, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre, PR'ı merge edildikten sonra branch'i silmek neye karşılık gelir?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre, PR'ı merge edildikten sonra branch'i silmek neye karşılık gelir?$$, NULL, NULL,
           $$PR'ı merge edildikten sonra branch'i silmek, yerel branch'lerden zaten bilinen `git branch -d` temizliğinin remote karşılığıdır, ve o kadar güvenlidir — commit'ler `main`'in geçmişinde kalıcı olarak yaşamaya devam eder.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.707955',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Gerçek dünyada bir karşılığı yoktur — yalnızca GitHub'a özgü bir kavramdır.$$, FALSE, 0),
    ($$Yerel branch'lerden zaten bilinen `git branch -d` temizliğinin remote karşılığı — ve o kadar güvenlidir, çünkü commit'ler `main`'de yaşamaya devam eder.$$, TRUE, 1),
    ($$`git branch -D`'nin karşılığıdır, çünkü branch'in commit'lerini kalıcı olarak yok eder.$$, FALSE, 2),
    ($$PR'ın merge edilmiş olarak işaretlenmesinden önce gereken bir adımdır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 211, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre branch protection rule'ları nedir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre branch protection rule'ları nedir?$$, NULL, NULL,
           $$Branch protection rule'ları, bir repository admin'inin, herkesin uymayı hatırlamasına güvenmek yerine gerekli onaylar ya da `main`'e doğrudan push'ları engellemek gibi pratikleri otomatik olarak zorunlu kılmak için GitHub'da yapılandırdığı ayarlardır.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.71514',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$GitHub'ın her gece her branch için aldığı otomatik yedekler.$$, FALSE, 0),
    ($$Kimsenin bir branch'i asla silmesini engelleyen bir özellik.$$, FALSE, 1),
    ($$Bir repository admin'inin, gerekli onaylar ya da `main`'e doğrudan push'ları engellemek gibi pratikleri otomatik olarak zorunlu kılmak için yapılandırdığı ayarlar.$$, TRUE, 2),
    ($$Her commit'ten önce testleri çalıştıran bir GitHub Actions workflow'u.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 212, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre GitHub'da bir Pull Request'i merge etmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre GitHub'da bir Pull Request'i merge etmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$GitHub'ın merge butonu, merge'i sunucuda tam olarak yerel `git merge`'ün yapacağı gibi gerçekleştirir — fark, incelemeden sonra gerçekleşmesi ve tüm takım tarafından kalıcı bir kayıtla görülebilir olmasıdır.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.722493',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$GitHub'ın merge butonu, merge'i sunucuda, tam olarak yerel `git merge`'ün yapacağı gibi gerçekleştirir.$$, TRUE, 0),
    ($$Merge etmek, reviewer'ın branch kopyasının üzerine otomatik olarak force-push yapar.$$, FALSE, 1),
    ($$Merge, incelemeden sonra gerçekleşir, hiçbir inceleme adımı olmayan düz bir yerel `git merge`'ün aksine.$$, TRUE, 2),
    ($$Merge butonuna yalnızca PR'ın orijinal yazarı tıklayabilir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 213, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Derse göre 'Create a merge commit' ile 'Squash and merge' hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre 'Create a merge commit' ile 'Squash and merge' hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$'Create a merge commit', branch'ten her bireysel commit'i artı onları bir araya bağlayan bir merge commit'i korur; 'Squash and merge' ise branch'teki her commit'i `main`'de tek, yeni bir commit'te birleştirir.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.729581',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$'Squash and merge', branch'ten her bireysel commit'i `main`'de ayrı commit'ler olarak korur.$$, FALSE, 0),
    ($$'Create a merge commit', branch'ten her bireysel commit'i, artı onları bir araya bağlayan bir merge commit'i korur.$$, TRUE, 1),
    ($$'Create a merge commit', branch'in commit geçmişini tamamen yok eder.$$, FALSE, 2),
    ($$'Squash and merge', branch'teki her commit'i `main`'de tek, yeni bir commit'te birleştirir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 214, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'pull-requests')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, belirsiz bir PR başlığının/açıklamasının reviewer'ı değişikliğin amacını tersine mühendislikle çıkarmaya bıraktığını uyarıyor, En İyi Pratikler bölümü ise PR'ları küçük ve odaklı tutmayı öneriyor çünkü daha hızlı ve daha kapsamlı incelenirler.$$, 'n8n-ai-judge', '2026-08-29 16:42:22.736211',
           now(), now()
    FROM topic
    WHERE slug = 'pull-requests'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Belirsiz bir başlıkla ve açıklama olmadan bir PR açmak, reviewer'ı değişikliğin neden var olduğunu yalnızca diff'ten tersine mühendislikle çıkarmaya bırakır.$$, TRUE, 0),
    ($$Değişiklikten emin olduğun sürece, incelemeyi beklemeden kendi PR'ını merge etmek sorun değildir.$$, FALSE, 1),
    ($$Birçok ilgisiz değişikliği kapsayan büyük PR'lar, küçük ve odaklı olanlar kadar hızlı incelenir.$$, FALSE, 2),
    ($$PR'ları küçük ve tek bir şeye odaklı tutmak, daha hızlı ve daha kapsamlı incelenmelerine yardımcı olur.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'pull-requests'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

