-- Arama sonuçlarında kesilen, 70 karakterden uzun seo_title değerlerini 60 karakterin
-- altına indirir (bkz. docs/google-seo-adsense-plan.md, Aşama 4). Yalnızca seo_title
-- değişir; title, seo_description ve içerik dosyalarına dokunulmaz. Slug + dil ile
-- eşleştiği için ortamdan bağımsızdır ve tekrar çalıştırılması aynı sonucu verir.
UPDATE topic_translation tt
SET seo_title = v.seo_title
FROM (VALUES
    ('autoconfiguration-properties', 'tr', 'Spring Boot Auto-Configuration ve Properties Nedir?'),
    ('build-deployment', 'en', 'Build & Deployment in React: npm run build and Vercel'),
    ('build-deployment', 'tr', 'React''te Build & Deployment: npm run build ve Vercel'),
    ('built-in-functional-interfaces', 'en', 'Java Built-in Functional Interfaces and Method References'),
    ('built-in-functional-interfaces', 'tr', 'Java Built-in Functional Interfaces ve Method Reference'),
    ('collectors', 'en', 'Java Stream Collectors: groupingBy, joining, toMap'),
    ('component-testing', 'en', 'React Component Testing: Vitest and React Testing Library'),
    ('component-testing', 'tr', 'React Component Testing: Vitest ve React Testing Library'),
    ('conditional-rendering', 'en', 'What Is Conditional Rendering in React? Simple Examples'),
    ('configuration-management', 'en', 'Centralized Configuration with Spring Cloud Config'),
    ('context-api', 'en', 'React Context API: createContext, useContext, Provider'),
    ('context-api', 'tr', 'React Context API: createContext, useContext, Provider'),
    ('controlled-components', 'en', 'What Are Controlled Components in React? Simple Examples'),
    ('deployment', 'tr', 'Spring Boot Mikroservislerini Docker ile Deploy Etmek'),
    ('developing-with-claude-code', 'en', 'AI-Assisted Software Development with Claude Code'),
    ('distributed-transactions', 'en', 'Distributed Transactions and Saga Pattern in Microservices'),
    ('distributed-transactions', 'tr', 'Mikroservislerde Distributed Transaction ve Saga Deseni'),
    ('error-boundaries', 'en', 'React Error Boundaries: componentDidCatch Explained'),
    ('error-boundaries', 'tr', 'React Error Boundaries: componentDidCatch ile Hata Yakalama'),
    ('fetching-data', 'en', 'Fetching Data in React with fetch: GET, POST, PUT, DELETE'),
    ('fetching-data', 'tr', 'React''te fetch ile Veri Çekmek: GET, POST, PUT, DELETE'),
    ('file-reading', 'tr', 'Java Dosya Okuma: Files ve BufferedReader Örnekleri'),
    ('file-writing', 'tr', 'Java Dosya Yazma: Files ve BufferedWriter Örnekleri'),
    ('lazy-loading-code-splitting', 'en', 'React Lazy Loading & Code Splitting: React.lazy, Suspense'),
    ('lazy-loading-code-splitting', 'tr', 'React Lazy Loading & Code Splitting: React.lazy, Suspense'),
    ('mapping-annotations-http-methods', 'en', 'Spring MVC Mapping Annotations: @GetMapping, @PostMapping'),
    ('mapping-annotations-http-methods', 'tr', 'Spring MVC Mapping Annotation''ları ve HTTP Metotları'),
    ('microservices-fundamentals', 'en', 'What Are Microservices? Monolith vs. Microservices'),
    ('optional', 'en', 'Java Optional: orElse, orElseGet, map, flatMap Examples'),
    ('optional', 'tr', 'Java Optional Nedir? orElse, orElseGet, map, flatMap'),
    ('portals', 'en', 'React Portals: createPortal, Modals, Event Bubbling'),
    ('portals', 'tr', 'React Portals: createPortal, Modal''lar, Event Bubbling'),
    ('production-docker-for-java-applications', 'en', 'Production Docker for Java: Caching, Non-Root, Health Checks'),
    ('queues-collections-utility', 'en', 'Java Queue, Deque, and the Collections Class with Examples'),
    ('react-performance', 'en', 'React Performance: React.memo, useMemo, useCallback'),
    ('react-performance', 'tr', 'React Performance: React.memo, useMemo, useCallback'),
    ('react-rest-api', 'en', 'Using React with a REST API: api.js Module and CRUD'),
    ('react-rest-api', 'tr', 'React ile REST API Kullanımı: api.js Modülü ve CRUD'),
    ('react-router-basics', 'en', 'React Router Basics: BrowserRouter, Routes, Route, Link'),
    ('react-router-basics', 'tr', 'React Router Basics: BrowserRouter, Routes, Route, Link'),
    ('react-spring-boot-deployment', 'en', 'React + Spring Boot Deployment: Vercel, Render, CORS'),
    ('react-spring-boot-deployment', 'tr', 'React + Spring Boot Deployment: Vercel, Render, CORS'),
    ('request-response-handling', 'en', '@RequestBody, ResponseEntity, and Status Codes in Spring MVC'),
    ('request-response-handling', 'tr', 'Spring MVC''de @RequestBody, ResponseEntity ve Durum Kodları'),
    ('resilience4j', 'tr', 'Spring Boot''ta Resilience4j: Circuit Breaker ve Retry'),
    ('rest-api-design', 'en', 'REST API Design in Spring MVC: DTOs, Pagination, Versioning'),
    ('rest-api-design', 'tr', 'Spring MVC''de REST API Tasarımı: DTO, Sayfalama, Versioning'),
    ('route-parameters-navigation', 'en', 'React Router: useParams, useNavigate, and Outlet'),
    ('route-parameters-navigation', 'tr', 'React Router: useParams, useNavigate ve Outlet'),
    ('sharing-state', 'en', 'Sharing State in React: Lifting State Up, Props Drilling'),
    ('sharing-state', 'tr', 'React''te State Paylaşımı: Lifting State Up, Props Drilling'),
    ('spring-boot-microservice-basics', 'en', 'How to Configure a Microservice with Spring Boot'),
    ('spring-mvc-fundamentals', 'en', 'What Is Spring MVC? DispatcherServlet and the MVC Pattern'),
    ('stream-fundamentals', 'en', 'What Is the Java Stream API? filter, map, flatMap Examples'),
    ('suspense', 'en', 'React Suspense: fallback, Nested Suspense, the use() Hook'),
    ('suspense', 'tr', 'React Suspense: fallback, İç İçe Suspense, use() Hook''u'),
    ('terminal-operations', 'en', 'Java Stream Terminal Operations: reduce, count, findFirst'),
    ('terminal-operations', 'tr', 'Java Stream Terminal Operations: reduce, count, findFirst'),
    ('transaction-management', 'tr', 'Spring Transaction Management ve @Transactional Nedir?'),
    ('use-memo-use-callback', 'en', 'What Are useMemo and useCallback in React?'),
    ('user-interaction-testing', 'en', 'React User Interaction Testing: user-event and vi.fn()'),
    ('user-interaction-testing', 'tr', 'React User Interaction Testing: user-event ve vi.fn()'),
    ('validation-exception-handling', 'en', 'Bean Validation and Exception Handling in Spring MVC'),
    ('validation-exception-handling', 'tr', 'Spring MVC''de Bean Validation ve Exception Handling')
) AS v(slug, language, seo_title)
JOIN topic t ON t.slug = v.slug
WHERE tt.topic_id = t.id
  AND tt.language = v.language;
