-- Portable promotion-style migration linking the EN Advanced Git &
-- Best Practices quiz questions to the topic's existing fixed quiz --
-- same pattern as git-fundamentals/V467-V468, working-with-commits/
-- V469-V470, undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, rebase-and-
-- squash/V479-V480, merge-conflicts/V481-V482, and stash/V483-V484
-- (see those files for the full rationale).
--
-- Development Question IDs: 275, 276, 277, 278, 279, 280, 281, 282, 283, 284
-- Topic: advanced-git-and-best-practices (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript. Two of the 10 are
-- CODE_OUTPUT questions grounded in the lesson's real `git reflog` and
-- `git blame` sample outputs (genuine command-output interpretation
-- scenarios, not forced -- see chat transcript for the review).
--
-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 275, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$According to the lesson, what does `git cherry-pick` do?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what does `git cherry-pick` do?$$, NULL, NULL,
           $$`git cherry-pick` copies one specific commit from anywhere in the repository onto your current branch — useful when exactly one fix from another branch is relevant to yours, without merging or rebasing the whole branch.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.781345',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Copies one specific commit from anywhere in the repository onto your current branch, without merging or rebasing the whole branch.$$, TRUE, 0),
    ($$Combines all commits from another branch into your current branch.$$, FALSE, 1),
    ($$Permanently deletes a commit from the repository's history.$$, FALSE, 2),
    ($$Renames a commit's message without changing its content.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 276, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$According to the lesson, what is `git reflog`?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is `git reflog`?$$, NULL, NULL,
           $$The reflog is local only — it's never pushed, never shared, and it's specific to your own clone, recording everywhere your HEAD has pointed.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.812031',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$A shared, team-wide log that's pushed to the remote along with your commits.$$, FALSE, 0),
    ($$A local, personal log of everywhere your HEAD has pointed — it's never pushed or shared, and specific to your own clone.$$, TRUE, 1),
    ($$A record of every file ever staged with `git add`.$$, FALSE, 2),
    ($$A public changelog automatically generated from commit messages.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 277, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$What does `git blame` show for each line of a file?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does `git blame` show for each line of a file?$$, NULL, NULL,
           $$`git blame` shows who last changed each line of a file, and in which commit — invaluable for understanding why a specific line exists.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.819415',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$How many times the line has ever been changed in total.$$, FALSE, 0),
    ($$Whether the line currently has a syntax error.$$, FALSE, 1),
    ($$Who last changed that line, and in which commit.$$, TRUE, 2),
    ($$Which branch the line currently exists on.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 278, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$Why does the lesson say Conventional Commits is worth repeating specifically as a team practice?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson say Conventional Commits is worth repeating specifically as a team practice?$$, NULL, NULL,
           $$When everyone on a team follows Conventional Commits consistently, `git log` becomes scannable at a glance, and tooling can auto-generate changelogs or determine version bumps from the commit history alone.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.825401',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Because Git refuses to accept commits that don't follow the convention.$$, FALSE, 0),
    ($$Because it's required for `git push` to succeed on a shared branch.$$, FALSE, 1),
    ($$Because it automatically resolves merge conflicts.$$, FALSE, 2),
    ($$When everyone on a team follows it consistently, `git log` becomes scannable at a glance, and tooling can auto-generate changelogs or determine version bumps from the commit history alone.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 279, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$Why does the lesson describe Git aliases as 'entirely personal'?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does the lesson describe Git aliases as 'entirely personal'?$$, NULL, NULL,
           $$Aliases live in your own Git config, not the project, so there's no risk of imposing them on teammates — that's why the lesson calls them entirely personal.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.83112',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$They live in your own Git config, not the project, so there's no risk of imposing them on teammates.$$, TRUE, 0),
    ($$They only work on your own machine's operating system.$$, FALSE, 1),
    ($$They expire automatically after a set number of uses.$$, FALSE, 2),
    ($$They can only be defined for read-only commands.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 280, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$You accidentally ran `git reset --hard`, which discarded a commit. You run `git reflog` and see the output above (taken from the lesson). Which hash would you reset back to in order to recover the discarded 'first attempt' commit?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You accidentally ran `git reset --hard`, which discarded a commit. You run `git reflog` and see the output above (taken from the lesson). Which hash would you reset back to in order to recover the discarded 'first attempt' commit?$$, $$a9f3e21 HEAD@{0}: commit: Add password validation
8a1b2c3 HEAD@{1}: reset: moving to HEAD~1
3c9d1a2 HEAD@{2}: commit: Add password validation (first attempt)$$, $$bash$$,
           $$The reflog line `3c9d1a2 HEAD@{2}: commit: Add password validation (first attempt)` records the earlier commit that was later reset away — resetting back to that hash recovers it, exactly the emergency recovery workflow the lesson describes.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.83759',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$`a9f3e21` — the commit shown at `HEAD@{0}`, the most recent entry.$$, FALSE, 0),
    ($$`3c9d1a2` — the commit shown at `HEAD@{2}`, described as "Add password validation (first attempt)".$$, TRUE, 1),
    ($$`8a1b2c3` — the commit shown at `HEAD@{1}`, described as a reset.$$, FALSE, 2),
    ($$None of the hashes in the reflog can recover a commit discarded by `git reset --hard`.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 281, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$You run `git blame PasswordValidator.java` and see the output above (taken from the lesson). According to it, who most recently added the line that throws `WeakPasswordException`?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You run `git blame PasswordValidator.java` and see the output above (taken from the lesson). According to it, who most recently added the line that throws `WeakPasswordException`?$$, $$a1b2c3d4 (Ada Lovelace  2026-08-10 14:22:03 +0300  12) if (password.length() < 8) {
e5f6a7b8 (Grace Hopper  2026-08-15 09:10:41 +0300  13)     throw new WeakPasswordException();$$, $$bash$$,
           $$`git blame` shows who last changed each line and in which commit — here, the line throwing `WeakPasswordException` (line 13) was last changed by Grace Hopper in commit `e5f6a7b8`, a different commit than the line above it.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.843939',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Ada Lovelace, in the commit shown as `a1b2c3d4`.$$, FALSE, 0),
    ($$Both lines were added in the same commit, by the same author.$$, FALSE, 1),
    ($$Grace Hopper, in the commit shown as `e5f6a7b8`.$$, TRUE, 2),
    ($$`git blame` doesn't show authorship, only line numbers.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 282, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$According to the lesson's Merge vs Rebase vs Squash vs Revert comparison, which of the following operations are safe to use on shared/already-pushed commits, because they don't rewrite history? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Merge vs Rebase vs Squash vs Revert comparison, which of the following operations are safe to use on shared/already-pushed commits, because they don't rewrite history? (Select all that apply)$$, NULL, NULL,
           $$`git merge` and `git revert` are both safe on shared/pushed commits because neither rewrites existing history; `git rebase` and squash both rewrite commit hashes, so the lesson says they're only safe on unshared, local commits.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.850172',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git rebase` — safe on shared commits because it only ever adds new commits.$$, FALSE, 0),
    ($$`git merge` — combines branches while preserving all commits, without rewriting shared history.$$, TRUE, 1),
    ($$Squash (via `rebase -i` or GitHub) — safe on shared commits, following the same rule as merge.$$, FALSE, 2),
    ($$`git revert` — undoes a commit by adding a new, opposite commit, without rewriting existing history.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 283, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes, which of the following are true? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes section warns against reaching for `cherry-pick` when a clearer merge or rebase would do, and against personal aliases leaking into project documentation that assumes a teammate has the same setup.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.85602',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$A bad `git reset --hard` or an accidentally deleted branch is usually permanently unrecoverable.$$, FALSE, 0),
    ($$`reflog` only exists on shared, remote repositories, never on a local clone.$$, FALSE, 1),
    ($$Reaching for `cherry-pick` when a proper merge or rebase would be clearer is a common mistake — cherry-pick is for genuinely isolated, one-off fixes.$$, TRUE, 2),
    ($$Personal Git aliases can leak into project documentation if you assume a teammate has the same aliases configured.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 284, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'en'
      AND question = $$According to the lesson's Best Practices and Git Best Practices for a Development Team, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Best Practices and Git Best Practices for a Development Team, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Best Practices recommend feature branches for everything and learning `git reflog` before you actually need it — not `--force` over `--force-with-lease`, and not `reset` over `revert` on shared commits.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.862154',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Feature branches should be used for everything — never commit directly to `main`.$$, TRUE, 0),
    ($$On the rare occasion a force push is genuinely needed, plain `--force` is preferred over `--force-with-lease` because it's simpler.$$, FALSE, 1),
    ($$Learning `git reflog` before you actually need it is recommended, since the moment you need it isn't the time to read documentation for the first time.$$, TRUE, 2),
    ($$The safest default is to reach for `reset` over `revert` even on shared, already-pushed commits.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

