-- Portable promotion-style migration linking the TR Advanced Git &
-- Best Practices quiz questions to the topic's existing fixed quiz --
-- same pattern as git-fundamentals/V467-V468, working-with-commits/
-- V469-V470, undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, pull-requests/V477-V478, rebase-and-
-- squash/V479-V480, merge-conflicts/V481-V482, and stash/V483-V484
-- (see those files for the full rationale).
--
-- Development Question IDs: 285, 286, 287, 288, 289, 290, 291, 292, 293, 294
-- Topic: advanced-git-and-best-practices (language: tr)
-- Turkish counterparts of the English questions in V485 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 285, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Derse göre `git cherry-pick` ne yapar?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre `git cherry-pick` ne yapar?$$, NULL, NULL,
           $$`git cherry-pick`, repository'nin herhangi bir yerinden belirli tek bir commit'i mevcut branch'ine kopyalar — tüm branch'i merge etmeden ya da rebase etmeden, başka bir branch'ten tam olarak tek bir düzeltmenin seninkiyle ilgili olduğu durumlarda işine yarar.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.872211',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Repository'nin herhangi bir yerinden belirli tek bir commit'i mevcut branch'ine kopyalar, tüm branch'i merge etmeden ya da rebase etmeden.$$, TRUE, 0),
    ($$Başka bir branch'teki tüm commit'leri mevcut branch'inle birleştirir.$$, FALSE, 1),
    ($$Bir commit'i repository'nin geçmişinden kalıcı olarak siler.$$, FALSE, 2),
    ($$Bir commit'in mesajını, içeriğini değiştirmeden yeniden adlandırır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 286, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Derse göre `git reflog` nedir?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre `git reflog` nedir?$$, NULL, NULL,
           $$Reflog yalnızca yereldir — asla push edilmez, asla paylaşılmaz, ve senin kendi clone'una özeldir, HEAD'inin işaret ettiği her yeri kaydeder.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.893256',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Commit'lerinle birlikte remote'a push edilen, paylaşılan, takım genelinde bir günlük.$$, FALSE, 0),
    ($$HEAD'inin işaret ettiği her yerin yerel, kişisel bir günlüğü — asla push edilmez ya da paylaşılmaz, ve senin kendi clone'una özeldir.$$, TRUE, 1),
    ($$`git add` ile stage edilmiş her dosyanın bir kaydı.$$, FALSE, 2),
    ($$Commit mesajlarından otomatik olarak üretilen genel bir changelog.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 287, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$`git blame`, bir dosyanın her satırı için neyi gösterir?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git blame`, bir dosyanın her satırı için neyi gösterir?$$, NULL, NULL,
           $$`git blame`, bir dosyanın her satırını en son kimin değiştirdiğini ve hangi commit'te değiştirdiğini gösterir — belirli bir satırın neden var olduğunu anlamak için paha biçilmezdir.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.900862',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Satırın toplamda kaç kez değiştirildiğini.$$, FALSE, 0),
    ($$Satırın şu anda bir sözdizimi hatası olup olmadığını.$$, FALSE, 1),
    ($$O satırı en son kimin değiştirdiğini, ve hangi commit'te değiştirdiğini.$$, TRUE, 2),
    ($$Satırın şu anda hangi branch'te bulunduğunu.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 288, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Ders, Conventional Commits'in özellikle bir takım pratiği olarak tekrarlanmaya değer olduğunu neden söylüyor?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, Conventional Commits'in özellikle bir takım pratiği olarak tekrarlanmaya değer olduğunu neden söylüyor?$$, NULL, NULL,
           $$Bir takımdaki herkes Conventional Commits'i tutarlı bir şekilde takip ettiğinde, `git log` bir bakışta taranabilir hale gelir, ve araçlar changelog'ları otomatik üretebilir ya da sürüm artışlarını yalnızca commit geçmişinden belirleyebilir.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.907697',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Çünkü Git, konvansiyonu takip etmeyen commit'leri kabul etmeyi reddeder.$$, FALSE, 0),
    ($$Çünkü paylaşılan bir branch'te `git push`'un başarılı olması için gereklidir.$$, FALSE, 1),
    ($$Çünkü merge conflict'lerini otomatik olarak çözer.$$, FALSE, 2),
    ($$Bir takımdaki herkes bunu tutarlı bir şekilde takip ettiğinde, `git log` bir bakışta taranabilir hale gelir, ve araçlar changelog'ları otomatik üretebilir ya da sürüm artışlarını yalnızca commit geçmişinden belirleyebilir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 289, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Ders, Git alias'larını neden 'tamamen kişisel' olarak tanımlıyor?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, Git alias'larını neden 'tamamen kişisel' olarak tanımlıyor?$$, NULL, NULL,
           $$Alias'lar, projede değil, kendi Git yapılandırmanda yaşarlar, bu yüzden onları takım arkadaşlarına dayatma riski yoktur — ders bu yüzden onları tamamen kişisel olarak adlandırıyor.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.913995',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Projede değil, kendi Git yapılandırmanda yaşarlar, bu yüzden onları takım arkadaşlarına dayatma riski yoktur.$$, TRUE, 0),
    ($$Yalnızca kendi makinenin işletim sisteminde çalışırlar.$$, FALSE, 1),
    ($$Belirli bir kullanım sayısından sonra otomatik olarak sona ererler.$$, FALSE, 2),
    ($$Yalnızca salt-okunur komutlar için tanımlanabilirler.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 290, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Yanlışlıkla `git reset --hard` çalıştırdın, bu da bir commit'i attı. `git reflog` çalıştırıyorsun ve yukarıdaki çıktıyı görüyorsun (dersten alınmıştır). Atılan 'first attempt' commit'ini kurtarmak için hangi hash'e reset etmelisin?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Yanlışlıkla `git reset --hard` çalıştırdın, bu da bir commit'i attı. `git reflog` çalıştırıyorsun ve yukarıdaki çıktıyı görüyorsun (dersten alınmıştır). Atılan 'first attempt' commit'ini kurtarmak için hangi hash'e reset etmelisin?$$, $$a9f3e21 HEAD@{0}: commit: Add password validation
8a1b2c3 HEAD@{1}: reset: moving to HEAD~1
3c9d1a2 HEAD@{2}: commit: Add password validation (first attempt)$$, $$bash$$,
           $$`3c9d1a2 HEAD@{2}: commit: Add password validation (first attempt)` reflog satırı, daha sonra reset ile atılan daha önceki commit'i kaydeder — o hash'e geri reset etmek, dersin anlattığı tam olarak acil durum kurtarma iş akışıyla onu kurtarır.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.919931',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$`a9f3e21` — `HEAD@{0}`'da gösterilen, en son giriş olan commit.$$, FALSE, 0),
    ($$`3c9d1a2` — `HEAD@{2}`'de gösterilen, "Add password validation (first attempt)" olarak tanımlanan commit.$$, TRUE, 1),
    ($$`8a1b2c3` — `HEAD@{1}`'de gösterilen, bir reset olarak tanımlanan commit.$$, FALSE, 2),
    ($$Reflog'daki hash'lerin hiçbiri, `git reset --hard` ile atılan bir commit'i kurtaramaz.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 291, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$`git blame PasswordValidator.java` çalıştırıyorsun ve yukarıdaki çıktıyı görüyorsun (dersten alınmıştır). Buna göre, `WeakPasswordException` fırlatan satırı en son kim eklemiştir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'CODE_OUTPUT', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git blame PasswordValidator.java` çalıştırıyorsun ve yukarıdaki çıktıyı görüyorsun (dersten alınmıştır). Buna göre, `WeakPasswordException` fırlatan satırı en son kim eklemiştir?$$, $$a1b2c3d4 (Ada Lovelace  2026-08-10 14:22:03 +0300  12) if (password.length() < 8) {
e5f6a7b8 (Grace Hopper  2026-08-15 09:10:41 +0300  13)     throw new WeakPasswordException();$$, $$bash$$,
           $$`git blame`, her satırı en son kimin ve hangi commit'te değiştirdiğini gösterir — burada, `WeakPasswordException` fırlatan satır (13. satır) en son Grace Hopper tarafından `e5f6a7b8` commit'inde değiştirilmiş, üstündeki satırdan (12. satır) farklı bir commit'te.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.925933',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Ada Lovelace, `a1b2c3d4` olarak gösterilen commit'te.$$, FALSE, 0),
    ($$Her iki satır da aynı commit'te, aynı yazar tarafından eklenmiştir.$$, FALSE, 1),
    ($$Grace Hopper, `e5f6a7b8` olarak gösterilen commit'te.$$, TRUE, 2),
    ($$`git blame` yazarlık göstermez, yalnızca satır numaralarını gösterir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 292, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Dersin Merge vs Rebase vs Squash vs Revert karşılaştırmasına göre, aşağıdaki işlemlerden hangileri, geçmişi yeniden yazmadıkları için paylaşılan/zaten push edilmiş commit'lerde kullanmak açısından güvenlidir? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Merge vs Rebase vs Squash vs Revert karşılaştırmasına göre, aşağıdaki işlemlerden hangileri, geçmişi yeniden yazmadıkları için paylaşılan/zaten push edilmiş commit'lerde kullanmak açısından güvenlidir? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git merge` ve `git revert`, ikisi de paylaşılan/push edilmiş commit'lerde güvenlidir çünkü ikisi de var olan geçmişi yeniden yazmaz; `git rebase` ve squash ise ikisi de commit hash'lerini yeniden yazar, bu yüzden ders bunların yalnızca paylaşılmamış, yerel commit'lerde güvenli olduğunu söylüyor.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.931574',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`git rebase` — yalnızca yeni commit'ler eklediği için paylaşılan commit'lerde güvenlidir.$$, FALSE, 0),
    ($$`git merge` — branch'leri, tüm commit'leri koruyarak birleştirir, paylaşılan geçmişi yeniden yazmadan.$$, TRUE, 1),
    ($$Squash (`rebase -i` ya da GitHub ile) — merge ile aynı kuralı izleyerek paylaşılan commit'lerde güvenlidir.$$, FALSE, 2),
    ($$`git revert` — var olan geçmişi yeniden yazmadan, yeni, tersine bir commit ekleyerek bir commit'i geri alır.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 293, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar bölümüne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar bölümüne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, daha net bir merge ya da rebase yeterliyken `cherry-pick`'e başvurmaya karşı ve bir takım arkadaşının aynı kuruluma sahip olduğunu varsayan proje dokümantasyonuna kişisel alias'ların sızmasına karşı uyarıyor.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.937642',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Kötü bir `git reset --hard` ya da yanlışlıkla silinen bir branch genellikle kalıcı olarak kurtarılamaz.$$, FALSE, 0),
    ($$`reflog`, yalnızca paylaşılan, remote repository'lerde vardır, asla yerel bir clone'da değil.$$, FALSE, 1),
    ($$Düzgün bir merge ya da rebase daha net olacakken `cherry-pick`'e başvurmak yaygın bir hatadır — cherry-pick, gerçekten izole, tek seferlik düzeltmeler içindir.$$, TRUE, 2),
    ($$Bir takım arkadaşının aynı alias'ları yapılandırdığını varsayarsan, kişisel Git alias'ları proje dokümantasyonuna sızabilir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 294, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'advanced-git-and-best-practices')
      AND language = 'tr'
      AND question = $$Dersin En İyi Pratikler'ine ve Bir Geliştirme Takımı için Git En İyi Pratikleri'ne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin En İyi Pratikler'ine ve Bir Geliştirme Takımı için Git En İyi Pratikleri'ne göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin En İyi Pratikler'i, her şey için feature branch kullanmayı ve `git reflog`'u gerçekten ihtiyacın olmadan önce öğrenmeyi öneriyor — `--force-with-lease` yerine `--force`'u değil, ve paylaşılan commit'lerde `revert` yerine `reset`'i değil.$$, 'n8n-ai-judge', '2026-08-30 00:36:51.942951',
           now(), now()
    FROM topic
    WHERE slug = 'advanced-git-and-best-practices'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Her şey için feature branch'ler kullanılmalıdır — asla doğrudan `main`'e commit etme.$$, TRUE, 0),
    ($$Bir force push gerçekten gerektiğinde, nadir durumda, düz `--force`, daha basit olduğu için `--force-with-lease`'e tercih edilir.$$, FALSE, 1),
    ($$`git reflog`'u gerçekten ihtiyacın olmadan önce öğrenmek önerilir, çünkü ihtiyacın olduğu an dokümantasyonu ilk kez okuyacağın an değildir.$$, TRUE, 2),
    ($$En güvenli varsayılan, paylaşılan, zaten push edilmiş commit'lerde bile `revert` yerine `reset`'e başvurmaktır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'advanced-git-and-best-practices'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

