-- Portable promotion-style migration linking the EN Branches & Merging
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470, and
-- undoing-changes/V471-V472 (see those files for the full rationale).
--
-- Development Question IDs: 155, 156, 157, 158, 159, 160, 161, 162, 163, 164
-- Topic: branches-and-merging (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 155, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$According to the lesson, what is a branch, fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is a branch, fundamentally?$$, NULL, NULL,
           $$A branch is a lightweight, movable pointer to a commit — when you commit, the branch you're on simply moves forward to point at the new commit. It's not a copy of the project or a separate repository.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.715248',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$A movable pointer to a commit.$$, TRUE, 0),
    ($$A full copy of the entire project's files.$$, FALSE, 1),
    ($$A permanent, unchangeable snapshot of one point in history.$$, FALSE, 2),
    ($$A separate repository connected to the main one.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 156, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$What, technically, makes `main` different from any other branch?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What, technically, makes `main` different from any other branch?$$, NULL, NULL,
           $$`main` is just a branch like any other — it has no special technical status, only a conventional one as the primary line of development. Nothing in Git prevents deleting, renaming, or committing directly on other branches.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.740041',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$`main` is the only branch that can contain merge commits.$$, FALSE, 0),
    ($$Nothing — `main` has no special technical status, only a conventional one as the primary line of development.$$, TRUE, 1),
    ($$`main` cannot be deleted or renamed.$$, FALSE, 2),
    ($$`main` automatically merges any other branch that is created.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 157, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$After resolving a merge conflict by editing the file, what completes the merge?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$After resolving a merge conflict by editing the file, what completes the merge?$$, NULL, NULL,
           $$After editing the file to resolve the conflict, you stage it with `git add` and complete the merge with `git commit` — that's the two-step finish the lesson describes.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.750193',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Running `git switch -c` again on the same branch.$$, FALSE, 0),
    ($$Running `git branch -D` on the branch you're merging.$$, FALSE, 1),
    ($$Staging the resolved file with `git add` and then running `git commit`.$$, TRUE, 2),
    ($$Deleting the conflicting branch and starting the merge over.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 158, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$Which command creates a new branch and switches onto it in a single step?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which command creates a new branch and switches onto it in a single step?$$, NULL, NULL,
           $$`git switch -c <name>` is the combined, everyday command — it creates a new branch and moves you onto it in one step, unlike plain `git branch <name>` which only creates it.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.75785',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$git branch <name>$$, FALSE, 0),
    ($$git branch -m <name>$$, FALSE, 1),
    ($$git merge <name>$$, FALSE, 2),
    ($$git switch -c <name>$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 159, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$Which of the following are true about `git branch -d` and `git branch -D`? (Select all that apply)$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about `git branch -d` and `git branch -D`? (Select all that apply)$$, NULL, NULL,
           $$`git branch -d` is the safe delete — it refuses if the branch isn't fully merged. `git branch -D` force-deletes even an unmerged branch, discarding any commits that only exist there.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.765602',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$`git branch -d` is a safe delete that refuses to delete a branch that isn't fully merged.$$, TRUE, 0),
    ($$`git branch -D` is the safe delete option, while `-d` force-deletes unmerged branches.$$, FALSE, 1),
    ($$`git branch -D` force-deletes a branch even if its work hasn't been merged yet.$$, TRUE, 2),
    ($$Both `-d` and `-D` require the branch to be merged into `main` first.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 160, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$How many parent commits does a merge commit have?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$How many parent commits does a merge commit have?$$, NULL, NULL,
           $$A merge commit has two parents — one from each branch being merged — which is what distinguishes it from every other kind of commit in the history.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.773804',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Two — one from each branch being merged.$$, TRUE, 0),
    ($$One, the branch that received the merge.$$, FALSE, 1),
    ($$Three, including a common ancestor.$$, FALSE, 2),
    ($$None — a merge commit has no parents.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 161, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$Which of the following are true about a fast-forward merge? (Select all that apply)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about a fast-forward merge? (Select all that apply)$$, NULL, NULL,
           $$A fast-forward merge happens when `main` hasn't moved since the feature branch was created — Git just moves `main`'s pointer forward to the feature branch's latest commit, without creating a new commit.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.7815',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$It creates a new commit with two parents.$$, FALSE, 0),
    ($$It happens when `main` hasn't moved since the feature branch was created.$$, TRUE, 1),
    ($$It only works if the feature branch has already been deleted.$$, FALSE, 2),
    ($$Git simply moves the branch pointer forward to the feature branch's latest commit — no new commit is created.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 162, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$Why does Git create a merge commit instead of performing a fast-forward merge?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does Git create a merge commit instead of performing a fast-forward merge?$$, NULL, NULL,
           $$If `main` has moved forward since the feature branch was created, a fast-forward isn't possible, so Git creates a new merge commit with two parents instead.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.789062',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Because the feature branch has more than one commit.$$, FALSE, 0),
    ($$Because you ran `git branch -D` before merging.$$, FALSE, 1),
    ($$Because `main` has moved forward since the feature branch was created, so a fast-forward isn't possible.$$, TRUE, 2),
    ($$Because you switched branches without committing first.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 163, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$What causes a merge conflict?$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What causes a merge conflict?$$, NULL, NULL,
           $$A merge conflict happens when both branches changed the same lines of the same file in different ways, so Git can't automatically decide which version is correct and stops to ask you to resolve it manually.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.796347',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$One of the two branches was deleted before the merge ran.$$, FALSE, 0),
    ($$Both branches changed the same lines of the same file in different ways, so Git can't automatically decide which version is correct.$$, TRUE, 1),
    ($$The feature branch was created too long ago.$$, FALSE, 2),
    ($$You forgot to run `git branch -v` before merging.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 164, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes warns against committing directly on `main`, and its Best Practices recommend deleting branches immediately after merging since their history is preserved in `main` at no cost.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.803654',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Committing directly on `main` instead of creating a feature branch makes it harder to keep `main` always in a working, deployable state.$$, TRUE, 0),
    ($$Merged branches should be kept around indefinitely as a backup.$$, FALSE, 1),
    ($$`git status` never shows which branch you're currently on.$$, FALSE, 2),
    ($$Deleting a branch immediately after merging costs nothing, since its history lives on in `main`.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

