-- Portable promotion-style migration linking the TR Branches & Merging
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470, and
-- undoing-changes/V471-V472 (see those files for the full rationale).
--
-- Development Question IDs: 165, 166, 167, 168, 169, 170, 171, 172, 173, 174
-- Topic: branches-and-merging (language: tr)
-- Turkish counterparts of the English questions in V473 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 165, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Derse göre bir branch, temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir branch, temelde nedir?$$, NULL, NULL,
           $$Bir branch, bir commit'e işaret eden hafif, hareketli bir pointer'dır — commit attığında üzerinde olduğun branch yalnızca ileri hareket eder ve yeni commit'e işaret eder. Projenin bir kopyası ya da ayrı bir repository değildir.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.81073',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Bir commit'e işaret eden hareketli bir pointer.$$, TRUE, 0),
    ($$Projenin tüm dosyalarının tam bir kopyası.$$, FALSE, 1),
    ($$Geçmişte bir noktanın kalıcı, değiştirilemez bir görüntüsü.$$, FALSE, 2),
    ($$Ana repository'ye bağlı ayrı bir repository.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 166, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$`main`'i diğer branch'lerden teknik olarak farklı kılan nedir?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`main`'i diğer branch'lerden teknik olarak farklı kılan nedir?$$, NULL, NULL,
           $$`main`, diğerleri gibi yalnızca bir branch'tir — teknik olarak özel bir statüsü yoktur, yalnızca birincil geliştirme hattı olarak konvansiyonel bir statüsü vardır. Git'te başka branch'leri silmeyi, yeniden adlandırmayı ya da üzerlerine doğrudan commit atmayı engelleyen hiçbir şey yoktur.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.817922',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$`main`, merge commit içerebilen tek branch'tir.$$, FALSE, 0),
    ($$Hiçbir şey — `main`'in teknik olarak özel bir statüsü yoktur, yalnızca birincil geliştirme hattı olarak konvansiyonel bir statüsü vardır.$$, TRUE, 1),
    ($$`main` silinemez ya da yeniden adlandırılamaz.$$, FALSE, 2),
    ($$`main`, oluşturulan her branch'i otomatik olarak kendine merge eder.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 167, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Dosyayı düzenleyerek bir merge conflict'i çözdükten sonra, merge'i tamamlayan nedir?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dosyayı düzenleyerek bir merge conflict'i çözdükten sonra, merge'i tamamlayan nedir?$$, NULL, NULL,
           $$Conflict'i çözmek için dosyayı düzenledikten sonra, dosyayı `git add` ile stage'ler, sonra `git commit` ile merge'i tamamlarsın — dersin anlattığı iki adımlı bitiriş budur.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.825359',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Aynı branch'te tekrar `git switch -c` çalıştırmak.$$, FALSE, 0),
    ($$Merge ettiğin branch'te `git branch -D` çalıştırmak.$$, FALSE, 1),
    ($$Çözülen dosyayı `git add` ile stage'lemek, sonra `git commit` çalıştırmak.$$, TRUE, 2),
    ($$Çakışan branch'i silip merge'e baştan başlamak.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 168, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Hangi komut yeni bir branch oluşturur ve tek adımda üzerine geçer?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Hangi komut yeni bir branch oluşturur ve tek adımda üzerine geçer?$$, NULL, NULL,
           $$`git switch -c <name>`, birleşik, gündelik komuttur — yeni bir branch oluşturur ve tek adımda üzerine geçer, yalnızca oluşturan `git branch <name>`'in aksine.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.83212',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$git branch <name>$$, FALSE, 0),
    ($$git branch -m <name>$$, FALSE, 1),
    ($$git merge <name>$$, FALSE, 2),
    ($$git switch -c <name>$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 169, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$`git branch -d` ve `git branch -D` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git branch -d` ve `git branch -D` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`git branch -d`, tamamen merge edilmemişse reddeden güvenli silme işlemidir. `git branch -D` ise merge edilmemiş bir branch'i bile zorla siler, yalnızca orada var olan commit'leri kaybetme pahasına.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.840875',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$`git branch -d`, tamamen merge edilmemiş bir branch'i silmeyi reddeden güvenli bir silme işlemidir.$$, TRUE, 0),
    ($$`git branch -D` güvenli silme seçeneğidir, `-d` ise merge edilmemiş branch'leri zorla siler.$$, FALSE, 1),
    ($$`git branch -D`, işi henüz merge edilmemiş olsa bile bir branch'i zorla siler.$$, TRUE, 2),
    ($$Hem `-d` hem `-D`, branch'in önce `main`'e merge edilmiş olmasını gerektirir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 170, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Bir merge commit'in kaç ebeveyn commit'i vardır?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bir merge commit'in kaç ebeveyn commit'i vardır?$$, NULL, NULL,
           $$Bir merge commit'in iki ebeveyni vardır — merge edilen her branch'ten biri — bu da onu geçmişteki her diğer commit türünden ayıran şeydir.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.847116',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$İki — merge edilen her branch'ten biri.$$, TRUE, 0),
    ($$Bir, merge'i alan branch.$$, FALSE, 1),
    ($$Üç, ortak bir ata dahil.$$, FALSE, 2),
    ($$Hiç — bir merge commit'in ebeveyni yoktur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 171, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Fast-forward merge hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Fast-forward merge hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Fast-forward merge, `main` feature branch oluşturulduğundan beri hareket etmediyse gerçekleşir — Git yalnızca `main`'in pointer'ını feature branch'in son commit'ine ileri taşır, yeni bir commit oluşturmadan.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.85358',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$İki ebeveynli yeni bir commit oluşturur.$$, FALSE, 0),
    ($$`main`, feature branch oluşturulduğundan beri hiç hareket etmediyse gerçekleşir.$$, TRUE, 1),
    ($$Yalnızca feature branch önceden silinmişse çalışır.$$, FALSE, 2),
    ($$Git yalnızca branch pointer'ını feature branch'in son commit'ine ileri taşır — yeni bir commit oluşturulmaz.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 172, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Git neden fast-forward yapmak yerine bir merge commit oluşturur?$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Git neden fast-forward yapmak yerine bir merge commit oluşturur?$$, NULL, NULL,
           $$Eğer `main`, feature branch oluşturulduğundan beri ilerlediyse, bir fast-forward mümkün değildir, bu yüzden Git bunun yerine iki ebeveynli yeni bir merge commit oluşturur.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.860195',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$Feature branch'in birden fazla commit'i olduğu için.$$, FALSE, 0),
    ($$Merge etmeden önce `git branch -D` çalıştırdığın için.$$, FALSE, 1),
    ($$Feature branch oluşturulduğundan beri `main` ilerlediği için, bir fast-forward mümkün olmadığından.$$, TRUE, 2),
    ($$Commit etmeden branch değiştirdiğin için.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 173, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Bir merge conflict'e neden olan şey nedir?$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Bir merge conflict'e neden olan şey nedir?$$, NULL, NULL,
           $$Bir merge conflict, her iki branch de aynı dosyanın aynı satırlarını farklı şekillerde değiştirdiğinde olur, bu yüzden Git hangi sürümün doğru olduğuna otomatik karar veremez ve senden elle çözmeni istemek için durur.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.867298',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$İki branch'ten biri merge çalıştırılmadan önce silindi.$$, FALSE, 0),
    ($$Her iki branch de aynı dosyanın aynı satırlarını farklı şekillerde değiştirdi, bu yüzden Git hangi sürümün doğru olduğuna otomatik karar veremiyor.$$, TRUE, 1),
    ($$Feature branch çok uzun süre önce oluşturuldu.$$, FALSE, 2),
    ($$Merge etmeden önce `git branch -v` çalıştırmayı unuttun.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 174, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'branches-and-merging')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü doğrudan `main` üzerinde commit atmaya karşı uyarıyor, En İyi Pratikler bölümü ise merge ettikten hemen sonra branch'leri silmeyi öneriyor çünkü geçmişleri `main`'de maliyetsizce korunuyor.$$, 'n8n-ai-judge', '2026-08-29 15:28:04.875034',
           now(), now()
    FROM topic
    WHERE slug = 'branches-and-merging'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Önce bir feature branch oluşturmak yerine doğrudan `main` üzerinde commit atmak, `main`'i her zaman çalışır, deploy edilebilir bir durumda tutmayı zorlaştırır.$$, TRUE, 0),
    ($$Merge edilmiş branch'ler bir yedek olarak süresiz saklanmalıdır.$$, FALSE, 1),
    ($$`git status` hangi branch'te olduğunu asla göstermez.$$, FALSE, 2),
    ($$Merge ettikten hemen sonra bir branch'i silmenin hiçbir maliyeti yoktur, çünkü geçmişi `main`'de yaşamaya devam eder.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'branches-and-merging'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

