-- Portable promotion-style migration linking the EN Rebase & Squash
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, and pull-requests/V477-V478 (see those
-- files for the full rationale).
--
-- Development Question IDs: 215, 216, 217, 218, 219, 220, 221, 222, 223, 224
-- Topic: rebase-and-squash (language: en)
-- These 10 questions were generated by Claude and auto-published via the
-- project's existing AI-Judge auto-publish endpoint (POST
-- /api/internal/questions/{id}/auto-publish), after a structural/quality
-- self-review (option counts, correct-option counts, duplicate check,
-- answer-position distribution) -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='en', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='en' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 215, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$According to the lesson, what is rebasing, fundamentally?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, what is rebasing, fundamentally?$$, NULL, NULL,
           $$Rebasing takes the commits from one branch and replays them, one by one, on top of a different starting point — the replayed commits get new hashes, but the content of the work is preserved exactly.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.698464',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Taking the commits from one branch and replaying them, one by one, on top of a different starting point — the commits get new hashes but the content is preserved.$$, TRUE, 0),
    ($$Deleting a branch's commits and starting its history over from scratch.$$, FALSE, 1),
    ($$A way to permanently merge two branches without creating any new commits.$$, FALSE, 2),
    ($$A GitHub-only feature that has no local Git command equivalent.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 216, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$According to the lesson, how does the resulting history differ between a merge and a rebase?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson, how does the resulting history differ between a merge and a rebase?$$, NULL, NULL,
           $$Merge preserves exactly what happened, including a merge commit; rebase rewrites the branch's commits into a clean, linear story, at the cost of no longer perfectly reflecting what actually happened.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.727617',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Merge always produces a linear history, while rebase always produces a merge commit.$$, FALSE, 0),
    ($$Merge preserves exactly what happened, including a merge commit; rebase rewrites the branch's commits into a clean, linear story that no longer perfectly reflects what actually happened.$$, TRUE, 1),
    ($$Both produce identical histories — the only difference is which command you type.$$, FALSE, 2),
    ($$Rebase preserves the original commit hashes, while merge always creates new ones.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 217, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$You run `git rebase main` on your feature branch, and `main` hasn't changed at all since you branched off it. What happens?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$You run `git rebase main` on your feature branch, and `main` hasn't changed at all since you branched off it. What happens?$$, NULL, NULL,
           $$If `main` hasn't changed since you branched off it, there's nothing new for your commits to be replayed on top of, so the rebase has nothing to do.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.736856',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Git deletes your feature branch's commits since they're now redundant.$$, FALSE, 0),
    ($$Git creates a merge commit combining the two branches.$$, FALSE, 1),
    ($$There's nothing to do — since `main` hasn't moved, there's nothing new to replay your commits on top of.$$, TRUE, 2),
    ($$Git refuses to run the rebase and shows an error.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 218, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$What does `git rebase -i` let you do that a plain `git rebase` does not?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does `git rebase -i` let you do that a plain `git rebase` does not?$$, NULL, NULL,
           $$`git rebase -i` opens an editor listing your branch's commits and lets you decide what happens to each one — reorder, combine, edit, or drop them — not just replay them like a plain rebase.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.745909',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Rebase onto a remote branch instead of a local one.$$, FALSE, 0),
    ($$Skip conflict resolution entirely.$$, FALSE, 1),
    ($$Rebase without changing any commit hashes.$$, FALSE, 2),
    ($$Decide what happens to each individual commit — reorder, combine, edit, or drop them, not just replay them.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 219, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$In an interactive rebase, what's the difference between `squash` and `fixup`?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$In an interactive rebase, what's the difference between `squash` and `fixup`?$$, NULL, NULL,
           $$Both `squash` and `fixup` merge a commit into the one above it, but `fixup` silently discards the fixed-up commit's message, while `squash` lets you write a new, combined commit message.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.754547',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$Both merge a commit into the one above it, but `fixup` silently discards the fixed-up commit's message while `squash` lets you write a new combined message.$$, TRUE, 0),
    ($$`squash` deletes the commit entirely, while `fixup` keeps it as a separate commit.$$, FALSE, 1),
    ($$`fixup` can only be used on the very first commit in the list, while `squash` can be used anywhere.$$, FALSE, 2),
    ($$`squash` and `fixup` are two different names for exactly the same operation, with no difference at all.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 220, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$What does the lesson call 'the single most important rule about rebase'?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$What does the lesson call 'the single most important rule about rebase'?$$, NULL, NULL,
           $$The lesson explicitly calls this 'the single most important rule about rebase': never rebase commits that other people have already pulled, since it gives every replayed commit a new hash and diverges their history from yours.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.762081',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Always run `git rebase -i` instead of a plain `git rebase`.$$, FALSE, 0),
    ($$Never rebase commits that other people have already pulled.$$, TRUE, 1),
    ($$Always squash every commit before merging a Pull Request.$$, FALSE, 2),
    ($$Never use `git rebase --abort` once a rebase has started.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 221, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$Why does a normal `git push` get rejected after you rebase a branch that's already been pushed?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Why does a normal `git push` get rejected after you rebase a branch that's already been pushed?$$, NULL, NULL,
           $$Rebasing gives your commits new hashes, so your local branch and its already-pushed remote counterpart now have different histories — Git sees the remote as having commits you don't have and refuses the push as a safety check.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.768737',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Because `git push` is disabled while any rebase is in progress.$$, FALSE, 0),
    ($$Because rebased branches can only be pushed by a repository admin.$$, FALSE, 1),
    ($$Because rebasing gives your commits new hashes, so Git sees the remote as having commits you don't have and refuses as a safety check.$$, TRUE, 2),
    ($$Because GitHub blocks all pushes to branches involved in an open Pull Request.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 222, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$Which of the following are true about `git push --force` vs `git push --force-with-lease`? (Select all that apply)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about `git push --force` vs `git push --force-with-lease`? (Select all that apply)$$, NULL, NULL,
           $$`--force` overwrites the remote branch unconditionally, silently discarding any commits pushed there since your last fetch. `--force-with-lease` checks first and refuses if the remote has changed unexpectedly, failing safely instead.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.776298',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`--force` overwrites the remote branch unconditionally, including any commits someone else may have pushed since you last fetched.$$, TRUE, 0),
    ($$`--force-with-lease` always fails, even if nobody else has changed the remote branch.$$, FALSE, 1),
    ($$`--force-with-lease` checks first and refuses if the remote branch has changed since your last fetch.$$, TRUE, 2),
    ($$`--force` and `--force-with-lease` behave identically in every situation.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 223, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$Which of the following are true about resolving conflicts during a rebase, according to the lesson? (Select all that apply)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Which of the following are true about resolving conflicts during a rebase, according to the lesson? (Select all that apply)$$, NULL, NULL,
           $$After resolving a conflicted file during a rebase, you stage it and run `git rebase --continue` to resume. `git rebase --abort` is always safe — it cancels the whole rebase and returns you to exactly where you started.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.782913',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$A rebase conflict can only ever happen once, at the very end of the whole process.$$, FALSE, 0),
    ($$After resolving a conflicted file, you stage it and run `git rebase --continue` to resume.$$, TRUE, 1),
    ($$`git rebase --abort` is dangerous and can leave your branch in a broken, unpredictable state.$$, FALSE, 2),
    ($$`git rebase --abort` cancels the whole rebase and safely returns you to exactly where you started.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 224, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'en'
      AND question = $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'en', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$According to the lesson's Common Mistakes and Best Practices, which of the following are true? (Select all that apply)$$, NULL, NULL,
           $$The lesson's Common Mistakes calls rebasing already-pulled commits the single most common way rebase causes real problems, and its Best Practices recommend using `git rebase -i` to squash 'fix typo'-style commits before requesting review.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.789396',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Rebasing a branch other people have already pulled is the single most common way rebase causes real problems on a team.$$, TRUE, 0),
    ($$You should default to plain `--force` rather than `--force-with-lease` since it's simpler to type.$$, FALSE, 1),
    ($$Once a rebase conflict starts, aborting it is unsafe and should be avoided at all costs.$$, FALSE, 2),
    ($$A good practice is to use `git rebase -i` to squash 'fix typo'-style commits into their parent before requesting review.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'en'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

