-- Portable promotion-style migration linking the TR Rebase & Squash
-- quiz questions to the topic's existing fixed quiz -- same pattern as
-- git-fundamentals/V467-V468, working-with-commits/V469-V470,
-- undoing-changes/V471-V472, branches-and-merging/V473-V474,
-- github-and-remotes/V475-V476, and pull-requests/V477-V478 (see those
-- files for the full rationale).
--
-- Development Question IDs: 225, 226, 227, 228, 229, 230, 231, 232, 233, 234
-- Topic: rebase-and-squash (language: tr)
-- Turkish counterparts of the English questions in V479 -- same learning
-- objectives, not literal translations. Generated by Claude and
-- auto-published via the same AI-Judge auto-publish endpoint after the
-- same self-review -- see chat transcript.

-- Each question is RE-INSERTED here with its full content via
-- WITH ... RETURNING id (question-promotion/V431's mechanism) -- portable to
-- any environment, no hardcoded foreign ids. topic_id is resolved by
-- Topic.slug, and the quiz is resolved by (topic slug, language='tr', quiz
-- slug='default') -- the EXISTING fixed quiz for this topic, not a new one.
--
-- Content was captured AFTER these questions were auto-published (status=
-- PUBLISHED, reviewed_by='n8n-ai-judge', real reviewed_at) -- NOT before, per
-- the lesson learned while building git-fundamentals/V468 (bkz.
-- docs/known-constraints.md): a fallback branch generated from pre-publish
-- content would silently create PENDING_REVIEW rows on any fresh database.
--
-- Duplicate-safety: each block first checks whether an equivalent question
-- row (same topic_id + language='tr' + exact question text) already
-- exists, and only INSERTs when it doesn't -- portable to a fresh database,
-- and a safe no-op if re-run against this development database (where the
-- content already exists from live ingestion). The quiz_question_link insert
-- carries ON CONFLICT DO NOTHING as a second safety net (UNIQUE(quiz_id,
-- question_id), UNIQUE(quiz_id, position) from V290).


-- Question 1/10 (dev id 225, quiz position 1)
WITH existing_q1 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Derse göre rebase etmek, temelde nedir?$$
),
inserted_q1 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre rebase etmek, temelde nedir?$$, NULL, NULL,
           $$Rebase etmek, bir branch'teki commit'leri alıp farklı bir başlangıç noktasının üzerine tek tek yeniden oynatır — yeniden oynatılan commit'ler yeni hash'ler alır, ama işin içeriği birebir korunur.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.802814',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q1)
    RETURNING id
),
target_q1 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q1
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q1
),
option_ins_q1 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q1.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q1
             CROSS JOIN (VALUES
    ($$Bir branch'teki commit'leri alıp, farklı bir başlangıç noktasının üzerine tek tek yeniden oynatmak — commit'ler yeni hash'ler alır ama içerik korunur.$$, TRUE, 0),
    ($$Bir branch'in commit'lerini silip geçmişini sıfırdan başlatmak.$$, FALSE, 1),
    ($$Hiçbir yeni commit oluşturmadan iki branch'i kalıcı olarak birleştirmenin bir yolu.$$, FALSE, 2),
    ($$Yerel bir Git komutu karşılığı olmayan, yalnızca GitHub'a özgü bir özellik.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q1.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q1.id, 1
FROM target_q1
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 2/10 (dev id 226, quiz position 2)
WITH existing_q2 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Derse göre, bir merge ile bir rebase arasında ortaya çıkan geçmiş nasıl farklıdır?$$
),
inserted_q2 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre, bir merge ile bir rebase arasında ortaya çıkan geçmiş nasıl farklıdır?$$, NULL, NULL,
           $$Merge, gerçekte ne olduğunu bir merge commit'i dahil birebir korur; rebase ise branch'in commit'lerini, gerçekte ne olduğunu artık mükemmel yansıtmama pahasına, temiz, doğrusal bir hikayeye yeniden yazar.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.823033',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q2)
    RETURNING id
),
target_q2 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q2
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q2
),
option_ins_q2 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q2.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q2
             CROSS JOIN (VALUES
    ($$Merge her zaman doğrusal bir geçmiş üretir, rebase ise her zaman bir merge commit'i üretir.$$, FALSE, 0),
    ($$Merge, gerçekte ne olduğunu bir merge commit'i dahil birebir korur; rebase ise branch'in commit'lerini, gerçekte ne olduğunu artık mükemmel yansıtmayan, temiz, doğrusal bir hikayeye yeniden yazar.$$, TRUE, 1),
    ($$İkisi de birebir aynı geçmişi üretir — tek fark hangi komutu yazdığındır.$$, FALSE, 2),
    ($$Rebase orijinal commit hash'lerini korur, merge ise her zaman yenilerini oluşturur.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q2.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q2.id, 2
FROM target_q2
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 3/10 (dev id 227, quiz position 3)
WITH existing_q3 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Feature branch'inde `git rebase main` çalıştırıyorsun, ve branch'lediğinden beri `main` hiç değişmedi. Ne olur?$$
),
inserted_q3 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Feature branch'inde `git rebase main` çalıştırıyorsun, ve branch'lediğinden beri `main` hiç değişmedi. Ne olur?$$, NULL, NULL,
           $$Branch'lediğinden beri `main` değişmediyse, commit'lerinin üzerine yeniden oynatılacağı yeni bir şey yoktur, bu yüzden rebase'in yapacak bir şeyi yoktur.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.83363',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q3)
    RETURNING id
),
target_q3 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q3
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q3
),
option_ins_q3 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q3.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q3
             CROSS JOIN (VALUES
    ($$Git, artık gereksiz oldukları için feature branch'inin commit'lerini siler.$$, FALSE, 0),
    ($$Git, iki branch'i birleştiren bir merge commit'i oluşturur.$$, FALSE, 1),
    ($$Yapılacak bir şey yoktur — `main` hareket etmediği için, commit'lerini üzerine yeniden oynatacağın yeni bir şey yoktur.$$, TRUE, 2),
    ($$Git, rebase'i çalıştırmayı reddeder ve bir hata gösterir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q3.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q3.id, 3
FROM target_q3
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 4/10 (dev id 228, quiz position 4)
WITH existing_q4 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$`git rebase -i`, düz bir `git rebase`'in yapmadığı neyi yapmana izin verir?$$
),
inserted_q4 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git rebase -i`, düz bir `git rebase`'in yapmadığı neyi yapmana izin verir?$$, NULL, NULL,
           $$`git rebase -i`, branch'inin commit'lerini listeleyen bir editör açar ve her birine ne olacağına karar vermene izin verir — yeniden sıralama, birleştirme, düzenleme ya da düşürme — düz bir rebase gibi yalnızca onları yeniden oynatmakla kalmaz.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.841061',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q4)
    RETURNING id
),
target_q4 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q4
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q4
),
option_ins_q4 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q4.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q4
             CROSS JOIN (VALUES
    ($$Yerel bir branch yerine remote bir branch üzerine rebase etmene.$$, FALSE, 0),
    ($$Conflict çözümünü tamamen atlamana.$$, FALSE, 1),
    ($$Hiçbir commit hash'ini değiştirmeden rebase etmene.$$, FALSE, 2),
    ($$Her bireysel commit'e ne olacağına karar vermene — yalnızca onları yeniden oynatmakla kalmayıp yeniden sıralamana, birleştirmene, düzenlemene ya da düşürmene.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q4.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q4.id, 4
FROM target_q4
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 5/10 (dev id 229, quiz position 5)
WITH existing_q5 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Interactive rebase'de `squash` ile `fixup` arasındaki fark nedir?$$
),
inserted_q5 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Interactive rebase'de `squash` ile `fixup` arasındaki fark nedir?$$, NULL, NULL,
           $$Hem `squash` hem `fixup`, bir commit'i üstündeki commit'e birleştirir, ama `fixup` birleştirilen commit'in mesajını sessizce atarken, `squash` yeni, birleşik bir commit mesajı yazmana izin verir.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.848594',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q5)
    RETURNING id
),
target_q5 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q5
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q5
),
option_ins_q5 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q5.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q5
             CROSS JOIN (VALUES
    ($$İkisi de bir commit'i üstündeki commit'e birleştirir, ama `fixup` birleştirilen commit'in mesajını sessizce atarken `squash` yeni, birleşik bir mesaj yazmana izin verir.$$, TRUE, 0),
    ($$`squash` commit'i tamamen siler, `fixup` ise onu ayrı bir commit olarak tutar.$$, FALSE, 1),
    ($$`fixup` yalnızca listedeki ilk commit'te kullanılabilir, `squash` ise her yerde kullanılabilir.$$, FALSE, 2),
    ($$`squash` ve `fixup`, aralarında hiçbir fark olmayan, tamamen aynı işlemin iki farklı ismidir.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q5.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q5.id, 5
FROM target_q5
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 6/10 (dev id 230, quiz position 6)
WITH existing_q6 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Ders, 'rebase hakkındaki en önemli tek kural' olarak neyi adlandırıyor?$$
),
inserted_q6 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Ders, 'rebase hakkındaki en önemli tek kural' olarak neyi adlandırıyor?$$, NULL, NULL,
           $$Ders bunu açıkça 'rebase hakkındaki en önemli tek kural' olarak adlandırıyor: başkalarının zaten pull ettiği commit'leri asla rebase etme, çünkü bu, yeniden oynatılan her commit'e yeni bir hash verir ve onların geçmişini seninkinden ayırır.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.855456',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q6)
    RETURNING id
),
target_q6 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q6
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q6
),
option_ins_q6 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q6.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q6
             CROSS JOIN (VALUES
    ($$Her zaman düz bir `git rebase` yerine `git rebase -i` çalıştır.$$, FALSE, 0),
    ($$Başkalarının zaten pull ettiği commit'leri asla rebase etme.$$, TRUE, 1),
    ($$Bir Pull Request'i merge etmeden önce her zaman her commit'i squash et.$$, FALSE, 2),
    ($$Bir rebase başladıktan sonra `git rebase --abort`'u asla kullanma.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q6.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q6.id, 6
FROM target_q6
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 7/10 (dev id 231, quiz position 7)
WITH existing_q7 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Zaten push edilmiş bir branch'i rebase ettikten sonra, normal bir `git push` neden reddedilir?$$
),
inserted_q7 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'SINGLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Zaten push edilmiş bir branch'i rebase ettikten sonra, normal bir `git push` neden reddedilir?$$, NULL, NULL,
           $$Rebase etmek commit'lerine yeni hash'ler verir, bu yüzden yerel branch'in ve zaten push edilmiş remote karşılığı artık farklı geçmişlere sahiptir — Git, remote'ta senin sahip olmadığın commit'ler olduğunu görür ve push'u bir güvenlik kontrolü olarak reddeder.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.862793',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q7)
    RETURNING id
),
target_q7 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q7
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q7
),
option_ins_q7 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q7.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q7
             CROSS JOIN (VALUES
    ($$Çünkü herhangi bir rebase devam ederken `git push` devre dışıdır.$$, FALSE, 0),
    ($$Çünkü rebase edilmiş branch'ler yalnızca bir repository admin'i tarafından push edilebilir.$$, FALSE, 1),
    ($$Çünkü rebase etmek commit'lerine yeni hash'ler verir, bu yüzden Git remote'ta senin sahip olmadığın commit'ler olduğunu görür ve bir güvenlik kontrolü olarak reddeder.$$, TRUE, 2),
    ($$Çünkü GitHub, açık bir Pull Request'e dahil olan branch'lere tüm push'ları engeller.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q7.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q7.id, 7
FROM target_q7
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 8/10 (dev id 232, quiz position 8)
WITH existing_q8 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$`git push --force` ile `git push --force-with-lease` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q8 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$`git push --force` ile `git push --force-with-lease` hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$`--force`, son fetch'inden beri oraya push edilmiş commit'leri sessizce atarak remote branch'in üzerine koşulsuz yazar. `--force-with-lease` önce kontrol eder ve remote beklenmedik şekilde değiştiyse reddeder, üzerine yazmak yerine güvenle başarısız olur.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.868886',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q8)
    RETURNING id
),
target_q8 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q8
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q8
),
option_ins_q8 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q8.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q8
             CROSS JOIN (VALUES
    ($$`--force`, son fetch'inden beri başka birinin push etmiş olabileceği commit'ler dahil, remote branch'in üzerine koşulsuz yazar.$$, TRUE, 0),
    ($$`--force-with-lease`, remote branch'i kimse değiştirmemiş olsa bile her zaman başarısız olur.$$, FALSE, 1),
    ($$`--force-with-lease` önce kontrol eder ve remote branch son fetch'inden beri değiştiyse reddeder.$$, TRUE, 2),
    ($$`--force` ve `--force-with-lease`, her durumda birebir aynı şekilde davranır.$$, FALSE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q8.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q8.id, 8
FROM target_q8
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 9/10 (dev id 233, quiz position 9)
WITH existing_q9 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Derse göre bir rebase sırasında conflict'leri çözmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q9 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Derse göre bir rebase sırasında conflict'leri çözmek hakkında aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Bir rebase sırasında çakışan bir dosyayı çözdükten sonra, onu stage'ler ve devam etmek için `git rebase --continue` çalıştırırsın. `git rebase --abort` her zaman güvenlidir — tüm rebase'i iptal eder ve seni tam olarak başladığın yere geri götürür.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.875306',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q9)
    RETURNING id
),
target_q9 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q9
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q9
),
option_ins_q9 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q9.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q9
             CROSS JOIN (VALUES
    ($$Bir rebase conflict'i yalnızca bir kez, tüm sürecin en sonunda olabilir.$$, FALSE, 0),
    ($$Çakışan bir dosyayı çözdükten sonra, onu stage'ler ve devam etmek için `git rebase --continue` çalıştırırsın.$$, TRUE, 1),
    ($$`git rebase --abort` tehlikelidir ve branch'ini bozuk, öngörülemez bir durumda bırakabilir.$$, FALSE, 2),
    ($$`git rebase --abort`, tüm rebase'i iptal eder ve seni güvenle tam olarak başladığın yere geri götürür.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q9.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q9.id, 9
FROM target_q9
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;


-- Question 10/10 (dev id 234, quiz position 10)
WITH existing_q10 AS (
    SELECT id FROM question
    WHERE topic_id = (SELECT id FROM topic WHERE slug = 'rebase-and-squash')
      AND language = 'tr'
      AND question = $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$
),
inserted_q10 AS (
    INSERT INTO question (topic_id, language, type, difficulty, status, source,
                           question, code_snippet, code_language, explanation,
                           reviewed_by, reviewed_at, created_at, updated_at)
    SELECT id, 'tr', 'MULTIPLE_CHOICE', 'BEGINNER', 'PUBLISHED', 'CLAUDE',
           $$Dersin Yaygın Hatalar ve En İyi Pratikler bölümlerine göre aşağıdakilerden hangileri doğrudur? (Uygun olanların hepsini seçin)$$, NULL, NULL,
           $$Dersin Yaygın Hatalar bölümü, zaten pull edilmiş commit'leri rebase etmeyi, rebase'in gerçek sorunlara yol açmasının en yaygın tek yolu olarak adlandırıyor, En İyi Pratikler bölümü ise inceleme istemeden önce 'fix typo' tarzı commit'leri squash etmek için `git rebase -i` kullanmayı öneriyor.$$, 'n8n-ai-judge', '2026-08-29 20:49:08.882639',
           now(), now()
    FROM topic
    WHERE slug = 'rebase-and-squash'
      AND NOT EXISTS (SELECT 1 FROM existing_q10)
    RETURNING id
),
target_q10 AS (
    SELECT id, TRUE AS newly_inserted FROM inserted_q10
    UNION ALL
    SELECT id, FALSE AS newly_inserted FROM existing_q10
),
option_ins_q10 AS (
    INSERT INTO question_option (question_id, option_text, is_correct, sort_order)
    SELECT target_q10.id, v.option_text, v.is_correct, v.sort_order
    FROM target_q10
             CROSS JOIN (VALUES
    ($$Başkalarının zaten pull ettiği bir branch'i rebase etmek, rebase'in bir takımda gerçek sorunlara yol açmasının en yaygın tek yoludur.$$, TRUE, 0),
    ($$Yazması daha kolay olduğu için düz `--force`'u `--force-with-lease` yerine varsayılan yapmalısın.$$, FALSE, 1),
    ($$Bir rebase conflict'i başladığında, iptal etmek güvensizdir ve her ne pahasına olursa olsun kaçınılmalıdır.$$, FALSE, 2),
    ($$İnceleme istemeden önce 'fix typo' tarzı commit'leri ebeveynlerine squash etmek için `git rebase -i` kullanmak iyi bir pratiktir.$$, TRUE, 3)
        ) AS v(option_text, is_correct, sort_order)
    WHERE target_q10.newly_inserted
    RETURNING 1
)
INSERT INTO quiz_question_link (quiz_id, question_id, position)
SELECT quiz.id, target_q10.id, 10
FROM target_q10
         JOIN quiz ON TRUE
         JOIN topic t ON t.id = quiz.topic_id
WHERE t.slug = 'rebase-and-squash'
  AND quiz.language = 'tr'
  AND quiz.slug = 'default'
ON CONFLICT (quiz_id, question_id) DO NOTHING;

